/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.project.dao.impl;

import org.springframework.stereotype.Repository;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.jdbctemplatedslsession.callback.*;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;
import org.tinygroup.sdpm.project.dao.BurnDao;
import org.tinygroup.sdpm.project.dao.pojo.Burn;
import org.tinygroup.tinysqldsl.*;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;

import java.io.Serializable;
import java.util.List;

import static org.tinygroup.sdpm.project.dao.constant.BurnTable.BURNTABLE;
import static org.tinygroup.tinysqldsl.Delete.delete;
import static org.tinygroup.tinysqldsl.Insert.insertInto;
import static org.tinygroup.tinysqldsl.Select.selectFrom;
import static org.tinygroup.tinysqldsl.Update.update;
import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;

@Repository
public class BurnDaoImpl extends TinyDslDaoSupport implements BurnDao {

	public Burn add(Burn burn) {
		return getDslTemplate().insertAndReturnKey(burn, new InsertGenerateCallback<Burn>() {
			public Insert generate(Burn t) {
				Insert insert = insertInto(BURNTABLE).values(
						BURNTABLE.ID.value(t.getId()),
					BURNTABLE.PROJECT_ID.value(t.getProjectId()),
					BURNTABLE.BURN_DATE.value(t.getBurnDate()),
					BURNTABLE.BURN_LEFT.value(t.getBurnLeft()),
					BURNTABLE.BURN_CONSUMED.value(t.getBurnConsumed()));
				return insert;
			}
		});
	}

	public int edit(Burn burn) {
		if (burn == null || burn.getId() == null) {
			return 0;
		}
		return getDslTemplate().update(burn, new UpdateGenerateCallback<Burn>() {
			public Update generate(Burn t) {
				Update update = update(BURNTABLE).set(
						BURNTABLE.PROJECT_ID.value(t.getProjectId()),
					BURNTABLE.BURN_DATE.value(t.getBurnDate()),
					BURNTABLE.BURN_LEFT.value(t.getBurnLeft()),
					BURNTABLE.BURN_CONSUMED.value(t.getBurnConsumed())).where(
						BURNTABLE.ID.eq(t.getId()));
				return update;
			}
		});
	}

	public int deleteByKey(Integer pk){
		if(pk == null){
			return 0;
		}
		return getDslTemplate().deleteByKey(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(BURNTABLE).where(BURNTABLE.ID.eq(pk));
			}
		});
	}

	public int deleteByKeys(Integer... pks) {
		if(pks == null || pks.length == 0){
			return 0;
		}
		return getDslTemplate().deleteByKeys(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(BURNTABLE).where(BURNTABLE.ID.in(t));
		}
		},pks);
	}

	public Burn getByKey(Integer pk) {
		return getDslTemplate().getByKey(pk, Burn.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(BURNTABLE).where(BURNTABLE.ID.eq(t));
			}
		});
	}

	public List<Burn> query(Burn burn) {
		if(burn==null){
			burn=new Burn();
		}
		return getDslTemplate().query(burn, new SelectGenerateCallback<Burn>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Burn t) {
				return selectFrom(BURNTABLE).where(
				and(
						BURNTABLE.PROJECT_ID.eq(t.getProjectId()),
					BURNTABLE.BURN_DATE.eq(t.getBurnDate()),
					BURNTABLE.BURN_LEFT.eq(t.getBurnLeft()),
					BURNTABLE.BURN_CONSUMED.eq(t.getBurnConsumed())));
			}
		});
	}

	public Pager<Burn> queryPager(int start,int limit ,Burn burn) {
		if(burn==null){
			burn=new Burn();
		}
		return getDslTemplate().queryPager(start, limit, burn, false, new SelectGenerateCallback<Burn>() {

			public Select generate(Burn t) {
				return MysqlSelect.selectFrom(BURNTABLE).where(
				and(
						BURNTABLE.PROJECT_ID.eq(t.getProjectId()),
					BURNTABLE.BURN_DATE.eq(t.getBurnDate()),
					BURNTABLE.BURN_LEFT.eq(t.getBurnLeft()),
					BURNTABLE.BURN_CONSUMED.eq(t.getBurnConsumed())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Burn> burns) {
		if (CollectionUtil.isEmpty(burns)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, burns, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(BURNTABLE).values(
						BURNTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					BURNTABLE.BURN_DATE.value(new JdbcNamedParameter("burnDate")),
					BURNTABLE.BURN_LEFT.value(new JdbcNamedParameter("burnLeft")),
					BURNTABLE.BURN_CONSUMED.value(new JdbcNamedParameter("burnConsumed")));
			}
		});
	}

	public int[] batchInsert(List<Burn> burns){
			return batchInsert(true ,burns);
	}

	public int[] batchUpdate(List<Burn> burns) {
		if (CollectionUtil.isEmpty(burns)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(burns, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(BURNTABLE).set(
						BURNTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					BURNTABLE.BURN_DATE.value(new JdbcNamedParameter("burnDate")),
					BURNTABLE.BURN_LEFT.value(new JdbcNamedParameter("burnLeft")),
					BURNTABLE.BURN_CONSUMED.value(new JdbcNamedParameter("burnConsumed"))).where(
						BURNTABLE.ID.eq(new JdbcNamedParameter("id")));
			}
		});
	}

	public int[] batchDelete(List<Burn> burns) {
		if (CollectionUtil.isEmpty(burns)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(burns, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(BURNTABLE).where(and(
						BURNTABLE.ID.eq(new JdbcNamedParameter("id")),
				BURNTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				BURNTABLE.BURN_DATE.eq(new JdbcNamedParameter("burnDate")),
				BURNTABLE.BURN_LEFT.eq(new JdbcNamedParameter("burnLeft")),
				BURNTABLE.BURN_CONSUMED.eq(new JdbcNamedParameter("burnConsumed"))));
			}
		});
	}

}
