/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.service.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.service.constant.ClientUserTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.service.pojo.ClientUser;
import org.tinygroup.sdpm.service.inter.ClientUserDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class ClientUserDaoImpl extends TinyDslDaoSupport implements ClientUserDao {

	public ClientUser insertObject(ClientUser clientUser) {
		return getDslTemplate().insertObject(clientUser, new InsertGenerateCallback<ClientUser>() {
			public Insert generate(ClientUser t) {
				Insert insert = insertInto(CLIENTUSERTABLE).values(
					CLIENTUSERTABLE.CLIENT_USER_ID.value(t.getClientUserId()),
					CLIENTUSERTABLE.CLIENT_NAME.value(t.getClientName()),
					CLIENTUSERTABLE.USER_ACCOUNT.value(t.getUserAccount()));
				return insert;
			}
		});
	}

	public ClientUser insertObject(boolean autoGeneratedKeys ,ClientUser clientUser) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,clientUser, new InsertGenerateCallback<ClientUser>() {

			public Insert generate(ClientUser t) {
				Insert insert = insertInto(CLIENTUSERTABLE).values(
					CLIENTUSERTABLE.CLIENT_USER_ID.value(t.getClientUserId()),
					CLIENTUSERTABLE.CLIENT_NAME.value(t.getClientName()),
					CLIENTUSERTABLE.USER_ACCOUNT.value(t.getUserAccount()));
				return insert;
			}
		});
	}

	public int updateObject(ClientUser clientUser) {
		return getDslTemplate().updateObject(clientUser, new UpdateGenerateCallback<ClientUser>() {
			public Update generate(ClientUser t) {
				Update update = update(CLIENTUSERTABLE).set(
					CLIENTUSERTABLE.CLIENT_NAME.value(t.getClientName()),
					CLIENTUSERTABLE.USER_ACCOUNT.value(t.getUserAccount())).where(
					CLIENTUSERTABLE.CLIENT_USER_ID.eq(t.getClientUserId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(CLIENTUSERTABLE).where(CLIENTUSERTABLE.CLIENT_USER_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(CLIENTUSERTABLE).where(CLIENTUSERTABLE.CLIENT_USER_ID.in(t));
		}
		},pks);
	}

	public ClientUser getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, ClientUser.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(CLIENTUSERTABLE).where(CLIENTUSERTABLE.CLIENT_USER_ID.eq(t));
			}
		});
	}

	public List<ClientUser> queryObjects(ClientUser clientUser) {
		if(clientUser==null){
			clientUser=new ClientUser();
		}
		return getDslTemplate().queryObjects(clientUser, new SelectGenerateCallback<ClientUser>() {

			@SuppressWarnings("rawtypes")
			public Select generate(ClientUser t) {
				return selectFrom(CLIENTUSERTABLE).where(
				and(
					CLIENTUSERTABLE.CLIENT_NAME.eq(t.getClientName()),
					CLIENTUSERTABLE.USER_ACCOUNT.eq(t.getUserAccount())));
			}
		});
	}

	public Pager<ClientUser> queryObjectsForPage(int start,int limit ,ClientUser clientUser) {
		if(clientUser==null){
			clientUser=new ClientUser();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, clientUser, false, new SelectGenerateCallback<ClientUser>() {

			public Select generate(ClientUser t) {
				return MysqlSelect.selectFrom(CLIENTUSERTABLE).where(
				and(
					CLIENTUSERTABLE.CLIENT_NAME.eq(t.getClientName()),
					CLIENTUSERTABLE.USER_ACCOUNT.eq(t.getUserAccount())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<ClientUser> clientUsers) {
		if (CollectionUtil.isEmpty(clientUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, clientUsers, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(CLIENTUSERTABLE).values(
					CLIENTUSERTABLE.CLIENT_NAME.value(new JdbcNamedParameter("clientName")),
					CLIENTUSERTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")));
			}
		});
	}

	public int[] batchInsert(List<ClientUser> clientUsers){
			return batchInsert(true ,clientUsers);
	}

	public int[] batchUpdate(List<ClientUser> clientUsers) {
		if (CollectionUtil.isEmpty(clientUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(clientUsers, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(CLIENTUSERTABLE).set(
					CLIENTUSERTABLE.CLIENT_NAME.value(new JdbcNamedParameter("clientName")),
					CLIENTUSERTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount"))).where(
				CLIENTUSERTABLE.CLIENT_USER_ID.eq(new JdbcNamedParameter("clientUserId")));
			}
		});
	}

	public int[] batchDelete(List<ClientUser> clientUsers) {
		if (CollectionUtil.isEmpty(clientUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(clientUsers, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(CLIENTUSERTABLE).where(and(
				CLIENTUSERTABLE.CLIENT_USER_ID.eq(new JdbcNamedParameter("clientUserId")),
				CLIENTUSERTABLE.CLIENT_NAME.eq(new JdbcNamedParameter("clientName")),
				CLIENTUSERTABLE.USER_ACCOUNT.eq(new JdbcNamedParameter("userAccount"))));
			}
		});
	}

}
