/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.service.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.service.constant.FaqTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.service.pojo.Faq;
import org.tinygroup.sdpm.service.inter.FaqDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class FaqDaoImpl extends TinyDslDaoSupport implements FaqDao {

	public Faq insertObject(Faq faq) {
		return getDslTemplate().insertObject(faq, new InsertGenerateCallback<Faq>() {
			public Insert generate(Faq t) {
				Insert insert = insertInto(FAQTABLE).values(
					FAQTABLE.FAQ_ID.value(t.getFaqId()),
					FAQTABLE.COMPANY_ID.value(t.getCompanyId()),
					FAQTABLE.FAQ_TYPE.value(t.getFaqType()),
					FAQTABLE.FAQ_QUESTION.value(t.getFaqQuestion()),
					FAQTABLE.FAQ_ANSWER.value(t.getFaqAnswer()),
					FAQTABLE.PRODUCT_ID.value(t.getProductId()),
					FAQTABLE.FAQ_KEYWORDS.value(t.getFaqKeywords()),
					FAQTABLE.FAQ_SOURCE.value(t.getFaqSource()),
					FAQTABLE.FAQ_SOURCE_ID.value(t.getFaqSourceId()),
					FAQTABLE.FAQ_CREATED_BY.value(t.getFaqCreatedBy()),
					FAQTABLE.FAQ_CREATE_DATE.value(t.getFaqCreateDate()),
					FAQTABLE.FAQ_REPLIED_BY.value(t.getFaqRepliedBy()),
					FAQTABLE.FAQ_REPLY_DATE.value(t.getFaqReplyDate()),
					FAQTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Faq insertObject(boolean autoGeneratedKeys ,Faq faq) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,faq, new InsertGenerateCallback<Faq>() {

			public Insert generate(Faq t) {
				Insert insert = insertInto(FAQTABLE).values(
					FAQTABLE.FAQ_ID.value(t.getFaqId()),
					FAQTABLE.COMPANY_ID.value(t.getCompanyId()),
					FAQTABLE.FAQ_TYPE.value(t.getFaqType()),
					FAQTABLE.FAQ_QUESTION.value(t.getFaqQuestion()),
					FAQTABLE.FAQ_ANSWER.value(t.getFaqAnswer()),
					FAQTABLE.PRODUCT_ID.value(t.getProductId()),
					FAQTABLE.FAQ_KEYWORDS.value(t.getFaqKeywords()),
					FAQTABLE.FAQ_SOURCE.value(t.getFaqSource()),
					FAQTABLE.FAQ_SOURCE_ID.value(t.getFaqSourceId()),
					FAQTABLE.FAQ_CREATED_BY.value(t.getFaqCreatedBy()),
					FAQTABLE.FAQ_CREATE_DATE.value(t.getFaqCreateDate()),
					FAQTABLE.FAQ_REPLIED_BY.value(t.getFaqRepliedBy()),
					FAQTABLE.FAQ_REPLY_DATE.value(t.getFaqReplyDate()),
					FAQTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Faq faq) {
		return getDslTemplate().updateObject(faq, new UpdateGenerateCallback<Faq>() {
			public Update generate(Faq t) {
				Update update = update(FAQTABLE).set(
					FAQTABLE.COMPANY_ID.value(t.getCompanyId()),
					FAQTABLE.FAQ_TYPE.value(t.getFaqType()),
					FAQTABLE.FAQ_QUESTION.value(t.getFaqQuestion()),
					FAQTABLE.FAQ_ANSWER.value(t.getFaqAnswer()),
					FAQTABLE.PRODUCT_ID.value(t.getProductId()),
					FAQTABLE.FAQ_KEYWORDS.value(t.getFaqKeywords()),
					FAQTABLE.FAQ_SOURCE.value(t.getFaqSource()),
					FAQTABLE.FAQ_SOURCE_ID.value(t.getFaqSourceId()),
					FAQTABLE.FAQ_CREATED_BY.value(t.getFaqCreatedBy()),
					FAQTABLE.FAQ_CREATE_DATE.value(t.getFaqCreateDate()),
					FAQTABLE.FAQ_REPLIED_BY.value(t.getFaqRepliedBy()),
					FAQTABLE.FAQ_REPLY_DATE.value(t.getFaqReplyDate()),
					FAQTABLE.DELETED.value(t.getDeleted())).where(
					FAQTABLE.FAQ_ID.eq(t.getFaqId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(FAQTABLE).where(FAQTABLE.FAQ_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(FAQTABLE).where(FAQTABLE.FAQ_ID.in(t));
		}
		},pks);
	}

	public Faq getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Faq.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(FAQTABLE).where(FAQTABLE.FAQ_ID.eq(t));
			}
		});
	}

	public List<Faq> queryObjects(Faq faq) {
		if(faq==null){
			faq=new Faq();
		}
		return getDslTemplate().queryObjects(faq, new SelectGenerateCallback<Faq>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Faq t) {
				return selectFrom(FAQTABLE).where(
				and(
					FAQTABLE.COMPANY_ID.eq(t.getCompanyId()),
					FAQTABLE.FAQ_TYPE.eq(t.getFaqType()),
					FAQTABLE.FAQ_QUESTION.eq(t.getFaqQuestion()),
					FAQTABLE.FAQ_ANSWER.eq(t.getFaqAnswer()),
					FAQTABLE.PRODUCT_ID.eq(t.getProductId()),
					FAQTABLE.FAQ_KEYWORDS.eq(t.getFaqKeywords()),
					FAQTABLE.FAQ_SOURCE.eq(t.getFaqSource()),
					FAQTABLE.FAQ_SOURCE_ID.eq(t.getFaqSourceId()),
					FAQTABLE.FAQ_CREATED_BY.eq(t.getFaqCreatedBy()),
					FAQTABLE.FAQ_CREATE_DATE.eq(t.getFaqCreateDate()),
					FAQTABLE.FAQ_REPLIED_BY.eq(t.getFaqRepliedBy()),
					FAQTABLE.FAQ_REPLY_DATE.eq(t.getFaqReplyDate()),
					FAQTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Faq> queryObjectsForPage(int start,int limit ,Faq faq) {
		if(faq==null){
			faq=new Faq();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, faq, false, new SelectGenerateCallback<Faq>() {

			public Select generate(Faq t) {
				return MysqlSelect.selectFrom(FAQTABLE).where(
				and(
					FAQTABLE.COMPANY_ID.eq(t.getCompanyId()),
					FAQTABLE.FAQ_TYPE.eq(t.getFaqType()),
					FAQTABLE.FAQ_QUESTION.eq(t.getFaqQuestion()),
					FAQTABLE.FAQ_ANSWER.eq(t.getFaqAnswer()),
					FAQTABLE.PRODUCT_ID.eq(t.getProductId()),
					FAQTABLE.FAQ_KEYWORDS.eq(t.getFaqKeywords()),
					FAQTABLE.FAQ_SOURCE.eq(t.getFaqSource()),
					FAQTABLE.FAQ_SOURCE_ID.eq(t.getFaqSourceId()),
					FAQTABLE.FAQ_CREATED_BY.eq(t.getFaqCreatedBy()),
					FAQTABLE.FAQ_CREATE_DATE.eq(t.getFaqCreateDate()),
					FAQTABLE.FAQ_REPLIED_BY.eq(t.getFaqRepliedBy()),
					FAQTABLE.FAQ_REPLY_DATE.eq(t.getFaqReplyDate()),
					FAQTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Faq> faqs) {
		if (CollectionUtil.isEmpty(faqs)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, faqs, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(FAQTABLE).values(
					FAQTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					FAQTABLE.FAQ_TYPE.value(new JdbcNamedParameter("faqType")),
					FAQTABLE.FAQ_QUESTION.value(new JdbcNamedParameter("faqQuestion")),
					FAQTABLE.FAQ_ANSWER.value(new JdbcNamedParameter("faqAnswer")),
					FAQTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					FAQTABLE.FAQ_KEYWORDS.value(new JdbcNamedParameter("faqKeywords")),
					FAQTABLE.FAQ_SOURCE.value(new JdbcNamedParameter("faqSource")),
					FAQTABLE.FAQ_SOURCE_ID.value(new JdbcNamedParameter("faqSourceId")),
					FAQTABLE.FAQ_CREATED_BY.value(new JdbcNamedParameter("faqCreatedBy")),
					FAQTABLE.FAQ_CREATE_DATE.value(new JdbcNamedParameter("faqCreateDate")),
					FAQTABLE.FAQ_REPLIED_BY.value(new JdbcNamedParameter("faqRepliedBy")),
					FAQTABLE.FAQ_REPLY_DATE.value(new JdbcNamedParameter("faqReplyDate")),
					FAQTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Faq> faqs){
			return batchInsert(true ,faqs);
	}

	public int[] batchUpdate(List<Faq> faqs) {
		if (CollectionUtil.isEmpty(faqs)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(faqs, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(FAQTABLE).set(
					FAQTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					FAQTABLE.FAQ_TYPE.value(new JdbcNamedParameter("faqType")),
					FAQTABLE.FAQ_QUESTION.value(new JdbcNamedParameter("faqQuestion")),
					FAQTABLE.FAQ_ANSWER.value(new JdbcNamedParameter("faqAnswer")),
					FAQTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					FAQTABLE.FAQ_KEYWORDS.value(new JdbcNamedParameter("faqKeywords")),
					FAQTABLE.FAQ_SOURCE.value(new JdbcNamedParameter("faqSource")),
					FAQTABLE.FAQ_SOURCE_ID.value(new JdbcNamedParameter("faqSourceId")),
					FAQTABLE.FAQ_CREATED_BY.value(new JdbcNamedParameter("faqCreatedBy")),
					FAQTABLE.FAQ_CREATE_DATE.value(new JdbcNamedParameter("faqCreateDate")),
					FAQTABLE.FAQ_REPLIED_BY.value(new JdbcNamedParameter("faqRepliedBy")),
					FAQTABLE.FAQ_REPLY_DATE.value(new JdbcNamedParameter("faqReplyDate")),
					FAQTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				FAQTABLE.FAQ_ID.eq(new JdbcNamedParameter("faqId")));
			}
		});
	}

	public int[] batchDelete(List<Faq> faqs) {
		if (CollectionUtil.isEmpty(faqs)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(faqs, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(FAQTABLE).where(and(
				FAQTABLE.FAQ_ID.eq(new JdbcNamedParameter("faqId")),
				FAQTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				FAQTABLE.FAQ_TYPE.eq(new JdbcNamedParameter("faqType")),
				FAQTABLE.FAQ_QUESTION.eq(new JdbcNamedParameter("faqQuestion")),
				FAQTABLE.FAQ_ANSWER.eq(new JdbcNamedParameter("faqAnswer")),
				FAQTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				FAQTABLE.FAQ_KEYWORDS.eq(new JdbcNamedParameter("faqKeywords")),
				FAQTABLE.FAQ_SOURCE.eq(new JdbcNamedParameter("faqSource")),
				FAQTABLE.FAQ_SOURCE_ID.eq(new JdbcNamedParameter("faqSourceId")),
				FAQTABLE.FAQ_CREATED_BY.eq(new JdbcNamedParameter("faqCreatedBy")),
				FAQTABLE.FAQ_CREATE_DATE.eq(new JdbcNamedParameter("faqCreateDate")),
				FAQTABLE.FAQ_REPLIED_BY.eq(new JdbcNamedParameter("faqRepliedBy")),
				FAQTABLE.FAQ_REPLY_DATE.eq(new JdbcNamedParameter("faqReplyDate")),
				FAQTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
