/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.product.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.product.constant.PlanTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.product.pojo.Plan;
import org.tinygroup.sdpm.product.inter.PlanDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class PlanDaoImpl extends TinyDslDaoSupport implements PlanDao {

	public Plan insertObject(Plan plan) {
		return getDslTemplate().insertObject(plan, new InsertGenerateCallback<Plan>() {
			public Insert generate(Plan t) {
				Insert insert = insertInto(PLANTABLE).values(
					PLANTABLE.PLAN_ID.value(t.getPlanId()),
					PLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					PLANTABLE.PRODUCT_ID.value(t.getProductId()),
					PLANTABLE.PLAN_NAME.value(t.getPlanName()),
					PLANTABLE.PLAN_SPEC.value(t.getPlanSpec()),
					PLANTABLE.PLAN_BEGIN_DATE.value(t.getPlanBeginDate()),
					PLANTABLE.PLAN_END_DATE.value(t.getPlanEndDate()),
					PLANTABLE.BUILD_ID.value(t.getBuildId()),
					PLANTABLE.PLAN_RELEASE_DATE.value(t.getPlanReleaseDate()),
					PLANTABLE.PLAN_STORIES.value(t.getPlanStories()),
					PLANTABLE.PLAN_BUGS.value(t.getPlanBugs()),
					PLANTABLE.PLAN_EFFORT.value(t.getPlanEffort()),
					PLANTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Plan insertObject(boolean autoGeneratedKeys ,Plan plan) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,plan, new InsertGenerateCallback<Plan>() {

			public Insert generate(Plan t) {
				Insert insert = insertInto(PLANTABLE).values(
					PLANTABLE.PLAN_ID.value(t.getPlanId()),
					PLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					PLANTABLE.PRODUCT_ID.value(t.getProductId()),
					PLANTABLE.PLAN_NAME.value(t.getPlanName()),
					PLANTABLE.PLAN_SPEC.value(t.getPlanSpec()),
					PLANTABLE.PLAN_BEGIN_DATE.value(t.getPlanBeginDate()),
					PLANTABLE.PLAN_END_DATE.value(t.getPlanEndDate()),
					PLANTABLE.BUILD_ID.value(t.getBuildId()),
					PLANTABLE.PLAN_RELEASE_DATE.value(t.getPlanReleaseDate()),
					PLANTABLE.PLAN_STORIES.value(t.getPlanStories()),
					PLANTABLE.PLAN_BUGS.value(t.getPlanBugs()),
					PLANTABLE.PLAN_EFFORT.value(t.getPlanEffort()),
					PLANTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Plan plan) {
		return getDslTemplate().updateObject(plan, new UpdateGenerateCallback<Plan>() {
			public Update generate(Plan t) {
				Update update = update(PLANTABLE).set(
					PLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					PLANTABLE.PRODUCT_ID.value(t.getProductId()),
					PLANTABLE.PLAN_NAME.value(t.getPlanName()),
					PLANTABLE.PLAN_SPEC.value(t.getPlanSpec()),
					PLANTABLE.PLAN_BEGIN_DATE.value(t.getPlanBeginDate()),
					PLANTABLE.PLAN_END_DATE.value(t.getPlanEndDate()),
					PLANTABLE.BUILD_ID.value(t.getBuildId()),
					PLANTABLE.PLAN_RELEASE_DATE.value(t.getPlanReleaseDate()),
					PLANTABLE.PLAN_STORIES.value(t.getPlanStories()),
					PLANTABLE.PLAN_BUGS.value(t.getPlanBugs()),
					PLANTABLE.PLAN_EFFORT.value(t.getPlanEffort()),
					PLANTABLE.DELETED.value(t.getDeleted())).where(
					PLANTABLE.PLAN_ID.eq(t.getPlanId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(PLANTABLE).where(PLANTABLE.PLAN_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(PLANTABLE).where(PLANTABLE.PLAN_ID.in(t));
		}
		},pks);
	}

	public Plan getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Plan.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(PLANTABLE).where(PLANTABLE.PLAN_ID.eq(t));
			}
		});
	}

	public List<Plan> queryObjects(Plan plan) {
		if(plan==null){
			plan=new Plan();
		}
		return getDslTemplate().queryObjects(plan, new SelectGenerateCallback<Plan>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Plan t) {
				return selectFrom(PLANTABLE).where(
				and(
					PLANTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PLANTABLE.PRODUCT_ID.eq(t.getProductId()),
					PLANTABLE.PLAN_NAME.eq(t.getPlanName()),
					PLANTABLE.PLAN_SPEC.eq(t.getPlanSpec()),
					PLANTABLE.PLAN_BEGIN_DATE.eq(t.getPlanBeginDate()),
					PLANTABLE.PLAN_END_DATE.eq(t.getPlanEndDate()),
					PLANTABLE.BUILD_ID.eq(t.getBuildId()),
					PLANTABLE.PLAN_RELEASE_DATE.eq(t.getPlanReleaseDate()),
					PLANTABLE.PLAN_STORIES.eq(t.getPlanStories()),
					PLANTABLE.PLAN_BUGS.eq(t.getPlanBugs()),
					PLANTABLE.PLAN_EFFORT.eq(t.getPlanEffort()),
					PLANTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Plan> queryObjectsForPage(int start,int limit ,Plan plan) {
		if(plan==null){
			plan=new Plan();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, plan, false, new SelectGenerateCallback<Plan>() {

			public Select generate(Plan t) {
				return MysqlSelect.selectFrom(PLANTABLE).where(
				and(
					PLANTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PLANTABLE.PRODUCT_ID.eq(t.getProductId()),
					PLANTABLE.PLAN_NAME.eq(t.getPlanName()),
					PLANTABLE.PLAN_SPEC.eq(t.getPlanSpec()),
					PLANTABLE.PLAN_BEGIN_DATE.eq(t.getPlanBeginDate()),
					PLANTABLE.PLAN_END_DATE.eq(t.getPlanEndDate()),
					PLANTABLE.BUILD_ID.eq(t.getBuildId()),
					PLANTABLE.PLAN_RELEASE_DATE.eq(t.getPlanReleaseDate()),
					PLANTABLE.PLAN_STORIES.eq(t.getPlanStories()),
					PLANTABLE.PLAN_BUGS.eq(t.getPlanBugs()),
					PLANTABLE.PLAN_EFFORT.eq(t.getPlanEffort()),
					PLANTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Plan> plans) {
		if (CollectionUtil.isEmpty(plans)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, plans, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(PLANTABLE).values(
					PLANTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PLANTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					PLANTABLE.PLAN_NAME.value(new JdbcNamedParameter("planName")),
					PLANTABLE.PLAN_SPEC.value(new JdbcNamedParameter("planSpec")),
					PLANTABLE.PLAN_BEGIN_DATE.value(new JdbcNamedParameter("planBeginDate")),
					PLANTABLE.PLAN_END_DATE.value(new JdbcNamedParameter("planEndDate")),
					PLANTABLE.BUILD_ID.value(new JdbcNamedParameter("buildId")),
					PLANTABLE.PLAN_RELEASE_DATE.value(new JdbcNamedParameter("planReleaseDate")),
					PLANTABLE.PLAN_STORIES.value(new JdbcNamedParameter("planStories")),
					PLANTABLE.PLAN_BUGS.value(new JdbcNamedParameter("planBugs")),
					PLANTABLE.PLAN_EFFORT.value(new JdbcNamedParameter("planEffort")),
					PLANTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Plan> plans){
			return batchInsert(true ,plans);
	}

	public int[] batchUpdate(List<Plan> plans) {
		if (CollectionUtil.isEmpty(plans)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(plans, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(PLANTABLE).set(
					PLANTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PLANTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					PLANTABLE.PLAN_NAME.value(new JdbcNamedParameter("planName")),
					PLANTABLE.PLAN_SPEC.value(new JdbcNamedParameter("planSpec")),
					PLANTABLE.PLAN_BEGIN_DATE.value(new JdbcNamedParameter("planBeginDate")),
					PLANTABLE.PLAN_END_DATE.value(new JdbcNamedParameter("planEndDate")),
					PLANTABLE.BUILD_ID.value(new JdbcNamedParameter("buildId")),
					PLANTABLE.PLAN_RELEASE_DATE.value(new JdbcNamedParameter("planReleaseDate")),
					PLANTABLE.PLAN_STORIES.value(new JdbcNamedParameter("planStories")),
					PLANTABLE.PLAN_BUGS.value(new JdbcNamedParameter("planBugs")),
					PLANTABLE.PLAN_EFFORT.value(new JdbcNamedParameter("planEffort")),
					PLANTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				PLANTABLE.PLAN_ID.eq(new JdbcNamedParameter("planId")));
			}
		});
	}

	public int[] batchDelete(List<Plan> plans) {
		if (CollectionUtil.isEmpty(plans)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(plans, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(PLANTABLE).where(and(
				PLANTABLE.PLAN_ID.eq(new JdbcNamedParameter("planId")),
				PLANTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				PLANTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				PLANTABLE.PLAN_NAME.eq(new JdbcNamedParameter("planName")),
				PLANTABLE.PLAN_SPEC.eq(new JdbcNamedParameter("planSpec")),
				PLANTABLE.PLAN_BEGIN_DATE.eq(new JdbcNamedParameter("planBeginDate")),
				PLANTABLE.PLAN_END_DATE.eq(new JdbcNamedParameter("planEndDate")),
				PLANTABLE.BUILD_ID.eq(new JdbcNamedParameter("buildId")),
				PLANTABLE.PLAN_RELEASE_DATE.eq(new JdbcNamedParameter("planReleaseDate")),
				PLANTABLE.PLAN_STORIES.eq(new JdbcNamedParameter("planStories")),
				PLANTABLE.PLAN_BUGS.eq(new JdbcNamedParameter("planBugs")),
				PLANTABLE.PLAN_EFFORT.eq(new JdbcNamedParameter("planEffort")),
				PLANTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
