/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.product.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.product.constant.ProductTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.product.pojo.Product;
import org.tinygroup.sdpm.product.inter.ProductDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class ProductDaoImpl extends TinyDslDaoSupport implements ProductDao {

	public Product insertObject(Product product) {
		return getDslTemplate().insertObject(product, new InsertGenerateCallback<Product>() {
			public Insert generate(Product t) {
				Insert insert = insertInto(PRODUCTTABLE).values(
					PRODUCTTABLE.PRODUCT_ID.value(t.getProductId()),
					PRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTTABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTTABLE.PRODUCT_LINE_ID.value(t.getProductLineId()),
					PRODUCTTABLE.PRODUCT_NAME.value(t.getProductName()),
					PRODUCTTABLE.PRODUCT_CODE.value(t.getProductCode()),
					PRODUCTTABLE.PRODUCT_ORDER.value(t.getProductOrder()),
					PRODUCTTABLE.PRODUCT_STATUS.value(t.getProductStatus()),
					PRODUCTTABLE.PRODUCT_DESC.value(t.getProductDesc()),
					PRODUCTTABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTTABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTTABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTTABLE.ACL.value(t.getAcl()),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.value(t.getProductWhiteList()),
					PRODUCTTABLE.PRODUCT_CREATED_BY.value(t.getProductCreatedBy()),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.value(t.getProductCreatedDate()),
					PRODUCTTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Product insertObject(boolean autoGeneratedKeys ,Product product) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,product, new InsertGenerateCallback<Product>() {

			public Insert generate(Product t) {
				Insert insert = insertInto(PRODUCTTABLE).values(
					PRODUCTTABLE.PRODUCT_ID.value(t.getProductId()),
					PRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTTABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTTABLE.PRODUCT_LINE_ID.value(t.getProductLineId()),
					PRODUCTTABLE.PRODUCT_NAME.value(t.getProductName()),
					PRODUCTTABLE.PRODUCT_CODE.value(t.getProductCode()),
					PRODUCTTABLE.PRODUCT_ORDER.value(t.getProductOrder()),
					PRODUCTTABLE.PRODUCT_STATUS.value(t.getProductStatus()),
					PRODUCTTABLE.PRODUCT_DESC.value(t.getProductDesc()),
					PRODUCTTABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTTABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTTABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTTABLE.ACL.value(t.getAcl()),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.value(t.getProductWhiteList()),
					PRODUCTTABLE.PRODUCT_CREATED_BY.value(t.getProductCreatedBy()),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.value(t.getProductCreatedDate()),
					PRODUCTTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Product product) {
		return getDslTemplate().updateObject(product, new UpdateGenerateCallback<Product>() {
			public Update generate(Product t) {
				Update update = update(PRODUCTTABLE).set(
					PRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTTABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTTABLE.PRODUCT_LINE_ID.value(t.getProductLineId()),
					PRODUCTTABLE.PRODUCT_NAME.value(t.getProductName()),
					PRODUCTTABLE.PRODUCT_CODE.value(t.getProductCode()),
					PRODUCTTABLE.PRODUCT_ORDER.value(t.getProductOrder()),
					PRODUCTTABLE.PRODUCT_STATUS.value(t.getProductStatus()),
					PRODUCTTABLE.PRODUCT_DESC.value(t.getProductDesc()),
					PRODUCTTABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTTABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTTABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTTABLE.ACL.value(t.getAcl()),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.value(t.getProductWhiteList()),
					PRODUCTTABLE.PRODUCT_CREATED_BY.value(t.getProductCreatedBy()),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.value(t.getProductCreatedDate()),
					PRODUCTTABLE.DELETED.value(t.getDeleted())).where(
					PRODUCTTABLE.PRODUCT_ID.eq(t.getProductId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(PRODUCTTABLE).where(PRODUCTTABLE.PRODUCT_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(PRODUCTTABLE).where(PRODUCTTABLE.PRODUCT_ID.in(t));
		}
		},pks);
	}

	public Product getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Product.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(PRODUCTTABLE).where(PRODUCTTABLE.PRODUCT_ID.eq(t));
			}
		});
	}

	public List<Product> queryObjects(Product product) {
		if(product==null){
			product=new Product();
		}
		return getDslTemplate().queryObjects(product, new SelectGenerateCallback<Product>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Product t) {
				return selectFrom(PRODUCTTABLE).where(
				and(
					PRODUCTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PRODUCTTABLE.DEPT_ID.eq(t.getDeptId()),
					PRODUCTTABLE.PRODUCT_LINE_ID.eq(t.getProductLineId()),
					PRODUCTTABLE.PRODUCT_NAME.eq(t.getProductName()),
					PRODUCTTABLE.PRODUCT_CODE.eq(t.getProductCode()),
					PRODUCTTABLE.PRODUCT_ORDER.eq(t.getProductOrder()),
					PRODUCTTABLE.PRODUCT_STATUS.eq(t.getProductStatus()),
					PRODUCTTABLE.PRODUCT_DESC.eq(t.getProductDesc()),
					PRODUCTTABLE.PRODUCT_OWNER.eq(t.getProductOwner()),
					PRODUCTTABLE.QUALITY_MANAGER.eq(t.getQualityManager()),
					PRODUCTTABLE.DELIVERY_MANAGER.eq(t.getDeliveryManager()),
					PRODUCTTABLE.ACL.eq(t.getAcl()),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.eq(t.getProductWhiteList()),
					PRODUCTTABLE.PRODUCT_CREATED_BY.eq(t.getProductCreatedBy()),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.eq(t.getProductCreatedDate()),
					PRODUCTTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Product> queryObjectsForPage(int start,int limit ,Product product) {
		if(product==null){
			product=new Product();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, product, false, new SelectGenerateCallback<Product>() {

			public Select generate(Product t) {
				return MysqlSelect.selectFrom(PRODUCTTABLE).where(
				and(
					PRODUCTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PRODUCTTABLE.DEPT_ID.eq(t.getDeptId()),
					PRODUCTTABLE.PRODUCT_LINE_ID.eq(t.getProductLineId()),
					PRODUCTTABLE.PRODUCT_NAME.eq(t.getProductName()),
					PRODUCTTABLE.PRODUCT_CODE.eq(t.getProductCode()),
					PRODUCTTABLE.PRODUCT_ORDER.eq(t.getProductOrder()),
					PRODUCTTABLE.PRODUCT_STATUS.eq(t.getProductStatus()),
					PRODUCTTABLE.PRODUCT_DESC.eq(t.getProductDesc()),
					PRODUCTTABLE.PRODUCT_OWNER.eq(t.getProductOwner()),
					PRODUCTTABLE.QUALITY_MANAGER.eq(t.getQualityManager()),
					PRODUCTTABLE.DELIVERY_MANAGER.eq(t.getDeliveryManager()),
					PRODUCTTABLE.ACL.eq(t.getAcl()),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.eq(t.getProductWhiteList()),
					PRODUCTTABLE.PRODUCT_CREATED_BY.eq(t.getProductCreatedBy()),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.eq(t.getProductCreatedDate()),
					PRODUCTTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Product> products) {
		if (CollectionUtil.isEmpty(products)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, products, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(PRODUCTTABLE).values(
					PRODUCTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PRODUCTTABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					PRODUCTTABLE.PRODUCT_LINE_ID.value(new JdbcNamedParameter("productLineId")),
					PRODUCTTABLE.PRODUCT_NAME.value(new JdbcNamedParameter("productName")),
					PRODUCTTABLE.PRODUCT_CODE.value(new JdbcNamedParameter("productCode")),
					PRODUCTTABLE.PRODUCT_ORDER.value(new JdbcNamedParameter("productOrder")),
					PRODUCTTABLE.PRODUCT_STATUS.value(new JdbcNamedParameter("productStatus")),
					PRODUCTTABLE.PRODUCT_DESC.value(new JdbcNamedParameter("productDesc")),
					PRODUCTTABLE.PRODUCT_OWNER.value(new JdbcNamedParameter("productOwner")),
					PRODUCTTABLE.QUALITY_MANAGER.value(new JdbcNamedParameter("qualityManager")),
					PRODUCTTABLE.DELIVERY_MANAGER.value(new JdbcNamedParameter("deliveryManager")),
					PRODUCTTABLE.ACL.value(new JdbcNamedParameter("acl")),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.value(new JdbcNamedParameter("productWhiteList")),
					PRODUCTTABLE.PRODUCT_CREATED_BY.value(new JdbcNamedParameter("productCreatedBy")),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.value(new JdbcNamedParameter("productCreatedDate")),
					PRODUCTTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Product> products){
			return batchInsert(true ,products);
	}

	public int[] batchUpdate(List<Product> products) {
		if (CollectionUtil.isEmpty(products)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(products, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(PRODUCTTABLE).set(
					PRODUCTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PRODUCTTABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					PRODUCTTABLE.PRODUCT_LINE_ID.value(new JdbcNamedParameter("productLineId")),
					PRODUCTTABLE.PRODUCT_NAME.value(new JdbcNamedParameter("productName")),
					PRODUCTTABLE.PRODUCT_CODE.value(new JdbcNamedParameter("productCode")),
					PRODUCTTABLE.PRODUCT_ORDER.value(new JdbcNamedParameter("productOrder")),
					PRODUCTTABLE.PRODUCT_STATUS.value(new JdbcNamedParameter("productStatus")),
					PRODUCTTABLE.PRODUCT_DESC.value(new JdbcNamedParameter("productDesc")),
					PRODUCTTABLE.PRODUCT_OWNER.value(new JdbcNamedParameter("productOwner")),
					PRODUCTTABLE.QUALITY_MANAGER.value(new JdbcNamedParameter("qualityManager")),
					PRODUCTTABLE.DELIVERY_MANAGER.value(new JdbcNamedParameter("deliveryManager")),
					PRODUCTTABLE.ACL.value(new JdbcNamedParameter("acl")),
					PRODUCTTABLE.PRODUCT_WHITE_LIST.value(new JdbcNamedParameter("productWhiteList")),
					PRODUCTTABLE.PRODUCT_CREATED_BY.value(new JdbcNamedParameter("productCreatedBy")),
					PRODUCTTABLE.PRODUCT_CREATED_DATE.value(new JdbcNamedParameter("productCreatedDate")),
					PRODUCTTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				PRODUCTTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")));
			}
		});
	}

	public int[] batchDelete(List<Product> products) {
		if (CollectionUtil.isEmpty(products)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(products, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(PRODUCTTABLE).where(and(
				PRODUCTTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				PRODUCTTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				PRODUCTTABLE.DEPT_ID.eq(new JdbcNamedParameter("deptId")),
				PRODUCTTABLE.PRODUCT_LINE_ID.eq(new JdbcNamedParameter("productLineId")),
				PRODUCTTABLE.PRODUCT_NAME.eq(new JdbcNamedParameter("productName")),
				PRODUCTTABLE.PRODUCT_CODE.eq(new JdbcNamedParameter("productCode")),
				PRODUCTTABLE.PRODUCT_ORDER.eq(new JdbcNamedParameter("productOrder")),
				PRODUCTTABLE.PRODUCT_STATUS.eq(new JdbcNamedParameter("productStatus")),
				PRODUCTTABLE.PRODUCT_DESC.eq(new JdbcNamedParameter("productDesc")),
				PRODUCTTABLE.PRODUCT_OWNER.eq(new JdbcNamedParameter("productOwner")),
				PRODUCTTABLE.QUALITY_MANAGER.eq(new JdbcNamedParameter("qualityManager")),
				PRODUCTTABLE.DELIVERY_MANAGER.eq(new JdbcNamedParameter("deliveryManager")),
				PRODUCTTABLE.ACL.eq(new JdbcNamedParameter("acl")),
				PRODUCTTABLE.PRODUCT_WHITE_LIST.eq(new JdbcNamedParameter("productWhiteList")),
				PRODUCTTABLE.PRODUCT_CREATED_BY.eq(new JdbcNamedParameter("productCreatedBy")),
				PRODUCTTABLE.PRODUCT_CREATED_DATE.eq(new JdbcNamedParameter("productCreatedDate")),
				PRODUCTTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
