/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.product.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.product.constant.ProductLineTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.product.pojo.ProductLine;
import org.tinygroup.sdpm.product.inter.ProductLineDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class ProductLineDaoImpl extends TinyDslDaoSupport implements ProductLineDao {

	public ProductLine insertObject(ProductLine productLine) {
		return getDslTemplate().insertObject(productLine, new InsertGenerateCallback<ProductLine>() {
			public Insert generate(ProductLine t) {
				Insert insert = insertInto(PRODUCTLINETABLE).values(
					PRODUCTLINETABLE.PRODUCT_LINE_ID.value(t.getProductLineId()),
					PRODUCTLINETABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTLINETABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.value(t.getProductLineRoot()),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.value(t.getProductLineParent()),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.value(t.getProductLineName()),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.value(t.getProductLineCode()),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.value(t.getProductLineOrder()),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.value(t.getProductLineSpec()),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.value(t.getProductLineStatus()),
					PRODUCTLINETABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTLINETABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTLINETABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTLINETABLE.ACL.value(t.getAcl()),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.value(t.getProductLineWhiteList()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.value(t.getProductLineCreatedBy()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.value(t.getProductLineCreatedDate()),
					PRODUCTLINETABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public ProductLine insertObject(boolean autoGeneratedKeys ,ProductLine productLine) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,productLine, new InsertGenerateCallback<ProductLine>() {

			public Insert generate(ProductLine t) {
				Insert insert = insertInto(PRODUCTLINETABLE).values(
					PRODUCTLINETABLE.PRODUCT_LINE_ID.value(t.getProductLineId()),
					PRODUCTLINETABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTLINETABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.value(t.getProductLineRoot()),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.value(t.getProductLineParent()),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.value(t.getProductLineName()),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.value(t.getProductLineCode()),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.value(t.getProductLineOrder()),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.value(t.getProductLineSpec()),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.value(t.getProductLineStatus()),
					PRODUCTLINETABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTLINETABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTLINETABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTLINETABLE.ACL.value(t.getAcl()),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.value(t.getProductLineWhiteList()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.value(t.getProductLineCreatedBy()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.value(t.getProductLineCreatedDate()),
					PRODUCTLINETABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(ProductLine productLine) {
		return getDslTemplate().updateObject(productLine, new UpdateGenerateCallback<ProductLine>() {
			public Update generate(ProductLine t) {
				Update update = update(PRODUCTLINETABLE).set(
					PRODUCTLINETABLE.COMPANY_ID.value(t.getCompanyId()),
					PRODUCTLINETABLE.DEPT_ID.value(t.getDeptId()),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.value(t.getProductLineRoot()),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.value(t.getProductLineParent()),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.value(t.getProductLineName()),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.value(t.getProductLineCode()),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.value(t.getProductLineOrder()),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.value(t.getProductLineSpec()),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.value(t.getProductLineStatus()),
					PRODUCTLINETABLE.PRODUCT_OWNER.value(t.getProductOwner()),
					PRODUCTLINETABLE.QUALITY_MANAGER.value(t.getQualityManager()),
					PRODUCTLINETABLE.DELIVERY_MANAGER.value(t.getDeliveryManager()),
					PRODUCTLINETABLE.ACL.value(t.getAcl()),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.value(t.getProductLineWhiteList()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.value(t.getProductLineCreatedBy()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.value(t.getProductLineCreatedDate()),
					PRODUCTLINETABLE.DELETED.value(t.getDeleted())).where(
					PRODUCTLINETABLE.PRODUCT_LINE_ID.eq(t.getProductLineId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(PRODUCTLINETABLE).where(PRODUCTLINETABLE.PRODUCT_LINE_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(PRODUCTLINETABLE).where(PRODUCTLINETABLE.PRODUCT_LINE_ID.in(t));
		}
		},pks);
	}

	public ProductLine getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, ProductLine.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(PRODUCTLINETABLE).where(PRODUCTLINETABLE.PRODUCT_LINE_ID.eq(t));
			}
		});
	}

	public List<ProductLine> queryObjects(ProductLine productLine) {
		if(productLine==null){
			productLine=new ProductLine();
		}
		return getDslTemplate().queryObjects(productLine, new SelectGenerateCallback<ProductLine>() {

			@SuppressWarnings("rawtypes")
			public Select generate(ProductLine t) {
				return selectFrom(PRODUCTLINETABLE).where(
				and(
					PRODUCTLINETABLE.COMPANY_ID.eq(t.getCompanyId()),
					PRODUCTLINETABLE.DEPT_ID.eq(t.getDeptId()),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.eq(t.getProductLineRoot()),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.eq(t.getProductLineParent()),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.eq(t.getProductLineName()),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.eq(t.getProductLineCode()),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.eq(t.getProductLineOrder()),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.eq(t.getProductLineSpec()),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.eq(t.getProductLineStatus()),
					PRODUCTLINETABLE.PRODUCT_OWNER.eq(t.getProductOwner()),
					PRODUCTLINETABLE.QUALITY_MANAGER.eq(t.getQualityManager()),
					PRODUCTLINETABLE.DELIVERY_MANAGER.eq(t.getDeliveryManager()),
					PRODUCTLINETABLE.ACL.eq(t.getAcl()),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.eq(t.getProductLineWhiteList()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.eq(t.getProductLineCreatedBy()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.eq(t.getProductLineCreatedDate()),
					PRODUCTLINETABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<ProductLine> queryObjectsForPage(int start,int limit ,ProductLine productLine) {
		if(productLine==null){
			productLine=new ProductLine();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, productLine, false, new SelectGenerateCallback<ProductLine>() {

			public Select generate(ProductLine t) {
				return MysqlSelect.selectFrom(PRODUCTLINETABLE).where(
				and(
					PRODUCTLINETABLE.COMPANY_ID.eq(t.getCompanyId()),
					PRODUCTLINETABLE.DEPT_ID.eq(t.getDeptId()),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.eq(t.getProductLineRoot()),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.eq(t.getProductLineParent()),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.eq(t.getProductLineName()),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.eq(t.getProductLineCode()),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.eq(t.getProductLineOrder()),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.eq(t.getProductLineSpec()),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.eq(t.getProductLineStatus()),
					PRODUCTLINETABLE.PRODUCT_OWNER.eq(t.getProductOwner()),
					PRODUCTLINETABLE.QUALITY_MANAGER.eq(t.getQualityManager()),
					PRODUCTLINETABLE.DELIVERY_MANAGER.eq(t.getDeliveryManager()),
					PRODUCTLINETABLE.ACL.eq(t.getAcl()),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.eq(t.getProductLineWhiteList()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.eq(t.getProductLineCreatedBy()),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.eq(t.getProductLineCreatedDate()),
					PRODUCTLINETABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<ProductLine> productLines) {
		if (CollectionUtil.isEmpty(productLines)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, productLines, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(PRODUCTLINETABLE).values(
					PRODUCTLINETABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PRODUCTLINETABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.value(new JdbcNamedParameter("productLineRoot")),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.value(new JdbcNamedParameter("productLineParent")),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.value(new JdbcNamedParameter("productLineName")),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.value(new JdbcNamedParameter("productLineCode")),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.value(new JdbcNamedParameter("productLineOrder")),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.value(new JdbcNamedParameter("productLineSpec")),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.value(new JdbcNamedParameter("productLineStatus")),
					PRODUCTLINETABLE.PRODUCT_OWNER.value(new JdbcNamedParameter("productOwner")),
					PRODUCTLINETABLE.QUALITY_MANAGER.value(new JdbcNamedParameter("qualityManager")),
					PRODUCTLINETABLE.DELIVERY_MANAGER.value(new JdbcNamedParameter("deliveryManager")),
					PRODUCTLINETABLE.ACL.value(new JdbcNamedParameter("acl")),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.value(new JdbcNamedParameter("productLineWhiteList")),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.value(new JdbcNamedParameter("productLineCreatedBy")),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.value(new JdbcNamedParameter("productLineCreatedDate")),
					PRODUCTLINETABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<ProductLine> productLines){
			return batchInsert(true ,productLines);
	}

	public int[] batchUpdate(List<ProductLine> productLines) {
		if (CollectionUtil.isEmpty(productLines)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(productLines, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(PRODUCTLINETABLE).set(
					PRODUCTLINETABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PRODUCTLINETABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					PRODUCTLINETABLE.PRODUCT_LINE_ROOT.value(new JdbcNamedParameter("productLineRoot")),
					PRODUCTLINETABLE.PRODUCT_LINE_PARENT.value(new JdbcNamedParameter("productLineParent")),
					PRODUCTLINETABLE.PRODUCT_LINE_NAME.value(new JdbcNamedParameter("productLineName")),
					PRODUCTLINETABLE.PRODUCT_LINE_CODE.value(new JdbcNamedParameter("productLineCode")),
					PRODUCTLINETABLE.PRODUCT_LINE_ORDER.value(new JdbcNamedParameter("productLineOrder")),
					PRODUCTLINETABLE.PRODUCT_LINE_SPEC.value(new JdbcNamedParameter("productLineSpec")),
					PRODUCTLINETABLE.PRODUCT_LINE_STATUS.value(new JdbcNamedParameter("productLineStatus")),
					PRODUCTLINETABLE.PRODUCT_OWNER.value(new JdbcNamedParameter("productOwner")),
					PRODUCTLINETABLE.QUALITY_MANAGER.value(new JdbcNamedParameter("qualityManager")),
					PRODUCTLINETABLE.DELIVERY_MANAGER.value(new JdbcNamedParameter("deliveryManager")),
					PRODUCTLINETABLE.ACL.value(new JdbcNamedParameter("acl")),
					PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.value(new JdbcNamedParameter("productLineWhiteList")),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.value(new JdbcNamedParameter("productLineCreatedBy")),
					PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.value(new JdbcNamedParameter("productLineCreatedDate")),
					PRODUCTLINETABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				PRODUCTLINETABLE.PRODUCT_LINE_ID.eq(new JdbcNamedParameter("productLineId")));
			}
		});
	}

	public int[] batchDelete(List<ProductLine> productLines) {
		if (CollectionUtil.isEmpty(productLines)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(productLines, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(PRODUCTLINETABLE).where(and(
				PRODUCTLINETABLE.PRODUCT_LINE_ID.eq(new JdbcNamedParameter("productLineId")),
				PRODUCTLINETABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				PRODUCTLINETABLE.DEPT_ID.eq(new JdbcNamedParameter("deptId")),
				PRODUCTLINETABLE.PRODUCT_LINE_ROOT.eq(new JdbcNamedParameter("productLineRoot")),
				PRODUCTLINETABLE.PRODUCT_LINE_PARENT.eq(new JdbcNamedParameter("productLineParent")),
				PRODUCTLINETABLE.PRODUCT_LINE_NAME.eq(new JdbcNamedParameter("productLineName")),
				PRODUCTLINETABLE.PRODUCT_LINE_CODE.eq(new JdbcNamedParameter("productLineCode")),
				PRODUCTLINETABLE.PRODUCT_LINE_ORDER.eq(new JdbcNamedParameter("productLineOrder")),
				PRODUCTLINETABLE.PRODUCT_LINE_SPEC.eq(new JdbcNamedParameter("productLineSpec")),
				PRODUCTLINETABLE.PRODUCT_LINE_STATUS.eq(new JdbcNamedParameter("productLineStatus")),
				PRODUCTLINETABLE.PRODUCT_OWNER.eq(new JdbcNamedParameter("productOwner")),
				PRODUCTLINETABLE.QUALITY_MANAGER.eq(new JdbcNamedParameter("qualityManager")),
				PRODUCTLINETABLE.DELIVERY_MANAGER.eq(new JdbcNamedParameter("deliveryManager")),
				PRODUCTLINETABLE.ACL.eq(new JdbcNamedParameter("acl")),
				PRODUCTLINETABLE.PRODUCT_LINE_WHITE_LIST.eq(new JdbcNamedParameter("productLineWhiteList")),
				PRODUCTLINETABLE.PRODUCT_LINE_CREATED_BY.eq(new JdbcNamedParameter("productLineCreatedBy")),
				PRODUCTLINETABLE.PRODUCT_LINE_CREATED_DATE.eq(new JdbcNamedParameter("productLineCreatedDate")),
				PRODUCTLINETABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
