/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.product.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.product.constant.StoryTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.product.pojo.Story;
import org.tinygroup.sdpm.product.inter.StoryDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class StoryDaoImpl extends TinyDslDaoSupport implements StoryDao {

	public Story insertObject(Story story) {
		return getDslTemplate().insertObject(story, new InsertGenerateCallback<Story>() {
			public Insert generate(Story t) {
				Insert insert = insertInto(STORYTABLE).values(
					STORYTABLE.STORY_ID.value(t.getStoryId()),
					STORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					STORYTABLE.PRODUCT_ID.value(t.getProductId()),
					STORYTABLE.MODULE_ID.value(t.getModuleId()),
					STORYTABLE.PLAN_ID.value(t.getPlanId()),
					STORYTABLE.RELEASE_ID.value(t.getReleaseId()),
					STORYTABLE.STORY_PARENT_ID.value(t.getStoryParentId()),
					STORYTABLE.STORY_SOURCE.value(t.getStorySource()),
					STORYTABLE.STORY_TITLE.value(t.getStoryTitle()),
					STORYTABLE.STORY_KEYWORDS.value(t.getStoryKeywords()),
					STORYTABLE.STORY_TYPE.value(t.getStoryType()),
					STORYTABLE.STORY_PRI.value(t.getStoryPri()),
					STORYTABLE.STORY_ESTIMATE.value(t.getStoryEstimate()),
					STORYTABLE.STORY_STATUS.value(t.getStoryStatus()),
					STORYTABLE.STORY_MAILTO.value(t.getStoryMailto()),
					STORYTABLE.STORY_OPENED_BY.value(t.getStoryOpenedBy()),
					STORYTABLE.STORY_OPENED_DATE.value(t.getStoryOpenedDate()),
					STORYTABLE.STORY_ASSIGNED_TO.value(t.getStoryAssignedTo()),
					STORYTABLE.STORY_ASSIGNED_DATE.value(t.getStoryAssignedDate()),
					STORYTABLE.STORY_LAST_EDITED_BY.value(t.getStoryLastEditedBy()),
					STORYTABLE.STORY_LAST_EDITED_DATE.value(t.getStoryLastEditedDate()),
					STORYTABLE.STORY_REVIEWED_BY.value(t.getStoryReviewedBy()),
					STORYTABLE.STORY_REVIEWED_DATE.value(t.getStoryReviewedDate()),
					STORYTABLE.STORY_CLOSED_BY.value(t.getStoryClosedBy()),
					STORYTABLE.STORY_CLOSED_DATE.value(t.getStoryClosedDate()),
					STORYTABLE.STORY_CLOSED_REASON.value(t.getStoryClosedReason()),
					STORYTABLE.STORY_TO_BUG.value(t.getStoryToBug()),
					STORYTABLE.STORY_LINK_STORIES.value(t.getStoryLinkStories()),
					STORYTABLE.STORY_DUPLICATE_STORY.value(t.getStoryDuplicateStory()),
					STORYTABLE.STORY_VERSION.value(t.getStoryVersion()),
					STORYTABLE.BUG_ID.value(t.getBugId()),
					STORYTABLE.REQUEST_ID.value(t.getRequestId()),
					STORYTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Story insertObject(boolean autoGeneratedKeys ,Story story) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,story, new InsertGenerateCallback<Story>() {

			public Insert generate(Story t) {
				Insert insert = insertInto(STORYTABLE).values(
					STORYTABLE.STORY_ID.value(t.getStoryId()),
					STORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					STORYTABLE.PRODUCT_ID.value(t.getProductId()),
					STORYTABLE.MODULE_ID.value(t.getModuleId()),
					STORYTABLE.PLAN_ID.value(t.getPlanId()),
					STORYTABLE.RELEASE_ID.value(t.getReleaseId()),
					STORYTABLE.STORY_PARENT_ID.value(t.getStoryParentId()),
					STORYTABLE.STORY_SOURCE.value(t.getStorySource()),
					STORYTABLE.STORY_TITLE.value(t.getStoryTitle()),
					STORYTABLE.STORY_KEYWORDS.value(t.getStoryKeywords()),
					STORYTABLE.STORY_TYPE.value(t.getStoryType()),
					STORYTABLE.STORY_PRI.value(t.getStoryPri()),
					STORYTABLE.STORY_ESTIMATE.value(t.getStoryEstimate()),
					STORYTABLE.STORY_STATUS.value(t.getStoryStatus()),
					STORYTABLE.STORY_MAILTO.value(t.getStoryMailto()),
					STORYTABLE.STORY_OPENED_BY.value(t.getStoryOpenedBy()),
					STORYTABLE.STORY_OPENED_DATE.value(t.getStoryOpenedDate()),
					STORYTABLE.STORY_ASSIGNED_TO.value(t.getStoryAssignedTo()),
					STORYTABLE.STORY_ASSIGNED_DATE.value(t.getStoryAssignedDate()),
					STORYTABLE.STORY_LAST_EDITED_BY.value(t.getStoryLastEditedBy()),
					STORYTABLE.STORY_LAST_EDITED_DATE.value(t.getStoryLastEditedDate()),
					STORYTABLE.STORY_REVIEWED_BY.value(t.getStoryReviewedBy()),
					STORYTABLE.STORY_REVIEWED_DATE.value(t.getStoryReviewedDate()),
					STORYTABLE.STORY_CLOSED_BY.value(t.getStoryClosedBy()),
					STORYTABLE.STORY_CLOSED_DATE.value(t.getStoryClosedDate()),
					STORYTABLE.STORY_CLOSED_REASON.value(t.getStoryClosedReason()),
					STORYTABLE.STORY_TO_BUG.value(t.getStoryToBug()),
					STORYTABLE.STORY_LINK_STORIES.value(t.getStoryLinkStories()),
					STORYTABLE.STORY_DUPLICATE_STORY.value(t.getStoryDuplicateStory()),
					STORYTABLE.STORY_VERSION.value(t.getStoryVersion()),
					STORYTABLE.BUG_ID.value(t.getBugId()),
					STORYTABLE.REQUEST_ID.value(t.getRequestId()),
					STORYTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Story story) {
		return getDslTemplate().updateObject(story, new UpdateGenerateCallback<Story>() {
			public Update generate(Story t) {
				Update update = update(STORYTABLE).set(
					STORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					STORYTABLE.PRODUCT_ID.value(t.getProductId()),
					STORYTABLE.MODULE_ID.value(t.getModuleId()),
					STORYTABLE.PLAN_ID.value(t.getPlanId()),
					STORYTABLE.RELEASE_ID.value(t.getReleaseId()),
					STORYTABLE.STORY_PARENT_ID.value(t.getStoryParentId()),
					STORYTABLE.STORY_SOURCE.value(t.getStorySource()),
					STORYTABLE.STORY_TITLE.value(t.getStoryTitle()),
					STORYTABLE.STORY_KEYWORDS.value(t.getStoryKeywords()),
					STORYTABLE.STORY_TYPE.value(t.getStoryType()),
					STORYTABLE.STORY_PRI.value(t.getStoryPri()),
					STORYTABLE.STORY_ESTIMATE.value(t.getStoryEstimate()),
					STORYTABLE.STORY_STATUS.value(t.getStoryStatus()),
					STORYTABLE.STORY_MAILTO.value(t.getStoryMailto()),
					STORYTABLE.STORY_OPENED_BY.value(t.getStoryOpenedBy()),
					STORYTABLE.STORY_OPENED_DATE.value(t.getStoryOpenedDate()),
					STORYTABLE.STORY_ASSIGNED_TO.value(t.getStoryAssignedTo()),
					STORYTABLE.STORY_ASSIGNED_DATE.value(t.getStoryAssignedDate()),
					STORYTABLE.STORY_LAST_EDITED_BY.value(t.getStoryLastEditedBy()),
					STORYTABLE.STORY_LAST_EDITED_DATE.value(t.getStoryLastEditedDate()),
					STORYTABLE.STORY_REVIEWED_BY.value(t.getStoryReviewedBy()),
					STORYTABLE.STORY_REVIEWED_DATE.value(t.getStoryReviewedDate()),
					STORYTABLE.STORY_CLOSED_BY.value(t.getStoryClosedBy()),
					STORYTABLE.STORY_CLOSED_DATE.value(t.getStoryClosedDate()),
					STORYTABLE.STORY_CLOSED_REASON.value(t.getStoryClosedReason()),
					STORYTABLE.STORY_TO_BUG.value(t.getStoryToBug()),
					STORYTABLE.STORY_LINK_STORIES.value(t.getStoryLinkStories()),
					STORYTABLE.STORY_DUPLICATE_STORY.value(t.getStoryDuplicateStory()),
					STORYTABLE.STORY_VERSION.value(t.getStoryVersion()),
					STORYTABLE.BUG_ID.value(t.getBugId()),
					STORYTABLE.REQUEST_ID.value(t.getRequestId()),
					STORYTABLE.DELETED.value(t.getDeleted())).where(
					STORYTABLE.STORY_ID.eq(t.getStoryId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(STORYTABLE).where(STORYTABLE.STORY_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(STORYTABLE).where(STORYTABLE.STORY_ID.in(t));
		}
		},pks);
	}

	public Story getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Story.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(STORYTABLE).where(STORYTABLE.STORY_ID.eq(t));
			}
		});
	}

	public List<Story> queryObjects(Story story) {
		if(story==null){
			story=new Story();
		}
		return getDslTemplate().queryObjects(story, new SelectGenerateCallback<Story>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Story t) {
				return selectFrom(STORYTABLE).where(
				and(
					STORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					STORYTABLE.PRODUCT_ID.eq(t.getProductId()),
					STORYTABLE.MODULE_ID.eq(t.getModuleId()),
					STORYTABLE.PLAN_ID.eq(t.getPlanId()),
					STORYTABLE.RELEASE_ID.eq(t.getReleaseId()),
					STORYTABLE.STORY_PARENT_ID.eq(t.getStoryParentId()),
					STORYTABLE.STORY_SOURCE.eq(t.getStorySource()),
					STORYTABLE.STORY_TITLE.eq(t.getStoryTitle()),
					STORYTABLE.STORY_KEYWORDS.eq(t.getStoryKeywords()),
					STORYTABLE.STORY_TYPE.eq(t.getStoryType()),
					STORYTABLE.STORY_PRI.eq(t.getStoryPri()),
					STORYTABLE.STORY_ESTIMATE.eq(t.getStoryEstimate()),
					STORYTABLE.STORY_STATUS.eq(t.getStoryStatus()),
					STORYTABLE.STORY_MAILTO.eq(t.getStoryMailto()),
					STORYTABLE.STORY_OPENED_BY.eq(t.getStoryOpenedBy()),
					STORYTABLE.STORY_OPENED_DATE.eq(t.getStoryOpenedDate()),
					STORYTABLE.STORY_ASSIGNED_TO.eq(t.getStoryAssignedTo()),
					STORYTABLE.STORY_ASSIGNED_DATE.eq(t.getStoryAssignedDate()),
					STORYTABLE.STORY_LAST_EDITED_BY.eq(t.getStoryLastEditedBy()),
					STORYTABLE.STORY_LAST_EDITED_DATE.eq(t.getStoryLastEditedDate()),
					STORYTABLE.STORY_REVIEWED_BY.eq(t.getStoryReviewedBy()),
					STORYTABLE.STORY_REVIEWED_DATE.eq(t.getStoryReviewedDate()),
					STORYTABLE.STORY_CLOSED_BY.eq(t.getStoryClosedBy()),
					STORYTABLE.STORY_CLOSED_DATE.eq(t.getStoryClosedDate()),
					STORYTABLE.STORY_CLOSED_REASON.eq(t.getStoryClosedReason()),
					STORYTABLE.STORY_TO_BUG.eq(t.getStoryToBug()),
					STORYTABLE.STORY_LINK_STORIES.eq(t.getStoryLinkStories()),
					STORYTABLE.STORY_DUPLICATE_STORY.eq(t.getStoryDuplicateStory()),
					STORYTABLE.STORY_VERSION.eq(t.getStoryVersion()),
					STORYTABLE.BUG_ID.eq(t.getBugId()),
					STORYTABLE.REQUEST_ID.eq(t.getRequestId()),
					STORYTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Story> queryObjectsForPage(int start,int limit ,Story story) {
		if(story==null){
			story=new Story();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, story, false, new SelectGenerateCallback<Story>() {

			public Select generate(Story t) {
				return MysqlSelect.selectFrom(STORYTABLE).where(
				and(
					STORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					STORYTABLE.PRODUCT_ID.eq(t.getProductId()),
					STORYTABLE.MODULE_ID.eq(t.getModuleId()),
					STORYTABLE.PLAN_ID.eq(t.getPlanId()),
					STORYTABLE.RELEASE_ID.eq(t.getReleaseId()),
					STORYTABLE.STORY_PARENT_ID.eq(t.getStoryParentId()),
					STORYTABLE.STORY_SOURCE.eq(t.getStorySource()),
					STORYTABLE.STORY_TITLE.eq(t.getStoryTitle()),
					STORYTABLE.STORY_KEYWORDS.eq(t.getStoryKeywords()),
					STORYTABLE.STORY_TYPE.eq(t.getStoryType()),
					STORYTABLE.STORY_PRI.eq(t.getStoryPri()),
					STORYTABLE.STORY_ESTIMATE.eq(t.getStoryEstimate()),
					STORYTABLE.STORY_STATUS.eq(t.getStoryStatus()),
					STORYTABLE.STORY_MAILTO.eq(t.getStoryMailto()),
					STORYTABLE.STORY_OPENED_BY.eq(t.getStoryOpenedBy()),
					STORYTABLE.STORY_OPENED_DATE.eq(t.getStoryOpenedDate()),
					STORYTABLE.STORY_ASSIGNED_TO.eq(t.getStoryAssignedTo()),
					STORYTABLE.STORY_ASSIGNED_DATE.eq(t.getStoryAssignedDate()),
					STORYTABLE.STORY_LAST_EDITED_BY.eq(t.getStoryLastEditedBy()),
					STORYTABLE.STORY_LAST_EDITED_DATE.eq(t.getStoryLastEditedDate()),
					STORYTABLE.STORY_REVIEWED_BY.eq(t.getStoryReviewedBy()),
					STORYTABLE.STORY_REVIEWED_DATE.eq(t.getStoryReviewedDate()),
					STORYTABLE.STORY_CLOSED_BY.eq(t.getStoryClosedBy()),
					STORYTABLE.STORY_CLOSED_DATE.eq(t.getStoryClosedDate()),
					STORYTABLE.STORY_CLOSED_REASON.eq(t.getStoryClosedReason()),
					STORYTABLE.STORY_TO_BUG.eq(t.getStoryToBug()),
					STORYTABLE.STORY_LINK_STORIES.eq(t.getStoryLinkStories()),
					STORYTABLE.STORY_DUPLICATE_STORY.eq(t.getStoryDuplicateStory()),
					STORYTABLE.STORY_VERSION.eq(t.getStoryVersion()),
					STORYTABLE.BUG_ID.eq(t.getBugId()),
					STORYTABLE.REQUEST_ID.eq(t.getRequestId()),
					STORYTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Story> storys) {
		if (CollectionUtil.isEmpty(storys)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, storys, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(STORYTABLE).values(
					STORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					STORYTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					STORYTABLE.MODULE_ID.value(new JdbcNamedParameter("moduleId")),
					STORYTABLE.PLAN_ID.value(new JdbcNamedParameter("planId")),
					STORYTABLE.RELEASE_ID.value(new JdbcNamedParameter("releaseId")),
					STORYTABLE.STORY_PARENT_ID.value(new JdbcNamedParameter("storyParentId")),
					STORYTABLE.STORY_SOURCE.value(new JdbcNamedParameter("storySource")),
					STORYTABLE.STORY_TITLE.value(new JdbcNamedParameter("storyTitle")),
					STORYTABLE.STORY_KEYWORDS.value(new JdbcNamedParameter("storyKeywords")),
					STORYTABLE.STORY_TYPE.value(new JdbcNamedParameter("storyType")),
					STORYTABLE.STORY_PRI.value(new JdbcNamedParameter("storyPri")),
					STORYTABLE.STORY_ESTIMATE.value(new JdbcNamedParameter("storyEstimate")),
					STORYTABLE.STORY_STATUS.value(new JdbcNamedParameter("storyStatus")),
					STORYTABLE.STORY_MAILTO.value(new JdbcNamedParameter("storyMailto")),
					STORYTABLE.STORY_OPENED_BY.value(new JdbcNamedParameter("storyOpenedBy")),
					STORYTABLE.STORY_OPENED_DATE.value(new JdbcNamedParameter("storyOpenedDate")),
					STORYTABLE.STORY_ASSIGNED_TO.value(new JdbcNamedParameter("storyAssignedTo")),
					STORYTABLE.STORY_ASSIGNED_DATE.value(new JdbcNamedParameter("storyAssignedDate")),
					STORYTABLE.STORY_LAST_EDITED_BY.value(new JdbcNamedParameter("storyLastEditedBy")),
					STORYTABLE.STORY_LAST_EDITED_DATE.value(new JdbcNamedParameter("storyLastEditedDate")),
					STORYTABLE.STORY_REVIEWED_BY.value(new JdbcNamedParameter("storyReviewedBy")),
					STORYTABLE.STORY_REVIEWED_DATE.value(new JdbcNamedParameter("storyReviewedDate")),
					STORYTABLE.STORY_CLOSED_BY.value(new JdbcNamedParameter("storyClosedBy")),
					STORYTABLE.STORY_CLOSED_DATE.value(new JdbcNamedParameter("storyClosedDate")),
					STORYTABLE.STORY_CLOSED_REASON.value(new JdbcNamedParameter("storyClosedReason")),
					STORYTABLE.STORY_TO_BUG.value(new JdbcNamedParameter("storyToBug")),
					STORYTABLE.STORY_LINK_STORIES.value(new JdbcNamedParameter("storyLinkStories")),
					STORYTABLE.STORY_DUPLICATE_STORY.value(new JdbcNamedParameter("storyDuplicateStory")),
					STORYTABLE.STORY_VERSION.value(new JdbcNamedParameter("storyVersion")),
					STORYTABLE.BUG_ID.value(new JdbcNamedParameter("bugId")),
					STORYTABLE.REQUEST_ID.value(new JdbcNamedParameter("requestId")),
					STORYTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Story> storys){
			return batchInsert(true ,storys);
	}

	public int[] batchUpdate(List<Story> storys) {
		if (CollectionUtil.isEmpty(storys)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(storys, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(STORYTABLE).set(
					STORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					STORYTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					STORYTABLE.MODULE_ID.value(new JdbcNamedParameter("moduleId")),
					STORYTABLE.PLAN_ID.value(new JdbcNamedParameter("planId")),
					STORYTABLE.RELEASE_ID.value(new JdbcNamedParameter("releaseId")),
					STORYTABLE.STORY_PARENT_ID.value(new JdbcNamedParameter("storyParentId")),
					STORYTABLE.STORY_SOURCE.value(new JdbcNamedParameter("storySource")),
					STORYTABLE.STORY_TITLE.value(new JdbcNamedParameter("storyTitle")),
					STORYTABLE.STORY_KEYWORDS.value(new JdbcNamedParameter("storyKeywords")),
					STORYTABLE.STORY_TYPE.value(new JdbcNamedParameter("storyType")),
					STORYTABLE.STORY_PRI.value(new JdbcNamedParameter("storyPri")),
					STORYTABLE.STORY_ESTIMATE.value(new JdbcNamedParameter("storyEstimate")),
					STORYTABLE.STORY_STATUS.value(new JdbcNamedParameter("storyStatus")),
					STORYTABLE.STORY_MAILTO.value(new JdbcNamedParameter("storyMailto")),
					STORYTABLE.STORY_OPENED_BY.value(new JdbcNamedParameter("storyOpenedBy")),
					STORYTABLE.STORY_OPENED_DATE.value(new JdbcNamedParameter("storyOpenedDate")),
					STORYTABLE.STORY_ASSIGNED_TO.value(new JdbcNamedParameter("storyAssignedTo")),
					STORYTABLE.STORY_ASSIGNED_DATE.value(new JdbcNamedParameter("storyAssignedDate")),
					STORYTABLE.STORY_LAST_EDITED_BY.value(new JdbcNamedParameter("storyLastEditedBy")),
					STORYTABLE.STORY_LAST_EDITED_DATE.value(new JdbcNamedParameter("storyLastEditedDate")),
					STORYTABLE.STORY_REVIEWED_BY.value(new JdbcNamedParameter("storyReviewedBy")),
					STORYTABLE.STORY_REVIEWED_DATE.value(new JdbcNamedParameter("storyReviewedDate")),
					STORYTABLE.STORY_CLOSED_BY.value(new JdbcNamedParameter("storyClosedBy")),
					STORYTABLE.STORY_CLOSED_DATE.value(new JdbcNamedParameter("storyClosedDate")),
					STORYTABLE.STORY_CLOSED_REASON.value(new JdbcNamedParameter("storyClosedReason")),
					STORYTABLE.STORY_TO_BUG.value(new JdbcNamedParameter("storyToBug")),
					STORYTABLE.STORY_LINK_STORIES.value(new JdbcNamedParameter("storyLinkStories")),
					STORYTABLE.STORY_DUPLICATE_STORY.value(new JdbcNamedParameter("storyDuplicateStory")),
					STORYTABLE.STORY_VERSION.value(new JdbcNamedParameter("storyVersion")),
					STORYTABLE.BUG_ID.value(new JdbcNamedParameter("bugId")),
					STORYTABLE.REQUEST_ID.value(new JdbcNamedParameter("requestId")),
					STORYTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				STORYTABLE.STORY_ID.eq(new JdbcNamedParameter("storyId")));
			}
		});
	}

	public int[] batchDelete(List<Story> storys) {
		if (CollectionUtil.isEmpty(storys)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(storys, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(STORYTABLE).where(and(
				STORYTABLE.STORY_ID.eq(new JdbcNamedParameter("storyId")),
				STORYTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				STORYTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				STORYTABLE.MODULE_ID.eq(new JdbcNamedParameter("moduleId")),
				STORYTABLE.PLAN_ID.eq(new JdbcNamedParameter("planId")),
				STORYTABLE.RELEASE_ID.eq(new JdbcNamedParameter("releaseId")),
				STORYTABLE.STORY_PARENT_ID.eq(new JdbcNamedParameter("storyParentId")),
				STORYTABLE.STORY_SOURCE.eq(new JdbcNamedParameter("storySource")),
				STORYTABLE.STORY_TITLE.eq(new JdbcNamedParameter("storyTitle")),
				STORYTABLE.STORY_KEYWORDS.eq(new JdbcNamedParameter("storyKeywords")),
				STORYTABLE.STORY_TYPE.eq(new JdbcNamedParameter("storyType")),
				STORYTABLE.STORY_PRI.eq(new JdbcNamedParameter("storyPri")),
				STORYTABLE.STORY_ESTIMATE.eq(new JdbcNamedParameter("storyEstimate")),
				STORYTABLE.STORY_STATUS.eq(new JdbcNamedParameter("storyStatus")),
				STORYTABLE.STORY_MAILTO.eq(new JdbcNamedParameter("storyMailto")),
				STORYTABLE.STORY_OPENED_BY.eq(new JdbcNamedParameter("storyOpenedBy")),
				STORYTABLE.STORY_OPENED_DATE.eq(new JdbcNamedParameter("storyOpenedDate")),
				STORYTABLE.STORY_ASSIGNED_TO.eq(new JdbcNamedParameter("storyAssignedTo")),
				STORYTABLE.STORY_ASSIGNED_DATE.eq(new JdbcNamedParameter("storyAssignedDate")),
				STORYTABLE.STORY_LAST_EDITED_BY.eq(new JdbcNamedParameter("storyLastEditedBy")),
				STORYTABLE.STORY_LAST_EDITED_DATE.eq(new JdbcNamedParameter("storyLastEditedDate")),
				STORYTABLE.STORY_REVIEWED_BY.eq(new JdbcNamedParameter("storyReviewedBy")),
				STORYTABLE.STORY_REVIEWED_DATE.eq(new JdbcNamedParameter("storyReviewedDate")),
				STORYTABLE.STORY_CLOSED_BY.eq(new JdbcNamedParameter("storyClosedBy")),
				STORYTABLE.STORY_CLOSED_DATE.eq(new JdbcNamedParameter("storyClosedDate")),
				STORYTABLE.STORY_CLOSED_REASON.eq(new JdbcNamedParameter("storyClosedReason")),
				STORYTABLE.STORY_TO_BUG.eq(new JdbcNamedParameter("storyToBug")),
				STORYTABLE.STORY_LINK_STORIES.eq(new JdbcNamedParameter("storyLinkStories")),
				STORYTABLE.STORY_DUPLICATE_STORY.eq(new JdbcNamedParameter("storyDuplicateStory")),
				STORYTABLE.STORY_VERSION.eq(new JdbcNamedParameter("storyVersion")),
				STORYTABLE.BUG_ID.eq(new JdbcNamedParameter("bugId")),
				STORYTABLE.REQUEST_ID.eq(new JdbcNamedParameter("requestId")),
				STORYTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
