/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.HistoryTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.History;
import org.tinygroup.sdpm.common.inter.HistoryDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class HistoryDaoImpl extends TinyDslDaoSupport implements HistoryDao {

	public History insertObject(History history) {
		return getDslTemplate().insertObject(history, new InsertGenerateCallback<History>() {
			public Insert generate(History t) {
				Insert insert = insertInto(HISTORYTABLE).values(
					HISTORYTABLE.HISTORY_ID.value(t.getHistoryId()),
					HISTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					HISTORYTABLE.ACTION_ID.value(t.getActionId()),
					HISTORYTABLE.HISTORY_FIELD.value(t.getHistoryField()),
					HISTORYTABLE.HISTORY_OLD.value(t.getHistoryOld()),
					HISTORYTABLE.HISTORY_NEW.value(t.getHistoryNew()),
					HISTORYTABLE.HISTORY_DIFF.value(t.getHistoryDiff()));
				return insert;
			}
		});
	}

	public History insertObject(boolean autoGeneratedKeys ,History history) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,history, new InsertGenerateCallback<History>() {

			public Insert generate(History t) {
				Insert insert = insertInto(HISTORYTABLE).values(
					HISTORYTABLE.HISTORY_ID.value(t.getHistoryId()),
					HISTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					HISTORYTABLE.ACTION_ID.value(t.getActionId()),
					HISTORYTABLE.HISTORY_FIELD.value(t.getHistoryField()),
					HISTORYTABLE.HISTORY_OLD.value(t.getHistoryOld()),
					HISTORYTABLE.HISTORY_NEW.value(t.getHistoryNew()),
					HISTORYTABLE.HISTORY_DIFF.value(t.getHistoryDiff()));
				return insert;
			}
		});
	}

	public int updateObject(History history) {
		return getDslTemplate().updateObject(history, new UpdateGenerateCallback<History>() {
			public Update generate(History t) {
				Update update = update(HISTORYTABLE).set(
					HISTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					HISTORYTABLE.ACTION_ID.value(t.getActionId()),
					HISTORYTABLE.HISTORY_FIELD.value(t.getHistoryField()),
					HISTORYTABLE.HISTORY_OLD.value(t.getHistoryOld()),
					HISTORYTABLE.HISTORY_NEW.value(t.getHistoryNew()),
					HISTORYTABLE.HISTORY_DIFF.value(t.getHistoryDiff())).where(
					HISTORYTABLE.HISTORY_ID.eq(t.getHistoryId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(HISTORYTABLE).where(HISTORYTABLE.HISTORY_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(HISTORYTABLE).where(HISTORYTABLE.HISTORY_ID.in(t));
		}
		},pks);
	}

	public History getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, History.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(HISTORYTABLE).where(HISTORYTABLE.HISTORY_ID.eq(t));
			}
		});
	}

	public List<History> queryObjects(History history) {
		if(history==null){
			history=new History();
		}
		return getDslTemplate().queryObjects(history, new SelectGenerateCallback<History>() {

			@SuppressWarnings("rawtypes")
			public Select generate(History t) {
				return selectFrom(HISTORYTABLE).where(
				and(
					HISTORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					HISTORYTABLE.ACTION_ID.eq(t.getActionId()),
					HISTORYTABLE.HISTORY_FIELD.eq(t.getHistoryField()),
					HISTORYTABLE.HISTORY_OLD.eq(t.getHistoryOld()),
					HISTORYTABLE.HISTORY_NEW.eq(t.getHistoryNew()),
					HISTORYTABLE.HISTORY_DIFF.eq(t.getHistoryDiff())));
			}
		});
	}

	public Pager<History> queryObjectsForPage(int start,int limit ,History history) {
		if(history==null){
			history=new History();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, history, false, new SelectGenerateCallback<History>() {

			public Select generate(History t) {
				return MysqlSelect.selectFrom(HISTORYTABLE).where(
				and(
					HISTORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					HISTORYTABLE.ACTION_ID.eq(t.getActionId()),
					HISTORYTABLE.HISTORY_FIELD.eq(t.getHistoryField()),
					HISTORYTABLE.HISTORY_OLD.eq(t.getHistoryOld()),
					HISTORYTABLE.HISTORY_NEW.eq(t.getHistoryNew()),
					HISTORYTABLE.HISTORY_DIFF.eq(t.getHistoryDiff())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<History> historys) {
		if (CollectionUtil.isEmpty(historys)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, historys, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(HISTORYTABLE).values(
					HISTORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					HISTORYTABLE.ACTION_ID.value(new JdbcNamedParameter("actionId")),
					HISTORYTABLE.HISTORY_FIELD.value(new JdbcNamedParameter("historyField")),
					HISTORYTABLE.HISTORY_OLD.value(new JdbcNamedParameter("historyOld")),
					HISTORYTABLE.HISTORY_NEW.value(new JdbcNamedParameter("historyNew")),
					HISTORYTABLE.HISTORY_DIFF.value(new JdbcNamedParameter("historyDiff")));
			}
		});
	}

	public int[] batchInsert(List<History> historys){
			return batchInsert(true ,historys);
	}

	public int[] batchUpdate(List<History> historys) {
		if (CollectionUtil.isEmpty(historys)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(historys, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(HISTORYTABLE).set(
					HISTORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					HISTORYTABLE.ACTION_ID.value(new JdbcNamedParameter("actionId")),
					HISTORYTABLE.HISTORY_FIELD.value(new JdbcNamedParameter("historyField")),
					HISTORYTABLE.HISTORY_OLD.value(new JdbcNamedParameter("historyOld")),
					HISTORYTABLE.HISTORY_NEW.value(new JdbcNamedParameter("historyNew")),
					HISTORYTABLE.HISTORY_DIFF.value(new JdbcNamedParameter("historyDiff"))).where(
				HISTORYTABLE.HISTORY_ID.eq(new JdbcNamedParameter("historyId")));
			}
		});
	}

	public int[] batchDelete(List<History> historys) {
		if (CollectionUtil.isEmpty(historys)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(historys, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(HISTORYTABLE).where(and(
				HISTORYTABLE.HISTORY_ID.eq(new JdbcNamedParameter("historyId")),
				HISTORYTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				HISTORYTABLE.ACTION_ID.eq(new JdbcNamedParameter("actionId")),
				HISTORYTABLE.HISTORY_FIELD.eq(new JdbcNamedParameter("historyField")),
				HISTORYTABLE.HISTORY_OLD.eq(new JdbcNamedParameter("historyOld")),
				HISTORYTABLE.HISTORY_NEW.eq(new JdbcNamedParameter("historyNew")),
				HISTORYTABLE.HISTORY_DIFF.eq(new JdbcNamedParameter("historyDiff"))));
			}
		});
	}

}
