/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.RolePrivTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.RolePriv;
import org.tinygroup.sdpm.common.inter.RolePrivDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class RolePrivDaoImpl extends TinyDslDaoSupport implements RolePrivDao {

	public RolePriv insertObject(RolePriv rolePriv) {
		return getDslTemplate().insertObject(rolePriv, new InsertGenerateCallback<RolePriv>() {
			public Insert generate(RolePriv t) {
				Insert insert = insertInto(ROLEPRIVTABLE).values(
					ROLEPRIVTABLE.ROLE_PRIV_ID.value(t.getRolePrivId()),
					ROLEPRIVTABLE.COMPANY_ID.value(t.getCompanyId()),
					ROLEPRIVTABLE.ROLE_ID.value(t.getRoleId()),
					ROLEPRIVTABLE.MODULE_NAME.value(t.getModuleName()),
					ROLEPRIVTABLE.FUNCTION.value(t.getFunction()));
				return insert;
			}
		});
	}

	public RolePriv insertObject(boolean autoGeneratedKeys ,RolePriv rolePriv) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,rolePriv, new InsertGenerateCallback<RolePriv>() {

			public Insert generate(RolePriv t) {
				Insert insert = insertInto(ROLEPRIVTABLE).values(
					ROLEPRIVTABLE.ROLE_PRIV_ID.value(t.getRolePrivId()),
					ROLEPRIVTABLE.COMPANY_ID.value(t.getCompanyId()),
					ROLEPRIVTABLE.ROLE_ID.value(t.getRoleId()),
					ROLEPRIVTABLE.MODULE_NAME.value(t.getModuleName()),
					ROLEPRIVTABLE.FUNCTION.value(t.getFunction()));
				return insert;
			}
		});
	}

	public int updateObject(RolePriv rolePriv) {
		return getDslTemplate().updateObject(rolePriv, new UpdateGenerateCallback<RolePriv>() {
			public Update generate(RolePriv t) {
				Update update = update(ROLEPRIVTABLE).set(
					ROLEPRIVTABLE.COMPANY_ID.value(t.getCompanyId()),
					ROLEPRIVTABLE.ROLE_ID.value(t.getRoleId()),
					ROLEPRIVTABLE.MODULE_NAME.value(t.getModuleName()),
					ROLEPRIVTABLE.FUNCTION.value(t.getFunction())).where(
					ROLEPRIVTABLE.ROLE_PRIV_ID.eq(t.getRolePrivId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(ROLEPRIVTABLE).where(ROLEPRIVTABLE.ROLE_PRIV_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(ROLEPRIVTABLE).where(ROLEPRIVTABLE.ROLE_PRIV_ID.in(t));
		}
		},pks);
	}

	public RolePriv getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, RolePriv.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(ROLEPRIVTABLE).where(ROLEPRIVTABLE.ROLE_PRIV_ID.eq(t));
			}
		});
	}

	public List<RolePriv> queryObjects(RolePriv rolePriv) {
		if(rolePriv==null){
			rolePriv=new RolePriv();
		}
		return getDslTemplate().queryObjects(rolePriv, new SelectGenerateCallback<RolePriv>() {

			@SuppressWarnings("rawtypes")
			public Select generate(RolePriv t) {
				return selectFrom(ROLEPRIVTABLE).where(
				and(
					ROLEPRIVTABLE.COMPANY_ID.eq(t.getCompanyId()),
					ROLEPRIVTABLE.ROLE_ID.eq(t.getRoleId()),
					ROLEPRIVTABLE.MODULE_NAME.eq(t.getModuleName()),
					ROLEPRIVTABLE.FUNCTION.eq(t.getFunction())));
			}
		});
	}

	public Pager<RolePriv> queryObjectsForPage(int start,int limit ,RolePriv rolePriv) {
		if(rolePriv==null){
			rolePriv=new RolePriv();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, rolePriv, false, new SelectGenerateCallback<RolePriv>() {

			public Select generate(RolePriv t) {
				return MysqlSelect.selectFrom(ROLEPRIVTABLE).where(
				and(
					ROLEPRIVTABLE.COMPANY_ID.eq(t.getCompanyId()),
					ROLEPRIVTABLE.ROLE_ID.eq(t.getRoleId()),
					ROLEPRIVTABLE.MODULE_NAME.eq(t.getModuleName()),
					ROLEPRIVTABLE.FUNCTION.eq(t.getFunction())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<RolePriv> rolePrivs) {
		if (CollectionUtil.isEmpty(rolePrivs)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, rolePrivs, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(ROLEPRIVTABLE).values(
					ROLEPRIVTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					ROLEPRIVTABLE.ROLE_ID.value(new JdbcNamedParameter("roleId")),
					ROLEPRIVTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					ROLEPRIVTABLE.FUNCTION.value(new JdbcNamedParameter("function")));
			}
		});
	}

	public int[] batchInsert(List<RolePriv> rolePrivs){
			return batchInsert(true ,rolePrivs);
	}

	public int[] batchUpdate(List<RolePriv> rolePrivs) {
		if (CollectionUtil.isEmpty(rolePrivs)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(rolePrivs, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(ROLEPRIVTABLE).set(
					ROLEPRIVTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					ROLEPRIVTABLE.ROLE_ID.value(new JdbcNamedParameter("roleId")),
					ROLEPRIVTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					ROLEPRIVTABLE.FUNCTION.value(new JdbcNamedParameter("function"))).where(
				ROLEPRIVTABLE.ROLE_PRIV_ID.eq(new JdbcNamedParameter("rolePrivId")));
			}
		});
	}

	public int[] batchDelete(List<RolePriv> rolePrivs) {
		if (CollectionUtil.isEmpty(rolePrivs)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(rolePrivs, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(ROLEPRIVTABLE).where(and(
				ROLEPRIVTABLE.ROLE_PRIV_ID.eq(new JdbcNamedParameter("rolePrivId")),
				ROLEPRIVTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				ROLEPRIVTABLE.ROLE_ID.eq(new JdbcNamedParameter("roleId")),
				ROLEPRIVTABLE.MODULE_NAME.eq(new JdbcNamedParameter("moduleName")),
				ROLEPRIVTABLE.FUNCTION.eq(new JdbcNamedParameter("function"))));
			}
		});
	}

}
