/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.SysFuncTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.SysFunc;
import org.tinygroup.sdpm.common.inter.SysFuncDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class SysFuncDaoImpl extends TinyDslDaoSupport implements SysFuncDao {

	public SysFunc insertObject(SysFunc sysFunc) {
		return getDslTemplate().insertObject(sysFunc, new InsertGenerateCallback<SysFunc>() {
			public Insert generate(SysFunc t) {
				Insert insert = insertInto(SYSFUNCTABLE).values(
					SYSFUNCTABLE.FUNCTION_ID.value(t.getFunctionId()),
					SYSFUNCTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSFUNCTABLE.MODULE_NAME.value(t.getModuleName()),
					SYSFUNCTABLE.FUNCTION.value(t.getFunction()),
					SYSFUNCTABLE.ACL.value(t.getAcl()));
				return insert;
			}
		});
	}

	public SysFunc insertObject(boolean autoGeneratedKeys ,SysFunc sysFunc) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,sysFunc, new InsertGenerateCallback<SysFunc>() {

			public Insert generate(SysFunc t) {
				Insert insert = insertInto(SYSFUNCTABLE).values(
					SYSFUNCTABLE.FUNCTION_ID.value(t.getFunctionId()),
					SYSFUNCTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSFUNCTABLE.MODULE_NAME.value(t.getModuleName()),
					SYSFUNCTABLE.FUNCTION.value(t.getFunction()),
					SYSFUNCTABLE.ACL.value(t.getAcl()));
				return insert;
			}
		});
	}

	public int updateObject(SysFunc sysFunc) {
		return getDslTemplate().updateObject(sysFunc, new UpdateGenerateCallback<SysFunc>() {
			public Update generate(SysFunc t) {
				Update update = update(SYSFUNCTABLE).set(
					SYSFUNCTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSFUNCTABLE.MODULE_NAME.value(t.getModuleName()),
					SYSFUNCTABLE.FUNCTION.value(t.getFunction()),
					SYSFUNCTABLE.ACL.value(t.getAcl())).where(
					SYSFUNCTABLE.FUNCTION_ID.eq(t.getFunctionId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(SYSFUNCTABLE).where(SYSFUNCTABLE.FUNCTION_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(SYSFUNCTABLE).where(SYSFUNCTABLE.FUNCTION_ID.in(t));
		}
		},pks);
	}

	public SysFunc getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, SysFunc.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(SYSFUNCTABLE).where(SYSFUNCTABLE.FUNCTION_ID.eq(t));
			}
		});
	}

	public List<SysFunc> queryObjects(SysFunc sysFunc) {
		if(sysFunc==null){
			sysFunc=new SysFunc();
		}
		return getDslTemplate().queryObjects(sysFunc, new SelectGenerateCallback<SysFunc>() {

			@SuppressWarnings("rawtypes")
			public Select generate(SysFunc t) {
				return selectFrom(SYSFUNCTABLE).where(
				and(
					SYSFUNCTABLE.COMPANY_ID.eq(t.getCompanyId()),
					SYSFUNCTABLE.MODULE_NAME.eq(t.getModuleName()),
					SYSFUNCTABLE.FUNCTION.eq(t.getFunction()),
					SYSFUNCTABLE.ACL.eq(t.getAcl())));
			}
		});
	}

	public Pager<SysFunc> queryObjectsForPage(int start,int limit ,SysFunc sysFunc) {
		if(sysFunc==null){
			sysFunc=new SysFunc();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, sysFunc, false, new SelectGenerateCallback<SysFunc>() {

			public Select generate(SysFunc t) {
				return MysqlSelect.selectFrom(SYSFUNCTABLE).where(
				and(
					SYSFUNCTABLE.COMPANY_ID.eq(t.getCompanyId()),
					SYSFUNCTABLE.MODULE_NAME.eq(t.getModuleName()),
					SYSFUNCTABLE.FUNCTION.eq(t.getFunction()),
					SYSFUNCTABLE.ACL.eq(t.getAcl())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<SysFunc> sysFuncs) {
		if (CollectionUtil.isEmpty(sysFuncs)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, sysFuncs, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(SYSFUNCTABLE).values(
					SYSFUNCTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					SYSFUNCTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					SYSFUNCTABLE.FUNCTION.value(new JdbcNamedParameter("function")),
					SYSFUNCTABLE.ACL.value(new JdbcNamedParameter("acl")));
			}
		});
	}

	public int[] batchInsert(List<SysFunc> sysFuncs){
			return batchInsert(true ,sysFuncs);
	}

	public int[] batchUpdate(List<SysFunc> sysFuncs) {
		if (CollectionUtil.isEmpty(sysFuncs)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(sysFuncs, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(SYSFUNCTABLE).set(
					SYSFUNCTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					SYSFUNCTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					SYSFUNCTABLE.FUNCTION.value(new JdbcNamedParameter("function")),
					SYSFUNCTABLE.ACL.value(new JdbcNamedParameter("acl"))).where(
				SYSFUNCTABLE.FUNCTION_ID.eq(new JdbcNamedParameter("functionId")));
			}
		});
	}

	public int[] batchDelete(List<SysFunc> sysFuncs) {
		if (CollectionUtil.isEmpty(sysFuncs)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(sysFuncs, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(SYSFUNCTABLE).where(and(
				SYSFUNCTABLE.FUNCTION_ID.eq(new JdbcNamedParameter("functionId")),
				SYSFUNCTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				SYSFUNCTABLE.MODULE_NAME.eq(new JdbcNamedParameter("moduleName")),
				SYSFUNCTABLE.FUNCTION.eq(new JdbcNamedParameter("function")),
				SYSFUNCTABLE.ACL.eq(new JdbcNamedParameter("acl"))));
			}
		});
	}

}
