/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.SysUserTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.SysUser;
import org.tinygroup.sdpm.common.inter.SysUserDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class SysUserDaoImpl extends TinyDslDaoSupport implements SysUserDao {

	public SysUser insertObject(SysUser sysUser) {
		return getDslTemplate().insertObject(sysUser, new InsertGenerateCallback<SysUser>() {
			public Insert generate(SysUser t) {
				Insert insert = insertInto(SYSUSERTABLE).values(
					SYSUSERTABLE.USER_ID.value(t.getUserId()),
					SYSUSERTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSUSERTABLE.DEPT_ID.value(t.getDeptId()),
					SYSUSERTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					SYSUSERTABLE.USER_PASSWORD.value(t.getUserPassword()),
					SYSUSERTABLE.USER_REALNAME.value(t.getUserRealname()),
					SYSUSERTABLE.USER_NICKNAME.value(t.getUserNickname()),
					SYSUSERTABLE.USER_AVATAR.value(t.getUserAvatar()),
					SYSUSERTABLE.USER_BIRTHDAY.value(t.getUserBirthday()),
					SYSUSERTABLE.USER_GENDER.value(t.getUserGender()),
					SYSUSERTABLE.USER_EMAIL.value(t.getUserEmail()),
					SYSUSERTABLE.USER_MSN.value(t.getUserMsn()),
					SYSUSERTABLE.USER_QQ.value(t.getUserQq()),
					SYSUSERTABLE.USER_GTALK.value(t.getUserGtalk()),
					SYSUSERTABLE.USER_MOBILE.value(t.getUserMobile()),
					SYSUSERTABLE.USER_PHONE.value(t.getUserPhone()),
					SYSUSERTABLE.USER_ADDRESS.value(t.getUserAddress()),
					SYSUSERTABLE.USER_ZIPCODE.value(t.getUserZipcode()),
					SYSUSERTABLE.USER_REGDATE.value(t.getUserRegdate()),
					SYSUSERTABLE.USER_VISITS.value(t.getUserVisits()),
					SYSUSERTABLE.USER_IP.value(t.getUserIp()),
					SYSUSERTABLE.USER_LASTVISIT.value(t.getUserLastvisit()),
					SYSUSERTABLE.USER_POSITION.value(t.getUserPosition()),
					SYSUSERTABLE.USER_LAST.value(t.getUserLast()),
					SYSUSERTABLE.USER_TITLE.value(t.getUserTitle()),
					SYSUSERTABLE.USER_STATUS.value(t.getUserStatus()),
					SYSUSERTABLE.USER_ONLINETIME.value(t.getUserOnlinetime()),
					SYSUSERTABLE.USER_ONLINETIMEM.value(t.getUserOnlinetimem()),
					SYSUSERTABLE.USER_VISITSM.value(t.getUserVisitsm()),
					SYSUSERTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public SysUser insertObject(boolean autoGeneratedKeys ,SysUser sysUser) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,sysUser, new InsertGenerateCallback<SysUser>() {

			public Insert generate(SysUser t) {
				Insert insert = insertInto(SYSUSERTABLE).values(
					SYSUSERTABLE.USER_ID.value(t.getUserId()),
					SYSUSERTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSUSERTABLE.DEPT_ID.value(t.getDeptId()),
					SYSUSERTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					SYSUSERTABLE.USER_PASSWORD.value(t.getUserPassword()),
					SYSUSERTABLE.USER_REALNAME.value(t.getUserRealname()),
					SYSUSERTABLE.USER_NICKNAME.value(t.getUserNickname()),
					SYSUSERTABLE.USER_AVATAR.value(t.getUserAvatar()),
					SYSUSERTABLE.USER_BIRTHDAY.value(t.getUserBirthday()),
					SYSUSERTABLE.USER_GENDER.value(t.getUserGender()),
					SYSUSERTABLE.USER_EMAIL.value(t.getUserEmail()),
					SYSUSERTABLE.USER_MSN.value(t.getUserMsn()),
					SYSUSERTABLE.USER_QQ.value(t.getUserQq()),
					SYSUSERTABLE.USER_GTALK.value(t.getUserGtalk()),
					SYSUSERTABLE.USER_MOBILE.value(t.getUserMobile()),
					SYSUSERTABLE.USER_PHONE.value(t.getUserPhone()),
					SYSUSERTABLE.USER_ADDRESS.value(t.getUserAddress()),
					SYSUSERTABLE.USER_ZIPCODE.value(t.getUserZipcode()),
					SYSUSERTABLE.USER_REGDATE.value(t.getUserRegdate()),
					SYSUSERTABLE.USER_VISITS.value(t.getUserVisits()),
					SYSUSERTABLE.USER_IP.value(t.getUserIp()),
					SYSUSERTABLE.USER_LASTVISIT.value(t.getUserLastvisit()),
					SYSUSERTABLE.USER_POSITION.value(t.getUserPosition()),
					SYSUSERTABLE.USER_LAST.value(t.getUserLast()),
					SYSUSERTABLE.USER_TITLE.value(t.getUserTitle()),
					SYSUSERTABLE.USER_STATUS.value(t.getUserStatus()),
					SYSUSERTABLE.USER_ONLINETIME.value(t.getUserOnlinetime()),
					SYSUSERTABLE.USER_ONLINETIMEM.value(t.getUserOnlinetimem()),
					SYSUSERTABLE.USER_VISITSM.value(t.getUserVisitsm()),
					SYSUSERTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(SysUser sysUser) {
		return getDslTemplate().updateObject(sysUser, new UpdateGenerateCallback<SysUser>() {
			public Update generate(SysUser t) {
				Update update = update(SYSUSERTABLE).set(
					SYSUSERTABLE.COMPANY_ID.value(t.getCompanyId()),
					SYSUSERTABLE.DEPT_ID.value(t.getDeptId()),
					SYSUSERTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					SYSUSERTABLE.USER_PASSWORD.value(t.getUserPassword()),
					SYSUSERTABLE.USER_REALNAME.value(t.getUserRealname()),
					SYSUSERTABLE.USER_NICKNAME.value(t.getUserNickname()),
					SYSUSERTABLE.USER_AVATAR.value(t.getUserAvatar()),
					SYSUSERTABLE.USER_BIRTHDAY.value(t.getUserBirthday()),
					SYSUSERTABLE.USER_GENDER.value(t.getUserGender()),
					SYSUSERTABLE.USER_EMAIL.value(t.getUserEmail()),
					SYSUSERTABLE.USER_MSN.value(t.getUserMsn()),
					SYSUSERTABLE.USER_QQ.value(t.getUserQq()),
					SYSUSERTABLE.USER_GTALK.value(t.getUserGtalk()),
					SYSUSERTABLE.USER_MOBILE.value(t.getUserMobile()),
					SYSUSERTABLE.USER_PHONE.value(t.getUserPhone()),
					SYSUSERTABLE.USER_ADDRESS.value(t.getUserAddress()),
					SYSUSERTABLE.USER_ZIPCODE.value(t.getUserZipcode()),
					SYSUSERTABLE.USER_REGDATE.value(t.getUserRegdate()),
					SYSUSERTABLE.USER_VISITS.value(t.getUserVisits()),
					SYSUSERTABLE.USER_IP.value(t.getUserIp()),
					SYSUSERTABLE.USER_LASTVISIT.value(t.getUserLastvisit()),
					SYSUSERTABLE.USER_POSITION.value(t.getUserPosition()),
					SYSUSERTABLE.USER_LAST.value(t.getUserLast()),
					SYSUSERTABLE.USER_TITLE.value(t.getUserTitle()),
					SYSUSERTABLE.USER_STATUS.value(t.getUserStatus()),
					SYSUSERTABLE.USER_ONLINETIME.value(t.getUserOnlinetime()),
					SYSUSERTABLE.USER_ONLINETIMEM.value(t.getUserOnlinetimem()),
					SYSUSERTABLE.USER_VISITSM.value(t.getUserVisitsm()),
					SYSUSERTABLE.DELETED.value(t.getDeleted())).where(
					SYSUSERTABLE.USER_ID.eq(t.getUserId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(SYSUSERTABLE).where(SYSUSERTABLE.USER_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(SYSUSERTABLE).where(SYSUSERTABLE.USER_ID.in(t));
		}
		},pks);
	}

	public SysUser getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, SysUser.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(SYSUSERTABLE).where(SYSUSERTABLE.USER_ID.eq(t));
			}
		});
	}

	public List<SysUser> queryObjects(SysUser sysUser) {
		if(sysUser==null){
			sysUser=new SysUser();
		}
		return getDslTemplate().queryObjects(sysUser, new SelectGenerateCallback<SysUser>() {

			@SuppressWarnings("rawtypes")
			public Select generate(SysUser t) {
				return selectFrom(SYSUSERTABLE).where(
				and(
					SYSUSERTABLE.COMPANY_ID.eq(t.getCompanyId()),
					SYSUSERTABLE.DEPT_ID.eq(t.getDeptId()),
					SYSUSERTABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					SYSUSERTABLE.USER_PASSWORD.eq(t.getUserPassword()),
					SYSUSERTABLE.USER_REALNAME.eq(t.getUserRealname()),
					SYSUSERTABLE.USER_NICKNAME.eq(t.getUserNickname()),
					SYSUSERTABLE.USER_AVATAR.eq(t.getUserAvatar()),
					SYSUSERTABLE.USER_BIRTHDAY.eq(t.getUserBirthday()),
					SYSUSERTABLE.USER_GENDER.eq(t.getUserGender()),
					SYSUSERTABLE.USER_EMAIL.eq(t.getUserEmail()),
					SYSUSERTABLE.USER_MSN.eq(t.getUserMsn()),
					SYSUSERTABLE.USER_QQ.eq(t.getUserQq()),
					SYSUSERTABLE.USER_GTALK.eq(t.getUserGtalk()),
					SYSUSERTABLE.USER_MOBILE.eq(t.getUserMobile()),
					SYSUSERTABLE.USER_PHONE.eq(t.getUserPhone()),
					SYSUSERTABLE.USER_ADDRESS.eq(t.getUserAddress()),
					SYSUSERTABLE.USER_ZIPCODE.eq(t.getUserZipcode()),
					SYSUSERTABLE.USER_REGDATE.eq(t.getUserRegdate()),
					SYSUSERTABLE.USER_VISITS.eq(t.getUserVisits()),
					SYSUSERTABLE.USER_IP.eq(t.getUserIp()),
					SYSUSERTABLE.USER_LASTVISIT.eq(t.getUserLastvisit()),
					SYSUSERTABLE.USER_POSITION.eq(t.getUserPosition()),
					SYSUSERTABLE.USER_LAST.eq(t.getUserLast()),
					SYSUSERTABLE.USER_TITLE.eq(t.getUserTitle()),
					SYSUSERTABLE.USER_STATUS.eq(t.getUserStatus()),
					SYSUSERTABLE.USER_ONLINETIME.eq(t.getUserOnlinetime()),
					SYSUSERTABLE.USER_ONLINETIMEM.eq(t.getUserOnlinetimem()),
					SYSUSERTABLE.USER_VISITSM.eq(t.getUserVisitsm()),
					SYSUSERTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<SysUser> queryObjectsForPage(int start,int limit ,SysUser sysUser) {
		if(sysUser==null){
			sysUser=new SysUser();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, sysUser, false, new SelectGenerateCallback<SysUser>() {

			public Select generate(SysUser t) {
				return MysqlSelect.selectFrom(SYSUSERTABLE).where(
				and(
					SYSUSERTABLE.COMPANY_ID.eq(t.getCompanyId()),
					SYSUSERTABLE.DEPT_ID.eq(t.getDeptId()),
					SYSUSERTABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					SYSUSERTABLE.USER_PASSWORD.eq(t.getUserPassword()),
					SYSUSERTABLE.USER_REALNAME.eq(t.getUserRealname()),
					SYSUSERTABLE.USER_NICKNAME.eq(t.getUserNickname()),
					SYSUSERTABLE.USER_AVATAR.eq(t.getUserAvatar()),
					SYSUSERTABLE.USER_BIRTHDAY.eq(t.getUserBirthday()),
					SYSUSERTABLE.USER_GENDER.eq(t.getUserGender()),
					SYSUSERTABLE.USER_EMAIL.eq(t.getUserEmail()),
					SYSUSERTABLE.USER_MSN.eq(t.getUserMsn()),
					SYSUSERTABLE.USER_QQ.eq(t.getUserQq()),
					SYSUSERTABLE.USER_GTALK.eq(t.getUserGtalk()),
					SYSUSERTABLE.USER_MOBILE.eq(t.getUserMobile()),
					SYSUSERTABLE.USER_PHONE.eq(t.getUserPhone()),
					SYSUSERTABLE.USER_ADDRESS.eq(t.getUserAddress()),
					SYSUSERTABLE.USER_ZIPCODE.eq(t.getUserZipcode()),
					SYSUSERTABLE.USER_REGDATE.eq(t.getUserRegdate()),
					SYSUSERTABLE.USER_VISITS.eq(t.getUserVisits()),
					SYSUSERTABLE.USER_IP.eq(t.getUserIp()),
					SYSUSERTABLE.USER_LASTVISIT.eq(t.getUserLastvisit()),
					SYSUSERTABLE.USER_POSITION.eq(t.getUserPosition()),
					SYSUSERTABLE.USER_LAST.eq(t.getUserLast()),
					SYSUSERTABLE.USER_TITLE.eq(t.getUserTitle()),
					SYSUSERTABLE.USER_STATUS.eq(t.getUserStatus()),
					SYSUSERTABLE.USER_ONLINETIME.eq(t.getUserOnlinetime()),
					SYSUSERTABLE.USER_ONLINETIMEM.eq(t.getUserOnlinetimem()),
					SYSUSERTABLE.USER_VISITSM.eq(t.getUserVisitsm()),
					SYSUSERTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<SysUser> sysUsers) {
		if (CollectionUtil.isEmpty(sysUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, sysUsers, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(SYSUSERTABLE).values(
					SYSUSERTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					SYSUSERTABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					SYSUSERTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					SYSUSERTABLE.USER_PASSWORD.value(new JdbcNamedParameter("userPassword")),
					SYSUSERTABLE.USER_REALNAME.value(new JdbcNamedParameter("userRealname")),
					SYSUSERTABLE.USER_NICKNAME.value(new JdbcNamedParameter("userNickname")),
					SYSUSERTABLE.USER_AVATAR.value(new JdbcNamedParameter("userAvatar")),
					SYSUSERTABLE.USER_BIRTHDAY.value(new JdbcNamedParameter("userBirthday")),
					SYSUSERTABLE.USER_GENDER.value(new JdbcNamedParameter("userGender")),
					SYSUSERTABLE.USER_EMAIL.value(new JdbcNamedParameter("userEmail")),
					SYSUSERTABLE.USER_MSN.value(new JdbcNamedParameter("userMsn")),
					SYSUSERTABLE.USER_QQ.value(new JdbcNamedParameter("userQq")),
					SYSUSERTABLE.USER_GTALK.value(new JdbcNamedParameter("userGtalk")),
					SYSUSERTABLE.USER_MOBILE.value(new JdbcNamedParameter("userMobile")),
					SYSUSERTABLE.USER_PHONE.value(new JdbcNamedParameter("userPhone")),
					SYSUSERTABLE.USER_ADDRESS.value(new JdbcNamedParameter("userAddress")),
					SYSUSERTABLE.USER_ZIPCODE.value(new JdbcNamedParameter("userZipcode")),
					SYSUSERTABLE.USER_REGDATE.value(new JdbcNamedParameter("userRegdate")),
					SYSUSERTABLE.USER_VISITS.value(new JdbcNamedParameter("userVisits")),
					SYSUSERTABLE.USER_IP.value(new JdbcNamedParameter("userIp")),
					SYSUSERTABLE.USER_LASTVISIT.value(new JdbcNamedParameter("userLastvisit")),
					SYSUSERTABLE.USER_POSITION.value(new JdbcNamedParameter("userPosition")),
					SYSUSERTABLE.USER_LAST.value(new JdbcNamedParameter("userLast")),
					SYSUSERTABLE.USER_TITLE.value(new JdbcNamedParameter("userTitle")),
					SYSUSERTABLE.USER_STATUS.value(new JdbcNamedParameter("userStatus")),
					SYSUSERTABLE.USER_ONLINETIME.value(new JdbcNamedParameter("userOnlinetime")),
					SYSUSERTABLE.USER_ONLINETIMEM.value(new JdbcNamedParameter("userOnlinetimem")),
					SYSUSERTABLE.USER_VISITSM.value(new JdbcNamedParameter("userVisitsm")),
					SYSUSERTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<SysUser> sysUsers){
			return batchInsert(true ,sysUsers);
	}

	public int[] batchUpdate(List<SysUser> sysUsers) {
		if (CollectionUtil.isEmpty(sysUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(sysUsers, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(SYSUSERTABLE).set(
					SYSUSERTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					SYSUSERTABLE.DEPT_ID.value(new JdbcNamedParameter("deptId")),
					SYSUSERTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					SYSUSERTABLE.USER_PASSWORD.value(new JdbcNamedParameter("userPassword")),
					SYSUSERTABLE.USER_REALNAME.value(new JdbcNamedParameter("userRealname")),
					SYSUSERTABLE.USER_NICKNAME.value(new JdbcNamedParameter("userNickname")),
					SYSUSERTABLE.USER_AVATAR.value(new JdbcNamedParameter("userAvatar")),
					SYSUSERTABLE.USER_BIRTHDAY.value(new JdbcNamedParameter("userBirthday")),
					SYSUSERTABLE.USER_GENDER.value(new JdbcNamedParameter("userGender")),
					SYSUSERTABLE.USER_EMAIL.value(new JdbcNamedParameter("userEmail")),
					SYSUSERTABLE.USER_MSN.value(new JdbcNamedParameter("userMsn")),
					SYSUSERTABLE.USER_QQ.value(new JdbcNamedParameter("userQq")),
					SYSUSERTABLE.USER_GTALK.value(new JdbcNamedParameter("userGtalk")),
					SYSUSERTABLE.USER_MOBILE.value(new JdbcNamedParameter("userMobile")),
					SYSUSERTABLE.USER_PHONE.value(new JdbcNamedParameter("userPhone")),
					SYSUSERTABLE.USER_ADDRESS.value(new JdbcNamedParameter("userAddress")),
					SYSUSERTABLE.USER_ZIPCODE.value(new JdbcNamedParameter("userZipcode")),
					SYSUSERTABLE.USER_REGDATE.value(new JdbcNamedParameter("userRegdate")),
					SYSUSERTABLE.USER_VISITS.value(new JdbcNamedParameter("userVisits")),
					SYSUSERTABLE.USER_IP.value(new JdbcNamedParameter("userIp")),
					SYSUSERTABLE.USER_LASTVISIT.value(new JdbcNamedParameter("userLastvisit")),
					SYSUSERTABLE.USER_POSITION.value(new JdbcNamedParameter("userPosition")),
					SYSUSERTABLE.USER_LAST.value(new JdbcNamedParameter("userLast")),
					SYSUSERTABLE.USER_TITLE.value(new JdbcNamedParameter("userTitle")),
					SYSUSERTABLE.USER_STATUS.value(new JdbcNamedParameter("userStatus")),
					SYSUSERTABLE.USER_ONLINETIME.value(new JdbcNamedParameter("userOnlinetime")),
					SYSUSERTABLE.USER_ONLINETIMEM.value(new JdbcNamedParameter("userOnlinetimem")),
					SYSUSERTABLE.USER_VISITSM.value(new JdbcNamedParameter("userVisitsm")),
					SYSUSERTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				SYSUSERTABLE.USER_ID.eq(new JdbcNamedParameter("userId")));
			}
		});
	}

	public int[] batchDelete(List<SysUser> sysUsers) {
		if (CollectionUtil.isEmpty(sysUsers)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(sysUsers, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(SYSUSERTABLE).where(and(
				SYSUSERTABLE.USER_ID.eq(new JdbcNamedParameter("userId")),
				SYSUSERTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				SYSUSERTABLE.DEPT_ID.eq(new JdbcNamedParameter("deptId")),
				SYSUSERTABLE.USER_ACCOUNT.eq(new JdbcNamedParameter("userAccount")),
				SYSUSERTABLE.USER_PASSWORD.eq(new JdbcNamedParameter("userPassword")),
				SYSUSERTABLE.USER_REALNAME.eq(new JdbcNamedParameter("userRealname")),
				SYSUSERTABLE.USER_NICKNAME.eq(new JdbcNamedParameter("userNickname")),
				SYSUSERTABLE.USER_AVATAR.eq(new JdbcNamedParameter("userAvatar")),
				SYSUSERTABLE.USER_BIRTHDAY.eq(new JdbcNamedParameter("userBirthday")),
				SYSUSERTABLE.USER_GENDER.eq(new JdbcNamedParameter("userGender")),
				SYSUSERTABLE.USER_EMAIL.eq(new JdbcNamedParameter("userEmail")),
				SYSUSERTABLE.USER_MSN.eq(new JdbcNamedParameter("userMsn")),
				SYSUSERTABLE.USER_QQ.eq(new JdbcNamedParameter("userQq")),
				SYSUSERTABLE.USER_GTALK.eq(new JdbcNamedParameter("userGtalk")),
				SYSUSERTABLE.USER_MOBILE.eq(new JdbcNamedParameter("userMobile")),
				SYSUSERTABLE.USER_PHONE.eq(new JdbcNamedParameter("userPhone")),
				SYSUSERTABLE.USER_ADDRESS.eq(new JdbcNamedParameter("userAddress")),
				SYSUSERTABLE.USER_ZIPCODE.eq(new JdbcNamedParameter("userZipcode")),
				SYSUSERTABLE.USER_REGDATE.eq(new JdbcNamedParameter("userRegdate")),
				SYSUSERTABLE.USER_VISITS.eq(new JdbcNamedParameter("userVisits")),
				SYSUSERTABLE.USER_IP.eq(new JdbcNamedParameter("userIp")),
				SYSUSERTABLE.USER_LASTVISIT.eq(new JdbcNamedParameter("userLastvisit")),
				SYSUSERTABLE.USER_POSITION.eq(new JdbcNamedParameter("userPosition")),
				SYSUSERTABLE.USER_LAST.eq(new JdbcNamedParameter("userLast")),
				SYSUSERTABLE.USER_TITLE.eq(new JdbcNamedParameter("userTitle")),
				SYSUSERTABLE.USER_STATUS.eq(new JdbcNamedParameter("userStatus")),
				SYSUSERTABLE.USER_ONLINETIME.eq(new JdbcNamedParameter("userOnlinetime")),
				SYSUSERTABLE.USER_ONLINETIMEM.eq(new JdbcNamedParameter("userOnlinetimem")),
				SYSUSERTABLE.USER_VISITSM.eq(new JdbcNamedParameter("userVisitsm")),
				SYSUSERTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
