/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.UserQueryTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.UserQuery;
import org.tinygroup.sdpm.common.inter.UserQueryDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class UserQueryDaoImpl extends TinyDslDaoSupport implements UserQueryDao {

	public UserQuery insertObject(UserQuery userQuery) {
		return getDslTemplate().insertObject(userQuery, new InsertGenerateCallback<UserQuery>() {
			public Insert generate(UserQuery t) {
				Insert insert = insertInto(USERQUERYTABLE).values(
					USERQUERYTABLE.USERQUERY_ID.value(t.getUserqueryId()),
					USERQUERYTABLE.COMPANY_ID.value(t.getCompanyId()),
					USERQUERYTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERQUERYTABLE.MODULE_NAME.value(t.getModuleName()),
					USERQUERYTABLE.USERQUERY_TITLE.value(t.getUserqueryTitle()),
					USERQUERYTABLE.USERQUERY_FORM.value(t.getUserqueryForm()),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.value(t.getUserquerySqlcondition()));
				return insert;
			}
		});
	}

	public UserQuery insertObject(boolean autoGeneratedKeys ,UserQuery userQuery) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,userQuery, new InsertGenerateCallback<UserQuery>() {

			public Insert generate(UserQuery t) {
				Insert insert = insertInto(USERQUERYTABLE).values(
					USERQUERYTABLE.USERQUERY_ID.value(t.getUserqueryId()),
					USERQUERYTABLE.COMPANY_ID.value(t.getCompanyId()),
					USERQUERYTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERQUERYTABLE.MODULE_NAME.value(t.getModuleName()),
					USERQUERYTABLE.USERQUERY_TITLE.value(t.getUserqueryTitle()),
					USERQUERYTABLE.USERQUERY_FORM.value(t.getUserqueryForm()),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.value(t.getUserquerySqlcondition()));
				return insert;
			}
		});
	}

	public int updateObject(UserQuery userQuery) {
		return getDslTemplate().updateObject(userQuery, new UpdateGenerateCallback<UserQuery>() {
			public Update generate(UserQuery t) {
				Update update = update(USERQUERYTABLE).set(
					USERQUERYTABLE.COMPANY_ID.value(t.getCompanyId()),
					USERQUERYTABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERQUERYTABLE.MODULE_NAME.value(t.getModuleName()),
					USERQUERYTABLE.USERQUERY_TITLE.value(t.getUserqueryTitle()),
					USERQUERYTABLE.USERQUERY_FORM.value(t.getUserqueryForm()),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.value(t.getUserquerySqlcondition())).where(
					USERQUERYTABLE.USERQUERY_ID.eq(t.getUserqueryId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(USERQUERYTABLE).where(USERQUERYTABLE.USERQUERY_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(USERQUERYTABLE).where(USERQUERYTABLE.USERQUERY_ID.in(t));
		}
		},pks);
	}

	public UserQuery getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, UserQuery.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(USERQUERYTABLE).where(USERQUERYTABLE.USERQUERY_ID.eq(t));
			}
		});
	}

	public List<UserQuery> queryObjects(UserQuery userQuery) {
		if(userQuery==null){
			userQuery=new UserQuery();
		}
		return getDslTemplate().queryObjects(userQuery, new SelectGenerateCallback<UserQuery>() {

			@SuppressWarnings("rawtypes")
			public Select generate(UserQuery t) {
				return selectFrom(USERQUERYTABLE).where(
				and(
					USERQUERYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					USERQUERYTABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					USERQUERYTABLE.MODULE_NAME.eq(t.getModuleName()),
					USERQUERYTABLE.USERQUERY_TITLE.eq(t.getUserqueryTitle()),
					USERQUERYTABLE.USERQUERY_FORM.eq(t.getUserqueryForm()),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.eq(t.getUserquerySqlcondition())));
			}
		});
	}

	public Pager<UserQuery> queryObjectsForPage(int start,int limit ,UserQuery userQuery) {
		if(userQuery==null){
			userQuery=new UserQuery();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, userQuery, false, new SelectGenerateCallback<UserQuery>() {

			public Select generate(UserQuery t) {
				return MysqlSelect.selectFrom(USERQUERYTABLE).where(
				and(
					USERQUERYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					USERQUERYTABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					USERQUERYTABLE.MODULE_NAME.eq(t.getModuleName()),
					USERQUERYTABLE.USERQUERY_TITLE.eq(t.getUserqueryTitle()),
					USERQUERYTABLE.USERQUERY_FORM.eq(t.getUserqueryForm()),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.eq(t.getUserquerySqlcondition())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<UserQuery> userQuerys) {
		if (CollectionUtil.isEmpty(userQuerys)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, userQuerys, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(USERQUERYTABLE).values(
					USERQUERYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					USERQUERYTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					USERQUERYTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					USERQUERYTABLE.USERQUERY_TITLE.value(new JdbcNamedParameter("userqueryTitle")),
					USERQUERYTABLE.USERQUERY_FORM.value(new JdbcNamedParameter("userqueryForm")),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.value(new JdbcNamedParameter("userquerySqlcondition")));
			}
		});
	}

	public int[] batchInsert(List<UserQuery> userQuerys){
			return batchInsert(true ,userQuerys);
	}

	public int[] batchUpdate(List<UserQuery> userQuerys) {
		if (CollectionUtil.isEmpty(userQuerys)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(userQuerys, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(USERQUERYTABLE).set(
					USERQUERYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					USERQUERYTABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					USERQUERYTABLE.MODULE_NAME.value(new JdbcNamedParameter("moduleName")),
					USERQUERYTABLE.USERQUERY_TITLE.value(new JdbcNamedParameter("userqueryTitle")),
					USERQUERYTABLE.USERQUERY_FORM.value(new JdbcNamedParameter("userqueryForm")),
					USERQUERYTABLE.USERQUERY_SQLCONDITION.value(new JdbcNamedParameter("userquerySqlcondition"))).where(
				USERQUERYTABLE.USERQUERY_ID.eq(new JdbcNamedParameter("userqueryId")));
			}
		});
	}

	public int[] batchDelete(List<UserQuery> userQuerys) {
		if (CollectionUtil.isEmpty(userQuerys)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(userQuerys, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(USERQUERYTABLE).where(and(
				USERQUERYTABLE.USERQUERY_ID.eq(new JdbcNamedParameter("userqueryId")),
				USERQUERYTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				USERQUERYTABLE.USER_ACCOUNT.eq(new JdbcNamedParameter("userAccount")),
				USERQUERYTABLE.MODULE_NAME.eq(new JdbcNamedParameter("moduleName")),
				USERQUERYTABLE.USERQUERY_TITLE.eq(new JdbcNamedParameter("userqueryTitle")),
				USERQUERYTABLE.USERQUERY_FORM.eq(new JdbcNamedParameter("userqueryForm")),
				USERQUERYTABLE.USERQUERY_SQLCONDITION.eq(new JdbcNamedParameter("userquerySqlcondition"))));
			}
		});
	}

}
