/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.common.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.common.constant.UserRoleTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.common.pojo.UserRole;
import org.tinygroup.sdpm.common.inter.UserRoleDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class UserRoleDaoImpl extends TinyDslDaoSupport implements UserRoleDao {

	public UserRole insertObject(UserRole userRole) {
		return getDslTemplate().insertObject(userRole, new InsertGenerateCallback<UserRole>() {
			public Insert generate(UserRole t) {
				Insert insert = insertInto(USERROLETABLE).values(
					USERROLETABLE.USER_ROLE_ID.value(t.getUserRoleId()),
					USERROLETABLE.COMPANY_ID.value(t.getCompanyId()),
					USERROLETABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERROLETABLE.ROLE_ID.value(t.getRoleId()));
				return insert;
			}
		});
	}

	public UserRole insertObject(boolean autoGeneratedKeys ,UserRole userRole) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,userRole, new InsertGenerateCallback<UserRole>() {

			public Insert generate(UserRole t) {
				Insert insert = insertInto(USERROLETABLE).values(
					USERROLETABLE.USER_ROLE_ID.value(t.getUserRoleId()),
					USERROLETABLE.COMPANY_ID.value(t.getCompanyId()),
					USERROLETABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERROLETABLE.ROLE_ID.value(t.getRoleId()));
				return insert;
			}
		});
	}

	public int updateObject(UserRole userRole) {
		return getDslTemplate().updateObject(userRole, new UpdateGenerateCallback<UserRole>() {
			public Update generate(UserRole t) {
				Update update = update(USERROLETABLE).set(
					USERROLETABLE.COMPANY_ID.value(t.getCompanyId()),
					USERROLETABLE.USER_ACCOUNT.value(t.getUserAccount()),
					USERROLETABLE.ROLE_ID.value(t.getRoleId())).where(
					USERROLETABLE.USER_ROLE_ID.eq(t.getUserRoleId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(USERROLETABLE).where(USERROLETABLE.USER_ROLE_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(USERROLETABLE).where(USERROLETABLE.USER_ROLE_ID.in(t));
		}
		},pks);
	}

	public UserRole getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, UserRole.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(USERROLETABLE).where(USERROLETABLE.USER_ROLE_ID.eq(t));
			}
		});
	}

	public List<UserRole> queryObjects(UserRole userRole) {
		if(userRole==null){
			userRole=new UserRole();
		}
		return getDslTemplate().queryObjects(userRole, new SelectGenerateCallback<UserRole>() {

			@SuppressWarnings("rawtypes")
			public Select generate(UserRole t) {
				return selectFrom(USERROLETABLE).where(
				and(
					USERROLETABLE.COMPANY_ID.eq(t.getCompanyId()),
					USERROLETABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					USERROLETABLE.ROLE_ID.eq(t.getRoleId())));
			}
		});
	}

	public Pager<UserRole> queryObjectsForPage(int start,int limit ,UserRole userRole) {
		if(userRole==null){
			userRole=new UserRole();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, userRole, false, new SelectGenerateCallback<UserRole>() {

			public Select generate(UserRole t) {
				return MysqlSelect.selectFrom(USERROLETABLE).where(
				and(
					USERROLETABLE.COMPANY_ID.eq(t.getCompanyId()),
					USERROLETABLE.USER_ACCOUNT.eq(t.getUserAccount()),
					USERROLETABLE.ROLE_ID.eq(t.getRoleId())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<UserRole> userRoles) {
		if (CollectionUtil.isEmpty(userRoles)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, userRoles, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(USERROLETABLE).values(
					USERROLETABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					USERROLETABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					USERROLETABLE.ROLE_ID.value(new JdbcNamedParameter("roleId")));
			}
		});
	}

	public int[] batchInsert(List<UserRole> userRoles){
			return batchInsert(true ,userRoles);
	}

	public int[] batchUpdate(List<UserRole> userRoles) {
		if (CollectionUtil.isEmpty(userRoles)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(userRoles, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(USERROLETABLE).set(
					USERROLETABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					USERROLETABLE.USER_ACCOUNT.value(new JdbcNamedParameter("userAccount")),
					USERROLETABLE.ROLE_ID.value(new JdbcNamedParameter("roleId"))).where(
				USERROLETABLE.USER_ROLE_ID.eq(new JdbcNamedParameter("userRoleId")));
			}
		});
	}

	public int[] batchDelete(List<UserRole> userRoles) {
		if (CollectionUtil.isEmpty(userRoles)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(userRoles, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(USERROLETABLE).where(and(
				USERROLETABLE.USER_ROLE_ID.eq(new JdbcNamedParameter("userRoleId")),
				USERROLETABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				USERROLETABLE.USER_ACCOUNT.eq(new JdbcNamedParameter("userAccount")),
				USERROLETABLE.ROLE_ID.eq(new JdbcNamedParameter("roleId"))));
			}
		});
	}

}
