/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.quality.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.quality.constant.TestRunTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.quality.pojo.TestRun;
import org.tinygroup.sdpm.quality.inter.TestRunDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class TestRunDaoImpl extends TinyDslDaoSupport implements TestRunDao {

	public TestRun insertObject(TestRun testRun) {
		return getDslTemplate().insertObject(testRun, new InsertGenerateCallback<TestRun>() {
			public Insert generate(TestRun t) {
				Insert insert = insertInto(TESTRUNTABLE).values(
					TESTRUNTABLE.TESTRUN_ID.value(t.getTestrunId()),
					TESTRUNTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRUNTABLE.TESTPLAN_ID.value(t.getTestplanId()),
					TESTRUNTABLE.CASE_ID.value(t.getCaseId()),
					TESTRUNTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.value(t.getTestrunAssignedTo()),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.value(t.getTestrunLastRunner()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.value(t.getTestrunLastRunDate()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.value(t.getTestrunLastRunResult()),
					TESTRUNTABLE.TESTRUN_STATUS.value(t.getTestrunStatus()));
				return insert;
			}
		});
	}

	public TestRun insertObject(boolean autoGeneratedKeys ,TestRun testRun) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,testRun, new InsertGenerateCallback<TestRun>() {

			public Insert generate(TestRun t) {
				Insert insert = insertInto(TESTRUNTABLE).values(
					TESTRUNTABLE.TESTRUN_ID.value(t.getTestrunId()),
					TESTRUNTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRUNTABLE.TESTPLAN_ID.value(t.getTestplanId()),
					TESTRUNTABLE.CASE_ID.value(t.getCaseId()),
					TESTRUNTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.value(t.getTestrunAssignedTo()),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.value(t.getTestrunLastRunner()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.value(t.getTestrunLastRunDate()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.value(t.getTestrunLastRunResult()),
					TESTRUNTABLE.TESTRUN_STATUS.value(t.getTestrunStatus()));
				return insert;
			}
		});
	}

	public int updateObject(TestRun testRun) {
		return getDslTemplate().updateObject(testRun, new UpdateGenerateCallback<TestRun>() {
			public Update generate(TestRun t) {
				Update update = update(TESTRUNTABLE).set(
					TESTRUNTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRUNTABLE.TESTPLAN_ID.value(t.getTestplanId()),
					TESTRUNTABLE.CASE_ID.value(t.getCaseId()),
					TESTRUNTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.value(t.getTestrunAssignedTo()),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.value(t.getTestrunLastRunner()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.value(t.getTestrunLastRunDate()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.value(t.getTestrunLastRunResult()),
					TESTRUNTABLE.TESTRUN_STATUS.value(t.getTestrunStatus())).where(
					TESTRUNTABLE.TESTRUN_ID.eq(t.getTestrunId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(TESTRUNTABLE).where(TESTRUNTABLE.TESTRUN_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(TESTRUNTABLE).where(TESTRUNTABLE.TESTRUN_ID.in(t));
		}
		},pks);
	}

	public TestRun getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, TestRun.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(TESTRUNTABLE).where(TESTRUNTABLE.TESTRUN_ID.eq(t));
			}
		});
	}

	public List<TestRun> queryObjects(TestRun testRun) {
		if(testRun==null){
			testRun=new TestRun();
		}
		return getDslTemplate().queryObjects(testRun, new SelectGenerateCallback<TestRun>() {

			@SuppressWarnings("rawtypes")
			public Select generate(TestRun t) {
				return selectFrom(TESTRUNTABLE).where(
				and(
					TESTRUNTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTRUNTABLE.TESTPLAN_ID.eq(t.getTestplanId()),
					TESTRUNTABLE.CASE_ID.eq(t.getCaseId()),
					TESTRUNTABLE.CASE_VERSION.eq(t.getCaseVersion()),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.eq(t.getTestrunAssignedTo()),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.eq(t.getTestrunLastRunner()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.eq(t.getTestrunLastRunDate()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.eq(t.getTestrunLastRunResult()),
					TESTRUNTABLE.TESTRUN_STATUS.eq(t.getTestrunStatus())));
			}
		});
	}

	public Pager<TestRun> queryObjectsForPage(int start,int limit ,TestRun testRun) {
		if(testRun==null){
			testRun=new TestRun();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, testRun, false, new SelectGenerateCallback<TestRun>() {

			public Select generate(TestRun t) {
				return MysqlSelect.selectFrom(TESTRUNTABLE).where(
				and(
					TESTRUNTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTRUNTABLE.TESTPLAN_ID.eq(t.getTestplanId()),
					TESTRUNTABLE.CASE_ID.eq(t.getCaseId()),
					TESTRUNTABLE.CASE_VERSION.eq(t.getCaseVersion()),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.eq(t.getTestrunAssignedTo()),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.eq(t.getTestrunLastRunner()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.eq(t.getTestrunLastRunDate()),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.eq(t.getTestrunLastRunResult()),
					TESTRUNTABLE.TESTRUN_STATUS.eq(t.getTestrunStatus())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<TestRun> testRuns) {
		if (CollectionUtil.isEmpty(testRuns)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, testRuns, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(TESTRUNTABLE).values(
					TESTRUNTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTRUNTABLE.TESTPLAN_ID.value(new JdbcNamedParameter("testplanId")),
					TESTRUNTABLE.CASE_ID.value(new JdbcNamedParameter("caseId")),
					TESTRUNTABLE.CASE_VERSION.value(new JdbcNamedParameter("caseVersion")),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.value(new JdbcNamedParameter("testrunAssignedTo")),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.value(new JdbcNamedParameter("testrunLastRunner")),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.value(new JdbcNamedParameter("testrunLastRunDate")),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.value(new JdbcNamedParameter("testrunLastRunResult")),
					TESTRUNTABLE.TESTRUN_STATUS.value(new JdbcNamedParameter("testrunStatus")));
			}
		});
	}

	public int[] batchInsert(List<TestRun> testRuns){
			return batchInsert(true ,testRuns);
	}

	public int[] batchUpdate(List<TestRun> testRuns) {
		if (CollectionUtil.isEmpty(testRuns)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(testRuns, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(TESTRUNTABLE).set(
					TESTRUNTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTRUNTABLE.TESTPLAN_ID.value(new JdbcNamedParameter("testplanId")),
					TESTRUNTABLE.CASE_ID.value(new JdbcNamedParameter("caseId")),
					TESTRUNTABLE.CASE_VERSION.value(new JdbcNamedParameter("caseVersion")),
					TESTRUNTABLE.TESTRUN_ASSIGNED_TO.value(new JdbcNamedParameter("testrunAssignedTo")),
					TESTRUNTABLE.TESTRUN_LAST_RUNNER.value(new JdbcNamedParameter("testrunLastRunner")),
					TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.value(new JdbcNamedParameter("testrunLastRunDate")),
					TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.value(new JdbcNamedParameter("testrunLastRunResult")),
					TESTRUNTABLE.TESTRUN_STATUS.value(new JdbcNamedParameter("testrunStatus"))).where(
				TESTRUNTABLE.TESTRUN_ID.eq(new JdbcNamedParameter("testrunId")));
			}
		});
	}

	public int[] batchDelete(List<TestRun> testRuns) {
		if (CollectionUtil.isEmpty(testRuns)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(testRuns, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(TESTRUNTABLE).where(and(
				TESTRUNTABLE.TESTRUN_ID.eq(new JdbcNamedParameter("testrunId")),
				TESTRUNTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				TESTRUNTABLE.TESTPLAN_ID.eq(new JdbcNamedParameter("testplanId")),
				TESTRUNTABLE.CASE_ID.eq(new JdbcNamedParameter("caseId")),
				TESTRUNTABLE.CASE_VERSION.eq(new JdbcNamedParameter("caseVersion")),
				TESTRUNTABLE.TESTRUN_ASSIGNED_TO.eq(new JdbcNamedParameter("testrunAssignedTo")),
				TESTRUNTABLE.TESTRUN_LAST_RUNNER.eq(new JdbcNamedParameter("testrunLastRunner")),
				TESTRUNTABLE.TESTRUN_LAST_RUN_DATE.eq(new JdbcNamedParameter("testrunLastRunDate")),
				TESTRUNTABLE.TESTRUN_LAST_RUN_RESULT.eq(new JdbcNamedParameter("testrunLastRunResult")),
				TESTRUNTABLE.TESTRUN_STATUS.eq(new JdbcNamedParameter("testrunStatus"))));
			}
		});
	}

}
