/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.quality.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.quality.constant.TestResultTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.quality.pojo.TestResult;
import org.tinygroup.sdpm.quality.inter.TestResultDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class TestResultDaoImpl extends TinyDslDaoSupport implements TestResultDao {

	public TestResult insertObject(TestResult testResult) {
		return getDslTemplate().insertObject(testResult, new InsertGenerateCallback<TestResult>() {
			public Insert generate(TestResult t) {
				Insert insert = insertInto(TESTRESULTTABLE).values(
					TESTRESULTTABLE.TEST_RESULT_ID.value(t.getTestResultId()),
					TESTRESULTTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRESULTTABLE.RUN_ID.value(t.getRunId()),
					TESTRESULTTABLE.CASE_ID.value(t.getCaseId()),
					TESTRESULTTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRESULTTABLE.CASE_RESULT.value(t.getCaseResult()),
					TESTRESULTTABLE.CASE_STEP_RESULTS.value(t.getCaseStepResults()),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.value(t.getTestResultLastRunner()),
					TESTRESULTTABLE.TEST_RESULT_DATE.value(t.getTestResultDate()));
				return insert;
			}
		});
	}

	public TestResult insertObject(boolean autoGeneratedKeys ,TestResult testResult) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,testResult, new InsertGenerateCallback<TestResult>() {

			public Insert generate(TestResult t) {
				Insert insert = insertInto(TESTRESULTTABLE).values(
					TESTRESULTTABLE.TEST_RESULT_ID.value(t.getTestResultId()),
					TESTRESULTTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRESULTTABLE.RUN_ID.value(t.getRunId()),
					TESTRESULTTABLE.CASE_ID.value(t.getCaseId()),
					TESTRESULTTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRESULTTABLE.CASE_RESULT.value(t.getCaseResult()),
					TESTRESULTTABLE.CASE_STEP_RESULTS.value(t.getCaseStepResults()),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.value(t.getTestResultLastRunner()),
					TESTRESULTTABLE.TEST_RESULT_DATE.value(t.getTestResultDate()));
				return insert;
			}
		});
	}

	public int updateObject(TestResult testResult) {
		return getDslTemplate().updateObject(testResult, new UpdateGenerateCallback<TestResult>() {
			public Update generate(TestResult t) {
				Update update = update(TESTRESULTTABLE).set(
					TESTRESULTTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTRESULTTABLE.RUN_ID.value(t.getRunId()),
					TESTRESULTTABLE.CASE_ID.value(t.getCaseId()),
					TESTRESULTTABLE.CASE_VERSION.value(t.getCaseVersion()),
					TESTRESULTTABLE.CASE_RESULT.value(t.getCaseResult()),
					TESTRESULTTABLE.CASE_STEP_RESULTS.value(t.getCaseStepResults()),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.value(t.getTestResultLastRunner()),
					TESTRESULTTABLE.TEST_RESULT_DATE.value(t.getTestResultDate())).where(
					TESTRESULTTABLE.TEST_RESULT_ID.eq(t.getTestResultId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(TESTRESULTTABLE).where(TESTRESULTTABLE.TEST_RESULT_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(TESTRESULTTABLE).where(TESTRESULTTABLE.TEST_RESULT_ID.in(t));
		}
		},pks);
	}

	public TestResult getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, TestResult.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(TESTRESULTTABLE).where(TESTRESULTTABLE.TEST_RESULT_ID.eq(t));
			}
		});
	}

	public List<TestResult> queryObjects(TestResult testResult) {
		if(testResult==null){
			testResult=new TestResult();
		}
		return getDslTemplate().queryObjects(testResult, new SelectGenerateCallback<TestResult>() {

			@SuppressWarnings("rawtypes")
			public Select generate(TestResult t) {
				return selectFrom(TESTRESULTTABLE).where(
				and(
					TESTRESULTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTRESULTTABLE.RUN_ID.eq(t.getRunId()),
					TESTRESULTTABLE.CASE_ID.eq(t.getCaseId()),
					TESTRESULTTABLE.CASE_VERSION.eq(t.getCaseVersion()),
					TESTRESULTTABLE.CASE_RESULT.eq(t.getCaseResult()),
					TESTRESULTTABLE.CASE_STEP_RESULTS.eq(t.getCaseStepResults()),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.eq(t.getTestResultLastRunner()),
					TESTRESULTTABLE.TEST_RESULT_DATE.eq(t.getTestResultDate())));
			}
		});
	}

	public Pager<TestResult> queryObjectsForPage(int start,int limit ,TestResult testResult) {
		if(testResult==null){
			testResult=new TestResult();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, testResult, false, new SelectGenerateCallback<TestResult>() {

			public Select generate(TestResult t) {
				return MysqlSelect.selectFrom(TESTRESULTTABLE).where(
				and(
					TESTRESULTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTRESULTTABLE.RUN_ID.eq(t.getRunId()),
					TESTRESULTTABLE.CASE_ID.eq(t.getCaseId()),
					TESTRESULTTABLE.CASE_VERSION.eq(t.getCaseVersion()),
					TESTRESULTTABLE.CASE_RESULT.eq(t.getCaseResult()),
					TESTRESULTTABLE.CASE_STEP_RESULTS.eq(t.getCaseStepResults()),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.eq(t.getTestResultLastRunner()),
					TESTRESULTTABLE.TEST_RESULT_DATE.eq(t.getTestResultDate())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<TestResult> testResults) {
		if (CollectionUtil.isEmpty(testResults)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, testResults, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(TESTRESULTTABLE).values(
					TESTRESULTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTRESULTTABLE.RUN_ID.value(new JdbcNamedParameter("runId")),
					TESTRESULTTABLE.CASE_ID.value(new JdbcNamedParameter("caseId")),
					TESTRESULTTABLE.CASE_VERSION.value(new JdbcNamedParameter("caseVersion")),
					TESTRESULTTABLE.CASE_RESULT.value(new JdbcNamedParameter("caseResult")),
					TESTRESULTTABLE.CASE_STEP_RESULTS.value(new JdbcNamedParameter("caseStepResults")),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.value(new JdbcNamedParameter("testResultLastRunner")),
					TESTRESULTTABLE.TEST_RESULT_DATE.value(new JdbcNamedParameter("testResultDate")));
			}
		});
	}

	public int[] batchInsert(List<TestResult> testResults){
			return batchInsert(true ,testResults);
	}

	public int[] batchUpdate(List<TestResult> testResults) {
		if (CollectionUtil.isEmpty(testResults)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(testResults, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(TESTRESULTTABLE).set(
					TESTRESULTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTRESULTTABLE.RUN_ID.value(new JdbcNamedParameter("runId")),
					TESTRESULTTABLE.CASE_ID.value(new JdbcNamedParameter("caseId")),
					TESTRESULTTABLE.CASE_VERSION.value(new JdbcNamedParameter("caseVersion")),
					TESTRESULTTABLE.CASE_RESULT.value(new JdbcNamedParameter("caseResult")),
					TESTRESULTTABLE.CASE_STEP_RESULTS.value(new JdbcNamedParameter("caseStepResults")),
					TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.value(new JdbcNamedParameter("testResultLastRunner")),
					TESTRESULTTABLE.TEST_RESULT_DATE.value(new JdbcNamedParameter("testResultDate"))).where(
				TESTRESULTTABLE.TEST_RESULT_ID.eq(new JdbcNamedParameter("testResultId")));
			}
		});
	}

	public int[] batchDelete(List<TestResult> testResults) {
		if (CollectionUtil.isEmpty(testResults)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(testResults, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(TESTRESULTTABLE).where(and(
				TESTRESULTTABLE.TEST_RESULT_ID.eq(new JdbcNamedParameter("testResultId")),
				TESTRESULTTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				TESTRESULTTABLE.RUN_ID.eq(new JdbcNamedParameter("runId")),
				TESTRESULTTABLE.CASE_ID.eq(new JdbcNamedParameter("caseId")),
				TESTRESULTTABLE.CASE_VERSION.eq(new JdbcNamedParameter("caseVersion")),
				TESTRESULTTABLE.CASE_RESULT.eq(new JdbcNamedParameter("caseResult")),
				TESTRESULTTABLE.CASE_STEP_RESULTS.eq(new JdbcNamedParameter("caseStepResults")),
				TESTRESULTTABLE.TEST_RESULT_LAST_RUNNER.eq(new JdbcNamedParameter("testResultLastRunner")),
				TESTRESULTTABLE.TEST_RESULT_DATE.eq(new JdbcNamedParameter("testResultDate"))));
			}
		});
	}

}
