/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.quality.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.quality.constant.TestPlanTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.quality.pojo.TestPlan;
import org.tinygroup.sdpm.quality.inter.TestPlanDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class TestPlanDaoImpl extends TinyDslDaoSupport implements TestPlanDao {

	public TestPlan insertObject(TestPlan testPlan) {
		return getDslTemplate().insertObject(testPlan, new InsertGenerateCallback<TestPlan>() {
			public Insert generate(TestPlan t) {
				Insert insert = insertInto(TESTPLANTABLE).values(
					TESTPLANTABLE.TESTPLAN_ID.value(t.getTestplanId()),
					TESTPLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTPLANTABLE.TESTPLAN_NAME.value(t.getTestplanName()),
					TESTPLANTABLE.PRODUCT_ID.value(t.getProductId()),
					TESTPLANTABLE.PROJECT_ID.value(t.getProjectId()),
					TESTPLANTABLE.BUILD_ID.value(t.getBuildId()),
					TESTPLANTABLE.TESTPLAN_OWNER.value(t.getTestplanOwner()),
					TESTPLANTABLE.TESTPLAN_BEGIN.value(t.getTestplanBegin()),
					TESTPLANTABLE.TESTPLAN_END.value(t.getTestplanEnd()),
					TESTPLANTABLE.TESTPLAN_DESC.value(t.getTestplanDesc()),
					TESTPLANTABLE.TESTPLAN_STATUS.value(t.getTestplanStatus()),
					TESTPLANTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public TestPlan insertObject(boolean autoGeneratedKeys ,TestPlan testPlan) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,testPlan, new InsertGenerateCallback<TestPlan>() {

			public Insert generate(TestPlan t) {
				Insert insert = insertInto(TESTPLANTABLE).values(
					TESTPLANTABLE.TESTPLAN_ID.value(t.getTestplanId()),
					TESTPLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTPLANTABLE.TESTPLAN_NAME.value(t.getTestplanName()),
					TESTPLANTABLE.PRODUCT_ID.value(t.getProductId()),
					TESTPLANTABLE.PROJECT_ID.value(t.getProjectId()),
					TESTPLANTABLE.BUILD_ID.value(t.getBuildId()),
					TESTPLANTABLE.TESTPLAN_OWNER.value(t.getTestplanOwner()),
					TESTPLANTABLE.TESTPLAN_BEGIN.value(t.getTestplanBegin()),
					TESTPLANTABLE.TESTPLAN_END.value(t.getTestplanEnd()),
					TESTPLANTABLE.TESTPLAN_DESC.value(t.getTestplanDesc()),
					TESTPLANTABLE.TESTPLAN_STATUS.value(t.getTestplanStatus()),
					TESTPLANTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(TestPlan testPlan) {
		return getDslTemplate().updateObject(testPlan, new UpdateGenerateCallback<TestPlan>() {
			public Update generate(TestPlan t) {
				Update update = update(TESTPLANTABLE).set(
					TESTPLANTABLE.COMPANY_ID.value(t.getCompanyId()),
					TESTPLANTABLE.TESTPLAN_NAME.value(t.getTestplanName()),
					TESTPLANTABLE.PRODUCT_ID.value(t.getProductId()),
					TESTPLANTABLE.PROJECT_ID.value(t.getProjectId()),
					TESTPLANTABLE.BUILD_ID.value(t.getBuildId()),
					TESTPLANTABLE.TESTPLAN_OWNER.value(t.getTestplanOwner()),
					TESTPLANTABLE.TESTPLAN_BEGIN.value(t.getTestplanBegin()),
					TESTPLANTABLE.TESTPLAN_END.value(t.getTestplanEnd()),
					TESTPLANTABLE.TESTPLAN_DESC.value(t.getTestplanDesc()),
					TESTPLANTABLE.TESTPLAN_STATUS.value(t.getTestplanStatus()),
					TESTPLANTABLE.DELETED.value(t.getDeleted())).where(
					TESTPLANTABLE.TESTPLAN_ID.eq(t.getTestplanId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(TESTPLANTABLE).where(TESTPLANTABLE.TESTPLAN_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(TESTPLANTABLE).where(TESTPLANTABLE.TESTPLAN_ID.in(t));
		}
		},pks);
	}

	public TestPlan getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, TestPlan.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(TESTPLANTABLE).where(TESTPLANTABLE.TESTPLAN_ID.eq(t));
			}
		});
	}

	public List<TestPlan> queryObjects(TestPlan testPlan) {
		if(testPlan==null){
			testPlan=new TestPlan();
		}
		return getDslTemplate().queryObjects(testPlan, new SelectGenerateCallback<TestPlan>() {

			@SuppressWarnings("rawtypes")
			public Select generate(TestPlan t) {
				return selectFrom(TESTPLANTABLE).where(
				and(
					TESTPLANTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTPLANTABLE.TESTPLAN_NAME.eq(t.getTestplanName()),
					TESTPLANTABLE.PRODUCT_ID.eq(t.getProductId()),
					TESTPLANTABLE.PROJECT_ID.eq(t.getProjectId()),
					TESTPLANTABLE.BUILD_ID.eq(t.getBuildId()),
					TESTPLANTABLE.TESTPLAN_OWNER.eq(t.getTestplanOwner()),
					TESTPLANTABLE.TESTPLAN_BEGIN.eq(t.getTestplanBegin()),
					TESTPLANTABLE.TESTPLAN_END.eq(t.getTestplanEnd()),
					TESTPLANTABLE.TESTPLAN_DESC.eq(t.getTestplanDesc()),
					TESTPLANTABLE.TESTPLAN_STATUS.eq(t.getTestplanStatus()),
					TESTPLANTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<TestPlan> queryObjectsForPage(int start,int limit ,TestPlan testPlan) {
		if(testPlan==null){
			testPlan=new TestPlan();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, testPlan, false, new SelectGenerateCallback<TestPlan>() {

			public Select generate(TestPlan t) {
				return MysqlSelect.selectFrom(TESTPLANTABLE).where(
				and(
					TESTPLANTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TESTPLANTABLE.TESTPLAN_NAME.eq(t.getTestplanName()),
					TESTPLANTABLE.PRODUCT_ID.eq(t.getProductId()),
					TESTPLANTABLE.PROJECT_ID.eq(t.getProjectId()),
					TESTPLANTABLE.BUILD_ID.eq(t.getBuildId()),
					TESTPLANTABLE.TESTPLAN_OWNER.eq(t.getTestplanOwner()),
					TESTPLANTABLE.TESTPLAN_BEGIN.eq(t.getTestplanBegin()),
					TESTPLANTABLE.TESTPLAN_END.eq(t.getTestplanEnd()),
					TESTPLANTABLE.TESTPLAN_DESC.eq(t.getTestplanDesc()),
					TESTPLANTABLE.TESTPLAN_STATUS.eq(t.getTestplanStatus()),
					TESTPLANTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<TestPlan> testPlans) {
		if (CollectionUtil.isEmpty(testPlans)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, testPlans, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(TESTPLANTABLE).values(
					TESTPLANTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTPLANTABLE.TESTPLAN_NAME.value(new JdbcNamedParameter("testplanName")),
					TESTPLANTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					TESTPLANTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					TESTPLANTABLE.BUILD_ID.value(new JdbcNamedParameter("buildId")),
					TESTPLANTABLE.TESTPLAN_OWNER.value(new JdbcNamedParameter("testplanOwner")),
					TESTPLANTABLE.TESTPLAN_BEGIN.value(new JdbcNamedParameter("testplanBegin")),
					TESTPLANTABLE.TESTPLAN_END.value(new JdbcNamedParameter("testplanEnd")),
					TESTPLANTABLE.TESTPLAN_DESC.value(new JdbcNamedParameter("testplanDesc")),
					TESTPLANTABLE.TESTPLAN_STATUS.value(new JdbcNamedParameter("testplanStatus")),
					TESTPLANTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<TestPlan> testPlans){
			return batchInsert(true ,testPlans);
	}

	public int[] batchUpdate(List<TestPlan> testPlans) {
		if (CollectionUtil.isEmpty(testPlans)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(testPlans, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(TESTPLANTABLE).set(
					TESTPLANTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TESTPLANTABLE.TESTPLAN_NAME.value(new JdbcNamedParameter("testplanName")),
					TESTPLANTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					TESTPLANTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					TESTPLANTABLE.BUILD_ID.value(new JdbcNamedParameter("buildId")),
					TESTPLANTABLE.TESTPLAN_OWNER.value(new JdbcNamedParameter("testplanOwner")),
					TESTPLANTABLE.TESTPLAN_BEGIN.value(new JdbcNamedParameter("testplanBegin")),
					TESTPLANTABLE.TESTPLAN_END.value(new JdbcNamedParameter("testplanEnd")),
					TESTPLANTABLE.TESTPLAN_DESC.value(new JdbcNamedParameter("testplanDesc")),
					TESTPLANTABLE.TESTPLAN_STATUS.value(new JdbcNamedParameter("testplanStatus")),
					TESTPLANTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				TESTPLANTABLE.TESTPLAN_ID.eq(new JdbcNamedParameter("testplanId")));
			}
		});
	}

	public int[] batchDelete(List<TestPlan> testPlans) {
		if (CollectionUtil.isEmpty(testPlans)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(testPlans, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(TESTPLANTABLE).where(and(
				TESTPLANTABLE.TESTPLAN_ID.eq(new JdbcNamedParameter("testplanId")),
				TESTPLANTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				TESTPLANTABLE.TESTPLAN_NAME.eq(new JdbcNamedParameter("testplanName")),
				TESTPLANTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				TESTPLANTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				TESTPLANTABLE.BUILD_ID.eq(new JdbcNamedParameter("buildId")),
				TESTPLANTABLE.TESTPLAN_OWNER.eq(new JdbcNamedParameter("testplanOwner")),
				TESTPLANTABLE.TESTPLAN_BEGIN.eq(new JdbcNamedParameter("testplanBegin")),
				TESTPLANTABLE.TESTPLAN_END.eq(new JdbcNamedParameter("testplanEnd")),
				TESTPLANTABLE.TESTPLAN_DESC.eq(new JdbcNamedParameter("testplanDesc")),
				TESTPLANTABLE.TESTPLAN_STATUS.eq(new JdbcNamedParameter("testplanStatus")),
				TESTPLANTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
