/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.project.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.project.constant.BuildTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.project.pojo.Build;
import org.tinygroup.sdpm.project.inter.BuildDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class BuildDaoImpl extends TinyDslDaoSupport implements BuildDao {

	public Build insertObject(Build build) {
		return getDslTemplate().insertObject(build, new InsertGenerateCallback<Build>() {
			public Insert generate(Build t) {
				Insert insert = insertInto(BUILDTABLE).values(
					BUILDTABLE.BUILD_ID.value(t.getBuildId()),
					BUILDTABLE.COMPANY_ID.value(t.getCompanyId()),
					BUILDTABLE.PRODUCT_ID.value(t.getProductId()),
					BUILDTABLE.PROJECT_ID.value(t.getProjectId()),
					BUILDTABLE.BUILD_NAME.value(t.getBuildName()),
					BUILDTABLE.BUILD_SPEC.value(t.getBuildSpec()),
					BUILDTABLE.BUILD_SCM_PATH.value(t.getBuildScmPath()),
					BUILDTABLE.BUILD_FILE_PATH.value(t.getBuildFilePath()),
					BUILDTABLE.BUILD_DATE.value(t.getBuildDate()),
					BUILDTABLE.BUILDER.value(t.getBuilder()),
					BUILDTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Build insertObject(boolean autoGeneratedKeys ,Build build) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,build, new InsertGenerateCallback<Build>() {

			public Insert generate(Build t) {
				Insert insert = insertInto(BUILDTABLE).values(
					BUILDTABLE.BUILD_ID.value(t.getBuildId()),
					BUILDTABLE.COMPANY_ID.value(t.getCompanyId()),
					BUILDTABLE.PRODUCT_ID.value(t.getProductId()),
					BUILDTABLE.PROJECT_ID.value(t.getProjectId()),
					BUILDTABLE.BUILD_NAME.value(t.getBuildName()),
					BUILDTABLE.BUILD_SPEC.value(t.getBuildSpec()),
					BUILDTABLE.BUILD_SCM_PATH.value(t.getBuildScmPath()),
					BUILDTABLE.BUILD_FILE_PATH.value(t.getBuildFilePath()),
					BUILDTABLE.BUILD_DATE.value(t.getBuildDate()),
					BUILDTABLE.BUILDER.value(t.getBuilder()),
					BUILDTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Build build) {
		return getDslTemplate().updateObject(build, new UpdateGenerateCallback<Build>() {
			public Update generate(Build t) {
				Update update = update(BUILDTABLE).set(
					BUILDTABLE.COMPANY_ID.value(t.getCompanyId()),
					BUILDTABLE.PRODUCT_ID.value(t.getProductId()),
					BUILDTABLE.PROJECT_ID.value(t.getProjectId()),
					BUILDTABLE.BUILD_NAME.value(t.getBuildName()),
					BUILDTABLE.BUILD_SPEC.value(t.getBuildSpec()),
					BUILDTABLE.BUILD_SCM_PATH.value(t.getBuildScmPath()),
					BUILDTABLE.BUILD_FILE_PATH.value(t.getBuildFilePath()),
					BUILDTABLE.BUILD_DATE.value(t.getBuildDate()),
					BUILDTABLE.BUILDER.value(t.getBuilder()),
					BUILDTABLE.DELETED.value(t.getDeleted())).where(
					BUILDTABLE.BUILD_ID.eq(t.getBuildId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(BUILDTABLE).where(BUILDTABLE.BUILD_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(BUILDTABLE).where(BUILDTABLE.BUILD_ID.in(t));
		}
		},pks);
	}

	public Build getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Build.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(BUILDTABLE).where(BUILDTABLE.BUILD_ID.eq(t));
			}
		});
	}

	public List<Build> queryObjects(Build build) {
		if(build==null){
			build=new Build();
		}
		return getDslTemplate().queryObjects(build, new SelectGenerateCallback<Build>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Build t) {
				return selectFrom(BUILDTABLE).where(
				and(
					BUILDTABLE.COMPANY_ID.eq(t.getCompanyId()),
					BUILDTABLE.PRODUCT_ID.eq(t.getProductId()),
					BUILDTABLE.PROJECT_ID.eq(t.getProjectId()),
					BUILDTABLE.BUILD_NAME.eq(t.getBuildName()),
					BUILDTABLE.BUILD_SPEC.eq(t.getBuildSpec()),
					BUILDTABLE.BUILD_SCM_PATH.eq(t.getBuildScmPath()),
					BUILDTABLE.BUILD_FILE_PATH.eq(t.getBuildFilePath()),
					BUILDTABLE.BUILD_DATE.eq(t.getBuildDate()),
					BUILDTABLE.BUILDER.eq(t.getBuilder()),
					BUILDTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Build> queryObjectsForPage(int start,int limit ,Build build) {
		if(build==null){
			build=new Build();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, build, false, new SelectGenerateCallback<Build>() {

			public Select generate(Build t) {
				return MysqlSelect.selectFrom(BUILDTABLE).where(
				and(
					BUILDTABLE.COMPANY_ID.eq(t.getCompanyId()),
					BUILDTABLE.PRODUCT_ID.eq(t.getProductId()),
					BUILDTABLE.PROJECT_ID.eq(t.getProjectId()),
					BUILDTABLE.BUILD_NAME.eq(t.getBuildName()),
					BUILDTABLE.BUILD_SPEC.eq(t.getBuildSpec()),
					BUILDTABLE.BUILD_SCM_PATH.eq(t.getBuildScmPath()),
					BUILDTABLE.BUILD_FILE_PATH.eq(t.getBuildFilePath()),
					BUILDTABLE.BUILD_DATE.eq(t.getBuildDate()),
					BUILDTABLE.BUILDER.eq(t.getBuilder()),
					BUILDTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Build> builds) {
		if (CollectionUtil.isEmpty(builds)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, builds, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(BUILDTABLE).values(
					BUILDTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					BUILDTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					BUILDTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					BUILDTABLE.BUILD_NAME.value(new JdbcNamedParameter("buildName")),
					BUILDTABLE.BUILD_SPEC.value(new JdbcNamedParameter("buildSpec")),
					BUILDTABLE.BUILD_SCM_PATH.value(new JdbcNamedParameter("buildScmPath")),
					BUILDTABLE.BUILD_FILE_PATH.value(new JdbcNamedParameter("buildFilePath")),
					BUILDTABLE.BUILD_DATE.value(new JdbcNamedParameter("buildDate")),
					BUILDTABLE.BUILDER.value(new JdbcNamedParameter("builder")),
					BUILDTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Build> builds){
			return batchInsert(true ,builds);
	}

	public int[] batchUpdate(List<Build> builds) {
		if (CollectionUtil.isEmpty(builds)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(builds, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(BUILDTABLE).set(
					BUILDTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					BUILDTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					BUILDTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					BUILDTABLE.BUILD_NAME.value(new JdbcNamedParameter("buildName")),
					BUILDTABLE.BUILD_SPEC.value(new JdbcNamedParameter("buildSpec")),
					BUILDTABLE.BUILD_SCM_PATH.value(new JdbcNamedParameter("buildScmPath")),
					BUILDTABLE.BUILD_FILE_PATH.value(new JdbcNamedParameter("buildFilePath")),
					BUILDTABLE.BUILD_DATE.value(new JdbcNamedParameter("buildDate")),
					BUILDTABLE.BUILDER.value(new JdbcNamedParameter("builder")),
					BUILDTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				BUILDTABLE.BUILD_ID.eq(new JdbcNamedParameter("buildId")));
			}
		});
	}

	public int[] batchDelete(List<Build> builds) {
		if (CollectionUtil.isEmpty(builds)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(builds, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(BUILDTABLE).where(and(
				BUILDTABLE.BUILD_ID.eq(new JdbcNamedParameter("buildId")),
				BUILDTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				BUILDTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				BUILDTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				BUILDTABLE.BUILD_NAME.eq(new JdbcNamedParameter("buildName")),
				BUILDTABLE.BUILD_SPEC.eq(new JdbcNamedParameter("buildSpec")),
				BUILDTABLE.BUILD_SCM_PATH.eq(new JdbcNamedParameter("buildScmPath")),
				BUILDTABLE.BUILD_FILE_PATH.eq(new JdbcNamedParameter("buildFilePath")),
				BUILDTABLE.BUILD_DATE.eq(new JdbcNamedParameter("buildDate")),
				BUILDTABLE.BUILDER.eq(new JdbcNamedParameter("builder")),
				BUILDTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
