/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.project.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.project.constant.ProjectStoryTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.project.pojo.ProjectStory;
import org.tinygroup.sdpm.project.inter.ProjectStoryDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class ProjectStoryDaoImpl extends TinyDslDaoSupport implements ProjectStoryDao {

	public ProjectStory insertObject(ProjectStory projectStory) {
		return getDslTemplate().insertObject(projectStory, new InsertGenerateCallback<ProjectStory>() {
			public Insert generate(ProjectStory t) {
				Insert insert = insertInto(PROJECTSTORYTABLE).values(
					PROJECTSTORYTABLE.PROJECT_STORY_ID.value(t.getProjectStoryId()),
					PROJECTSTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTSTORYTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTSTORYTABLE.PRODUCT_ID.value(t.getProductId()),
					PROJECTSTORYTABLE.STORY_ID.value(t.getStoryId()),
					PROJECTSTORYTABLE.STORY_VERSION.value(t.getStoryVersion()));
				return insert;
			}
		});
	}

	public ProjectStory insertObject(boolean autoGeneratedKeys ,ProjectStory projectStory) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,projectStory, new InsertGenerateCallback<ProjectStory>() {

			public Insert generate(ProjectStory t) {
				Insert insert = insertInto(PROJECTSTORYTABLE).values(
					PROJECTSTORYTABLE.PROJECT_STORY_ID.value(t.getProjectStoryId()),
					PROJECTSTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTSTORYTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTSTORYTABLE.PRODUCT_ID.value(t.getProductId()),
					PROJECTSTORYTABLE.STORY_ID.value(t.getStoryId()),
					PROJECTSTORYTABLE.STORY_VERSION.value(t.getStoryVersion()));
				return insert;
			}
		});
	}

	public int updateObject(ProjectStory projectStory) {
		return getDslTemplate().updateObject(projectStory, new UpdateGenerateCallback<ProjectStory>() {
			public Update generate(ProjectStory t) {
				Update update = update(PROJECTSTORYTABLE).set(
					PROJECTSTORYTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTSTORYTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTSTORYTABLE.PRODUCT_ID.value(t.getProductId()),
					PROJECTSTORYTABLE.STORY_ID.value(t.getStoryId()),
					PROJECTSTORYTABLE.STORY_VERSION.value(t.getStoryVersion())).where(
					PROJECTSTORYTABLE.PROJECT_STORY_ID.eq(t.getProjectStoryId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(PROJECTSTORYTABLE).where(PROJECTSTORYTABLE.PROJECT_STORY_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(PROJECTSTORYTABLE).where(PROJECTSTORYTABLE.PROJECT_STORY_ID.in(t));
		}
		},pks);
	}

	public ProjectStory getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, ProjectStory.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(PROJECTSTORYTABLE).where(PROJECTSTORYTABLE.PROJECT_STORY_ID.eq(t));
			}
		});
	}

	public List<ProjectStory> queryObjects(ProjectStory projectStory) {
		if(projectStory==null){
			projectStory=new ProjectStory();
		}
		return getDslTemplate().queryObjects(projectStory, new SelectGenerateCallback<ProjectStory>() {

			@SuppressWarnings("rawtypes")
			public Select generate(ProjectStory t) {
				return selectFrom(PROJECTSTORYTABLE).where(
				and(
					PROJECTSTORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PROJECTSTORYTABLE.PROJECT_ID.eq(t.getProjectId()),
					PROJECTSTORYTABLE.PRODUCT_ID.eq(t.getProductId()),
					PROJECTSTORYTABLE.STORY_ID.eq(t.getStoryId()),
					PROJECTSTORYTABLE.STORY_VERSION.eq(t.getStoryVersion())));
			}
		});
	}

	public Pager<ProjectStory> queryObjectsForPage(int start,int limit ,ProjectStory projectStory) {
		if(projectStory==null){
			projectStory=new ProjectStory();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, projectStory, false, new SelectGenerateCallback<ProjectStory>() {

			public Select generate(ProjectStory t) {
				return MysqlSelect.selectFrom(PROJECTSTORYTABLE).where(
				and(
					PROJECTSTORYTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PROJECTSTORYTABLE.PROJECT_ID.eq(t.getProjectId()),
					PROJECTSTORYTABLE.PRODUCT_ID.eq(t.getProductId()),
					PROJECTSTORYTABLE.STORY_ID.eq(t.getStoryId()),
					PROJECTSTORYTABLE.STORY_VERSION.eq(t.getStoryVersion())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<ProjectStory> projectStorys) {
		if (CollectionUtil.isEmpty(projectStorys)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, projectStorys, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(PROJECTSTORYTABLE).values(
					PROJECTSTORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PROJECTSTORYTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					PROJECTSTORYTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					PROJECTSTORYTABLE.STORY_ID.value(new JdbcNamedParameter("storyId")),
					PROJECTSTORYTABLE.STORY_VERSION.value(new JdbcNamedParameter("storyVersion")));
			}
		});
	}

	public int[] batchInsert(List<ProjectStory> projectStorys){
			return batchInsert(true ,projectStorys);
	}

	public int[] batchUpdate(List<ProjectStory> projectStorys) {
		if (CollectionUtil.isEmpty(projectStorys)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(projectStorys, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(PROJECTSTORYTABLE).set(
					PROJECTSTORYTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PROJECTSTORYTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					PROJECTSTORYTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")),
					PROJECTSTORYTABLE.STORY_ID.value(new JdbcNamedParameter("storyId")),
					PROJECTSTORYTABLE.STORY_VERSION.value(new JdbcNamedParameter("storyVersion"))).where(
				PROJECTSTORYTABLE.PROJECT_STORY_ID.eq(new JdbcNamedParameter("projectStoryId")));
			}
		});
	}

	public int[] batchDelete(List<ProjectStory> projectStorys) {
		if (CollectionUtil.isEmpty(projectStorys)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(projectStorys, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(PROJECTSTORYTABLE).where(and(
				PROJECTSTORYTABLE.PROJECT_STORY_ID.eq(new JdbcNamedParameter("projectStoryId")),
				PROJECTSTORYTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				PROJECTSTORYTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				PROJECTSTORYTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId")),
				PROJECTSTORYTABLE.STORY_ID.eq(new JdbcNamedParameter("storyId")),
				PROJECTSTORYTABLE.STORY_VERSION.eq(new JdbcNamedParameter("storyVersion"))));
			}
		});
	}

}
