/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.project.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.project.constant.ProjectProductTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.project.pojo.ProjectProduct;
import org.tinygroup.sdpm.project.inter.ProjectProductDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class ProjectProductDaoImpl extends TinyDslDaoSupport implements ProjectProductDao {

	public ProjectProduct insertObject(ProjectProduct projectProduct) {
		return getDslTemplate().insertObject(projectProduct, new InsertGenerateCallback<ProjectProduct>() {
			public Insert generate(ProjectProduct t) {
				Insert insert = insertInto(PROJECTPRODUCTTABLE).values(
					PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.value(t.getProjectProductId()),
					PROJECTPRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTPRODUCTTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTPRODUCTTABLE.PRODUCT_ID.value(t.getProductId()));
				return insert;
			}
		});
	}

	public ProjectProduct insertObject(boolean autoGeneratedKeys ,ProjectProduct projectProduct) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,projectProduct, new InsertGenerateCallback<ProjectProduct>() {

			public Insert generate(ProjectProduct t) {
				Insert insert = insertInto(PROJECTPRODUCTTABLE).values(
					PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.value(t.getProjectProductId()),
					PROJECTPRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTPRODUCTTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTPRODUCTTABLE.PRODUCT_ID.value(t.getProductId()));
				return insert;
			}
		});
	}

	public int updateObject(ProjectProduct projectProduct) {
		return getDslTemplate().updateObject(projectProduct, new UpdateGenerateCallback<ProjectProduct>() {
			public Update generate(ProjectProduct t) {
				Update update = update(PROJECTPRODUCTTABLE).set(
					PROJECTPRODUCTTABLE.COMPANY_ID.value(t.getCompanyId()),
					PROJECTPRODUCTTABLE.PROJECT_ID.value(t.getProjectId()),
					PROJECTPRODUCTTABLE.PRODUCT_ID.value(t.getProductId())).where(
					PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.eq(t.getProjectProductId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(PROJECTPRODUCTTABLE).where(PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(PROJECTPRODUCTTABLE).where(PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.in(t));
		}
		},pks);
	}

	public ProjectProduct getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, ProjectProduct.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(PROJECTPRODUCTTABLE).where(PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.eq(t));
			}
		});
	}

	public List<ProjectProduct> queryObjects(ProjectProduct projectProduct) {
		if(projectProduct==null){
			projectProduct=new ProjectProduct();
		}
		return getDslTemplate().queryObjects(projectProduct, new SelectGenerateCallback<ProjectProduct>() {

			@SuppressWarnings("rawtypes")
			public Select generate(ProjectProduct t) {
				return selectFrom(PROJECTPRODUCTTABLE).where(
				and(
					PROJECTPRODUCTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PROJECTPRODUCTTABLE.PROJECT_ID.eq(t.getProjectId()),
					PROJECTPRODUCTTABLE.PRODUCT_ID.eq(t.getProductId())));
			}
		});
	}

	public Pager<ProjectProduct> queryObjectsForPage(int start,int limit ,ProjectProduct projectProduct) {
		if(projectProduct==null){
			projectProduct=new ProjectProduct();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, projectProduct, false, new SelectGenerateCallback<ProjectProduct>() {

			public Select generate(ProjectProduct t) {
				return MysqlSelect.selectFrom(PROJECTPRODUCTTABLE).where(
				and(
					PROJECTPRODUCTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					PROJECTPRODUCTTABLE.PROJECT_ID.eq(t.getProjectId()),
					PROJECTPRODUCTTABLE.PRODUCT_ID.eq(t.getProductId())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<ProjectProduct> projectProducts) {
		if (CollectionUtil.isEmpty(projectProducts)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, projectProducts, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(PROJECTPRODUCTTABLE).values(
					PROJECTPRODUCTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PROJECTPRODUCTTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					PROJECTPRODUCTTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId")));
			}
		});
	}

	public int[] batchInsert(List<ProjectProduct> projectProducts){
			return batchInsert(true ,projectProducts);
	}

	public int[] batchUpdate(List<ProjectProduct> projectProducts) {
		if (CollectionUtil.isEmpty(projectProducts)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(projectProducts, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(PROJECTPRODUCTTABLE).set(
					PROJECTPRODUCTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					PROJECTPRODUCTTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					PROJECTPRODUCTTABLE.PRODUCT_ID.value(new JdbcNamedParameter("productId"))).where(
				PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.eq(new JdbcNamedParameter("projectProductId")));
			}
		});
	}

	public int[] batchDelete(List<ProjectProduct> projectProducts) {
		if (CollectionUtil.isEmpty(projectProducts)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(projectProducts, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(PROJECTPRODUCTTABLE).where(and(
				PROJECTPRODUCTTABLE.PROJECT_PRODUCT_ID.eq(new JdbcNamedParameter("projectProductId")),
				PROJECTPRODUCTTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				PROJECTPRODUCTTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				PROJECTPRODUCTTABLE.PRODUCT_ID.eq(new JdbcNamedParameter("productId"))));
			}
		});
	}

}
