/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.project.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.project.constant.TaskTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.project.pojo.Task;
import org.tinygroup.sdpm.project.inter.TaskDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class TaskDaoImpl extends TinyDslDaoSupport implements TaskDao {

	public Task insertObject(Task task) {
		return getDslTemplate().insertObject(task, new InsertGenerateCallback<Task>() {
			public Insert generate(Task t) {
				Insert insert = insertInto(TASKTABLE).values(
					TASKTABLE.TASK_ID.value(t.getTaskId()),
					TASKTABLE.COMPANY_ID.value(t.getCompanyId()),
					TASKTABLE.PROJECT_ID.value(t.getProjectId()),
					TASKTABLE.MODULE_ID.value(t.getModuleId()),
					TASKTABLE.TASK_NAME.value(t.getTaskName()),
					TASKTABLE.TASK_TYPE.value(t.getTaskType()),
					TASKTABLE.TASK_PRI.value(t.getTaskPri()),
					TASKTABLE.TASK_ESTIMATE.value(t.getTaskEstimate()),
					TASKTABLE.TASK_CONSUMED.value(t.getTaskConsumed()),
					TASKTABLE.TASK_LEFT.value(t.getTaskLeft()),
					TASKTABLE.TASK_DEADLINE.value(t.getTaskDeadline()),
					TASKTABLE.TASK_STATUS.value(t.getTaskStatus()),
					TASKTABLE.TASK_MAILTO.value(t.getTaskMailto()),
					TASKTABLE.TASK_DESC.value(t.getTaskDesc()),
					TASKTABLE.TASK_OPEN_COUNT.value(t.getTaskOpenCount()),
					TASKTABLE.TASK_OPENED_BY.value(t.getTaskOpenedBy()),
					TASKTABLE.TASK_OPENED_DATE.value(t.getTaskOpenedDate()),
					TASKTABLE.TASK_ASSIGNED_TO.value(t.getTaskAssignedTo()),
					TASKTABLE.TASK_ASSIGNED_DATE.value(t.getTaskAssignedDate()),
					TASKTABLE.TASK_EST_STARTED.value(t.getTaskEstStarted()),
					TASKTABLE.TASK_REAL_STARTED.value(t.getTaskRealStarted()),
					TASKTABLE.TASK_FINISHED_BY.value(t.getTaskFinishedBy()),
					TASKTABLE.TASK_FINISHED_DATE.value(t.getTaskFinishedDate()),
					TASKTABLE.TASK_CANCELED_BY.value(t.getTaskCanceledBy()),
					TASKTABLE.TASK_CANCELED_DATE.value(t.getTaskCanceledDate()),
					TASKTABLE.TASK_CLOSED_BY.value(t.getTaskClosedBy()),
					TASKTABLE.TASK_CLOSED_DATE.value(t.getTaskClosedDate()),
					TASKTABLE.TASK_CLOSED_REASON.value(t.getTaskClosedReason()),
					TASKTABLE.TASK_LAST_EDITED_BY.value(t.getTaskLastEditedBy()),
					TASKTABLE.TASK_LAST_EDITED_DATE.value(t.getTaskLastEditedDate()),
					TASKTABLE.TASK_F_S.value(t.getTaskFS()),
					TASKTABLE.TASK_S_S.value(t.getTaskSS()),
					TASKTABLE.TASK_F_F.value(t.getTaskFF()),
					TASKTABLE.TASK_S_F.value(t.getTaskSF()),
					TASKTABLE.REQUEST_ID.value(t.getRequestId()),
					TASKTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Task insertObject(boolean autoGeneratedKeys ,Task task) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,task, new InsertGenerateCallback<Task>() {

			public Insert generate(Task t) {
				Insert insert = insertInto(TASKTABLE).values(
					TASKTABLE.TASK_ID.value(t.getTaskId()),
					TASKTABLE.COMPANY_ID.value(t.getCompanyId()),
					TASKTABLE.PROJECT_ID.value(t.getProjectId()),
					TASKTABLE.MODULE_ID.value(t.getModuleId()),
					TASKTABLE.TASK_NAME.value(t.getTaskName()),
					TASKTABLE.TASK_TYPE.value(t.getTaskType()),
					TASKTABLE.TASK_PRI.value(t.getTaskPri()),
					TASKTABLE.TASK_ESTIMATE.value(t.getTaskEstimate()),
					TASKTABLE.TASK_CONSUMED.value(t.getTaskConsumed()),
					TASKTABLE.TASK_LEFT.value(t.getTaskLeft()),
					TASKTABLE.TASK_DEADLINE.value(t.getTaskDeadline()),
					TASKTABLE.TASK_STATUS.value(t.getTaskStatus()),
					TASKTABLE.TASK_MAILTO.value(t.getTaskMailto()),
					TASKTABLE.TASK_DESC.value(t.getTaskDesc()),
					TASKTABLE.TASK_OPEN_COUNT.value(t.getTaskOpenCount()),
					TASKTABLE.TASK_OPENED_BY.value(t.getTaskOpenedBy()),
					TASKTABLE.TASK_OPENED_DATE.value(t.getTaskOpenedDate()),
					TASKTABLE.TASK_ASSIGNED_TO.value(t.getTaskAssignedTo()),
					TASKTABLE.TASK_ASSIGNED_DATE.value(t.getTaskAssignedDate()),
					TASKTABLE.TASK_EST_STARTED.value(t.getTaskEstStarted()),
					TASKTABLE.TASK_REAL_STARTED.value(t.getTaskRealStarted()),
					TASKTABLE.TASK_FINISHED_BY.value(t.getTaskFinishedBy()),
					TASKTABLE.TASK_FINISHED_DATE.value(t.getTaskFinishedDate()),
					TASKTABLE.TASK_CANCELED_BY.value(t.getTaskCanceledBy()),
					TASKTABLE.TASK_CANCELED_DATE.value(t.getTaskCanceledDate()),
					TASKTABLE.TASK_CLOSED_BY.value(t.getTaskClosedBy()),
					TASKTABLE.TASK_CLOSED_DATE.value(t.getTaskClosedDate()),
					TASKTABLE.TASK_CLOSED_REASON.value(t.getTaskClosedReason()),
					TASKTABLE.TASK_LAST_EDITED_BY.value(t.getTaskLastEditedBy()),
					TASKTABLE.TASK_LAST_EDITED_DATE.value(t.getTaskLastEditedDate()),
					TASKTABLE.TASK_F_S.value(t.getTaskFS()),
					TASKTABLE.TASK_S_S.value(t.getTaskSS()),
					TASKTABLE.TASK_F_F.value(t.getTaskFF()),
					TASKTABLE.TASK_S_F.value(t.getTaskSF()),
					TASKTABLE.REQUEST_ID.value(t.getRequestId()),
					TASKTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Task task) {
		return getDslTemplate().updateObject(task, new UpdateGenerateCallback<Task>() {
			public Update generate(Task t) {
				Update update = update(TASKTABLE).set(
					TASKTABLE.COMPANY_ID.value(t.getCompanyId()),
					TASKTABLE.PROJECT_ID.value(t.getProjectId()),
					TASKTABLE.MODULE_ID.value(t.getModuleId()),
					TASKTABLE.TASK_NAME.value(t.getTaskName()),
					TASKTABLE.TASK_TYPE.value(t.getTaskType()),
					TASKTABLE.TASK_PRI.value(t.getTaskPri()),
					TASKTABLE.TASK_ESTIMATE.value(t.getTaskEstimate()),
					TASKTABLE.TASK_CONSUMED.value(t.getTaskConsumed()),
					TASKTABLE.TASK_LEFT.value(t.getTaskLeft()),
					TASKTABLE.TASK_DEADLINE.value(t.getTaskDeadline()),
					TASKTABLE.TASK_STATUS.value(t.getTaskStatus()),
					TASKTABLE.TASK_MAILTO.value(t.getTaskMailto()),
					TASKTABLE.TASK_DESC.value(t.getTaskDesc()),
					TASKTABLE.TASK_OPEN_COUNT.value(t.getTaskOpenCount()),
					TASKTABLE.TASK_OPENED_BY.value(t.getTaskOpenedBy()),
					TASKTABLE.TASK_OPENED_DATE.value(t.getTaskOpenedDate()),
					TASKTABLE.TASK_ASSIGNED_TO.value(t.getTaskAssignedTo()),
					TASKTABLE.TASK_ASSIGNED_DATE.value(t.getTaskAssignedDate()),
					TASKTABLE.TASK_EST_STARTED.value(t.getTaskEstStarted()),
					TASKTABLE.TASK_REAL_STARTED.value(t.getTaskRealStarted()),
					TASKTABLE.TASK_FINISHED_BY.value(t.getTaskFinishedBy()),
					TASKTABLE.TASK_FINISHED_DATE.value(t.getTaskFinishedDate()),
					TASKTABLE.TASK_CANCELED_BY.value(t.getTaskCanceledBy()),
					TASKTABLE.TASK_CANCELED_DATE.value(t.getTaskCanceledDate()),
					TASKTABLE.TASK_CLOSED_BY.value(t.getTaskClosedBy()),
					TASKTABLE.TASK_CLOSED_DATE.value(t.getTaskClosedDate()),
					TASKTABLE.TASK_CLOSED_REASON.value(t.getTaskClosedReason()),
					TASKTABLE.TASK_LAST_EDITED_BY.value(t.getTaskLastEditedBy()),
					TASKTABLE.TASK_LAST_EDITED_DATE.value(t.getTaskLastEditedDate()),
					TASKTABLE.TASK_F_S.value(t.getTaskFS()),
					TASKTABLE.TASK_S_S.value(t.getTaskSS()),
					TASKTABLE.TASK_F_F.value(t.getTaskFF()),
					TASKTABLE.TASK_S_F.value(t.getTaskSF()),
					TASKTABLE.REQUEST_ID.value(t.getRequestId()),
					TASKTABLE.DELETED.value(t.getDeleted())).where(
					TASKTABLE.TASK_ID.eq(t.getTaskId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(TASKTABLE).where(TASKTABLE.TASK_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(TASKTABLE).where(TASKTABLE.TASK_ID.in(t));
		}
		},pks);
	}

	public Task getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Task.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(TASKTABLE).where(TASKTABLE.TASK_ID.eq(t));
			}
		});
	}

	public List<Task> queryObjects(Task task) {
		if(task==null){
			task=new Task();
		}
		return getDslTemplate().queryObjects(task, new SelectGenerateCallback<Task>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Task t) {
				return selectFrom(TASKTABLE).where(
				and(
					TASKTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TASKTABLE.PROJECT_ID.eq(t.getProjectId()),
					TASKTABLE.MODULE_ID.eq(t.getModuleId()),
					TASKTABLE.TASK_NAME.eq(t.getTaskName()),
					TASKTABLE.TASK_TYPE.eq(t.getTaskType()),
					TASKTABLE.TASK_PRI.eq(t.getTaskPri()),
					TASKTABLE.TASK_ESTIMATE.eq(t.getTaskEstimate()),
					TASKTABLE.TASK_CONSUMED.eq(t.getTaskConsumed()),
					TASKTABLE.TASK_LEFT.eq(t.getTaskLeft()),
					TASKTABLE.TASK_DEADLINE.eq(t.getTaskDeadline()),
					TASKTABLE.TASK_STATUS.eq(t.getTaskStatus()),
					TASKTABLE.TASK_MAILTO.eq(t.getTaskMailto()),
					TASKTABLE.TASK_DESC.eq(t.getTaskDesc()),
					TASKTABLE.TASK_OPEN_COUNT.eq(t.getTaskOpenCount()),
					TASKTABLE.TASK_OPENED_BY.eq(t.getTaskOpenedBy()),
					TASKTABLE.TASK_OPENED_DATE.eq(t.getTaskOpenedDate()),
					TASKTABLE.TASK_ASSIGNED_TO.eq(t.getTaskAssignedTo()),
					TASKTABLE.TASK_ASSIGNED_DATE.eq(t.getTaskAssignedDate()),
					TASKTABLE.TASK_EST_STARTED.eq(t.getTaskEstStarted()),
					TASKTABLE.TASK_REAL_STARTED.eq(t.getTaskRealStarted()),
					TASKTABLE.TASK_FINISHED_BY.eq(t.getTaskFinishedBy()),
					TASKTABLE.TASK_FINISHED_DATE.eq(t.getTaskFinishedDate()),
					TASKTABLE.TASK_CANCELED_BY.eq(t.getTaskCanceledBy()),
					TASKTABLE.TASK_CANCELED_DATE.eq(t.getTaskCanceledDate()),
					TASKTABLE.TASK_CLOSED_BY.eq(t.getTaskClosedBy()),
					TASKTABLE.TASK_CLOSED_DATE.eq(t.getTaskClosedDate()),
					TASKTABLE.TASK_CLOSED_REASON.eq(t.getTaskClosedReason()),
					TASKTABLE.TASK_LAST_EDITED_BY.eq(t.getTaskLastEditedBy()),
					TASKTABLE.TASK_LAST_EDITED_DATE.eq(t.getTaskLastEditedDate()),
					TASKTABLE.TASK_F_S.eq(t.getTaskFS()),
					TASKTABLE.TASK_S_S.eq(t.getTaskSS()),
					TASKTABLE.TASK_F_F.eq(t.getTaskFF()),
					TASKTABLE.TASK_S_F.eq(t.getTaskSF()),
					TASKTABLE.REQUEST_ID.eq(t.getRequestId()),
					TASKTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Task> queryObjectsForPage(int start,int limit ,Task task) {
		if(task==null){
			task=new Task();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, task, false, new SelectGenerateCallback<Task>() {

			public Select generate(Task t) {
				return MysqlSelect.selectFrom(TASKTABLE).where(
				and(
					TASKTABLE.COMPANY_ID.eq(t.getCompanyId()),
					TASKTABLE.PROJECT_ID.eq(t.getProjectId()),
					TASKTABLE.MODULE_ID.eq(t.getModuleId()),
					TASKTABLE.TASK_NAME.eq(t.getTaskName()),
					TASKTABLE.TASK_TYPE.eq(t.getTaskType()),
					TASKTABLE.TASK_PRI.eq(t.getTaskPri()),
					TASKTABLE.TASK_ESTIMATE.eq(t.getTaskEstimate()),
					TASKTABLE.TASK_CONSUMED.eq(t.getTaskConsumed()),
					TASKTABLE.TASK_LEFT.eq(t.getTaskLeft()),
					TASKTABLE.TASK_DEADLINE.eq(t.getTaskDeadline()),
					TASKTABLE.TASK_STATUS.eq(t.getTaskStatus()),
					TASKTABLE.TASK_MAILTO.eq(t.getTaskMailto()),
					TASKTABLE.TASK_DESC.eq(t.getTaskDesc()),
					TASKTABLE.TASK_OPEN_COUNT.eq(t.getTaskOpenCount()),
					TASKTABLE.TASK_OPENED_BY.eq(t.getTaskOpenedBy()),
					TASKTABLE.TASK_OPENED_DATE.eq(t.getTaskOpenedDate()),
					TASKTABLE.TASK_ASSIGNED_TO.eq(t.getTaskAssignedTo()),
					TASKTABLE.TASK_ASSIGNED_DATE.eq(t.getTaskAssignedDate()),
					TASKTABLE.TASK_EST_STARTED.eq(t.getTaskEstStarted()),
					TASKTABLE.TASK_REAL_STARTED.eq(t.getTaskRealStarted()),
					TASKTABLE.TASK_FINISHED_BY.eq(t.getTaskFinishedBy()),
					TASKTABLE.TASK_FINISHED_DATE.eq(t.getTaskFinishedDate()),
					TASKTABLE.TASK_CANCELED_BY.eq(t.getTaskCanceledBy()),
					TASKTABLE.TASK_CANCELED_DATE.eq(t.getTaskCanceledDate()),
					TASKTABLE.TASK_CLOSED_BY.eq(t.getTaskClosedBy()),
					TASKTABLE.TASK_CLOSED_DATE.eq(t.getTaskClosedDate()),
					TASKTABLE.TASK_CLOSED_REASON.eq(t.getTaskClosedReason()),
					TASKTABLE.TASK_LAST_EDITED_BY.eq(t.getTaskLastEditedBy()),
					TASKTABLE.TASK_LAST_EDITED_DATE.eq(t.getTaskLastEditedDate()),
					TASKTABLE.TASK_F_S.eq(t.getTaskFS()),
					TASKTABLE.TASK_S_S.eq(t.getTaskSS()),
					TASKTABLE.TASK_F_F.eq(t.getTaskFF()),
					TASKTABLE.TASK_S_F.eq(t.getTaskSF()),
					TASKTABLE.REQUEST_ID.eq(t.getRequestId()),
					TASKTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Task> tasks) {
		if (CollectionUtil.isEmpty(tasks)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, tasks, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(TASKTABLE).values(
					TASKTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TASKTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					TASKTABLE.MODULE_ID.value(new JdbcNamedParameter("moduleId")),
					TASKTABLE.TASK_NAME.value(new JdbcNamedParameter("taskName")),
					TASKTABLE.TASK_TYPE.value(new JdbcNamedParameter("taskType")),
					TASKTABLE.TASK_PRI.value(new JdbcNamedParameter("taskPri")),
					TASKTABLE.TASK_ESTIMATE.value(new JdbcNamedParameter("taskEstimate")),
					TASKTABLE.TASK_CONSUMED.value(new JdbcNamedParameter("taskConsumed")),
					TASKTABLE.TASK_LEFT.value(new JdbcNamedParameter("taskLeft")),
					TASKTABLE.TASK_DEADLINE.value(new JdbcNamedParameter("taskDeadline")),
					TASKTABLE.TASK_STATUS.value(new JdbcNamedParameter("taskStatus")),
					TASKTABLE.TASK_MAILTO.value(new JdbcNamedParameter("taskMailto")),
					TASKTABLE.TASK_DESC.value(new JdbcNamedParameter("taskDesc")),
					TASKTABLE.TASK_OPEN_COUNT.value(new JdbcNamedParameter("taskOpenCount")),
					TASKTABLE.TASK_OPENED_BY.value(new JdbcNamedParameter("taskOpenedBy")),
					TASKTABLE.TASK_OPENED_DATE.value(new JdbcNamedParameter("taskOpenedDate")),
					TASKTABLE.TASK_ASSIGNED_TO.value(new JdbcNamedParameter("taskAssignedTo")),
					TASKTABLE.TASK_ASSIGNED_DATE.value(new JdbcNamedParameter("taskAssignedDate")),
					TASKTABLE.TASK_EST_STARTED.value(new JdbcNamedParameter("taskEstStarted")),
					TASKTABLE.TASK_REAL_STARTED.value(new JdbcNamedParameter("taskRealStarted")),
					TASKTABLE.TASK_FINISHED_BY.value(new JdbcNamedParameter("taskFinishedBy")),
					TASKTABLE.TASK_FINISHED_DATE.value(new JdbcNamedParameter("taskFinishedDate")),
					TASKTABLE.TASK_CANCELED_BY.value(new JdbcNamedParameter("taskCanceledBy")),
					TASKTABLE.TASK_CANCELED_DATE.value(new JdbcNamedParameter("taskCanceledDate")),
					TASKTABLE.TASK_CLOSED_BY.value(new JdbcNamedParameter("taskClosedBy")),
					TASKTABLE.TASK_CLOSED_DATE.value(new JdbcNamedParameter("taskClosedDate")),
					TASKTABLE.TASK_CLOSED_REASON.value(new JdbcNamedParameter("taskClosedReason")),
					TASKTABLE.TASK_LAST_EDITED_BY.value(new JdbcNamedParameter("taskLastEditedBy")),
					TASKTABLE.TASK_LAST_EDITED_DATE.value(new JdbcNamedParameter("taskLastEditedDate")),
					TASKTABLE.TASK_F_S.value(new JdbcNamedParameter("taskFS")),
					TASKTABLE.TASK_S_S.value(new JdbcNamedParameter("taskSS")),
					TASKTABLE.TASK_F_F.value(new JdbcNamedParameter("taskFF")),
					TASKTABLE.TASK_S_F.value(new JdbcNamedParameter("taskSF")),
					TASKTABLE.REQUEST_ID.value(new JdbcNamedParameter("requestId")),
					TASKTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Task> tasks){
			return batchInsert(true ,tasks);
	}

	public int[] batchUpdate(List<Task> tasks) {
		if (CollectionUtil.isEmpty(tasks)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(tasks, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(TASKTABLE).set(
					TASKTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					TASKTABLE.PROJECT_ID.value(new JdbcNamedParameter("projectId")),
					TASKTABLE.MODULE_ID.value(new JdbcNamedParameter("moduleId")),
					TASKTABLE.TASK_NAME.value(new JdbcNamedParameter("taskName")),
					TASKTABLE.TASK_TYPE.value(new JdbcNamedParameter("taskType")),
					TASKTABLE.TASK_PRI.value(new JdbcNamedParameter("taskPri")),
					TASKTABLE.TASK_ESTIMATE.value(new JdbcNamedParameter("taskEstimate")),
					TASKTABLE.TASK_CONSUMED.value(new JdbcNamedParameter("taskConsumed")),
					TASKTABLE.TASK_LEFT.value(new JdbcNamedParameter("taskLeft")),
					TASKTABLE.TASK_DEADLINE.value(new JdbcNamedParameter("taskDeadline")),
					TASKTABLE.TASK_STATUS.value(new JdbcNamedParameter("taskStatus")),
					TASKTABLE.TASK_MAILTO.value(new JdbcNamedParameter("taskMailto")),
					TASKTABLE.TASK_DESC.value(new JdbcNamedParameter("taskDesc")),
					TASKTABLE.TASK_OPEN_COUNT.value(new JdbcNamedParameter("taskOpenCount")),
					TASKTABLE.TASK_OPENED_BY.value(new JdbcNamedParameter("taskOpenedBy")),
					TASKTABLE.TASK_OPENED_DATE.value(new JdbcNamedParameter("taskOpenedDate")),
					TASKTABLE.TASK_ASSIGNED_TO.value(new JdbcNamedParameter("taskAssignedTo")),
					TASKTABLE.TASK_ASSIGNED_DATE.value(new JdbcNamedParameter("taskAssignedDate")),
					TASKTABLE.TASK_EST_STARTED.value(new JdbcNamedParameter("taskEstStarted")),
					TASKTABLE.TASK_REAL_STARTED.value(new JdbcNamedParameter("taskRealStarted")),
					TASKTABLE.TASK_FINISHED_BY.value(new JdbcNamedParameter("taskFinishedBy")),
					TASKTABLE.TASK_FINISHED_DATE.value(new JdbcNamedParameter("taskFinishedDate")),
					TASKTABLE.TASK_CANCELED_BY.value(new JdbcNamedParameter("taskCanceledBy")),
					TASKTABLE.TASK_CANCELED_DATE.value(new JdbcNamedParameter("taskCanceledDate")),
					TASKTABLE.TASK_CLOSED_BY.value(new JdbcNamedParameter("taskClosedBy")),
					TASKTABLE.TASK_CLOSED_DATE.value(new JdbcNamedParameter("taskClosedDate")),
					TASKTABLE.TASK_CLOSED_REASON.value(new JdbcNamedParameter("taskClosedReason")),
					TASKTABLE.TASK_LAST_EDITED_BY.value(new JdbcNamedParameter("taskLastEditedBy")),
					TASKTABLE.TASK_LAST_EDITED_DATE.value(new JdbcNamedParameter("taskLastEditedDate")),
					TASKTABLE.TASK_F_S.value(new JdbcNamedParameter("taskFS")),
					TASKTABLE.TASK_S_S.value(new JdbcNamedParameter("taskSS")),
					TASKTABLE.TASK_F_F.value(new JdbcNamedParameter("taskFF")),
					TASKTABLE.TASK_S_F.value(new JdbcNamedParameter("taskSF")),
					TASKTABLE.REQUEST_ID.value(new JdbcNamedParameter("requestId")),
					TASKTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				TASKTABLE.TASK_ID.eq(new JdbcNamedParameter("taskId")));
			}
		});
	}

	public int[] batchDelete(List<Task> tasks) {
		if (CollectionUtil.isEmpty(tasks)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(tasks, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(TASKTABLE).where(and(
				TASKTABLE.TASK_ID.eq(new JdbcNamedParameter("taskId")),
				TASKTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				TASKTABLE.PROJECT_ID.eq(new JdbcNamedParameter("projectId")),
				TASKTABLE.MODULE_ID.eq(new JdbcNamedParameter("moduleId")),
				TASKTABLE.TASK_NAME.eq(new JdbcNamedParameter("taskName")),
				TASKTABLE.TASK_TYPE.eq(new JdbcNamedParameter("taskType")),
				TASKTABLE.TASK_PRI.eq(new JdbcNamedParameter("taskPri")),
				TASKTABLE.TASK_ESTIMATE.eq(new JdbcNamedParameter("taskEstimate")),
				TASKTABLE.TASK_CONSUMED.eq(new JdbcNamedParameter("taskConsumed")),
				TASKTABLE.TASK_LEFT.eq(new JdbcNamedParameter("taskLeft")),
				TASKTABLE.TASK_DEADLINE.eq(new JdbcNamedParameter("taskDeadline")),
				TASKTABLE.TASK_STATUS.eq(new JdbcNamedParameter("taskStatus")),
				TASKTABLE.TASK_MAILTO.eq(new JdbcNamedParameter("taskMailto")),
				TASKTABLE.TASK_DESC.eq(new JdbcNamedParameter("taskDesc")),
				TASKTABLE.TASK_OPEN_COUNT.eq(new JdbcNamedParameter("taskOpenCount")),
				TASKTABLE.TASK_OPENED_BY.eq(new JdbcNamedParameter("taskOpenedBy")),
				TASKTABLE.TASK_OPENED_DATE.eq(new JdbcNamedParameter("taskOpenedDate")),
				TASKTABLE.TASK_ASSIGNED_TO.eq(new JdbcNamedParameter("taskAssignedTo")),
				TASKTABLE.TASK_ASSIGNED_DATE.eq(new JdbcNamedParameter("taskAssignedDate")),
				TASKTABLE.TASK_EST_STARTED.eq(new JdbcNamedParameter("taskEstStarted")),
				TASKTABLE.TASK_REAL_STARTED.eq(new JdbcNamedParameter("taskRealStarted")),
				TASKTABLE.TASK_FINISHED_BY.eq(new JdbcNamedParameter("taskFinishedBy")),
				TASKTABLE.TASK_FINISHED_DATE.eq(new JdbcNamedParameter("taskFinishedDate")),
				TASKTABLE.TASK_CANCELED_BY.eq(new JdbcNamedParameter("taskCanceledBy")),
				TASKTABLE.TASK_CANCELED_DATE.eq(new JdbcNamedParameter("taskCanceledDate")),
				TASKTABLE.TASK_CLOSED_BY.eq(new JdbcNamedParameter("taskClosedBy")),
				TASKTABLE.TASK_CLOSED_DATE.eq(new JdbcNamedParameter("taskClosedDate")),
				TASKTABLE.TASK_CLOSED_REASON.eq(new JdbcNamedParameter("taskClosedReason")),
				TASKTABLE.TASK_LAST_EDITED_BY.eq(new JdbcNamedParameter("taskLastEditedBy")),
				TASKTABLE.TASK_LAST_EDITED_DATE.eq(new JdbcNamedParameter("taskLastEditedDate")),
				TASKTABLE.TASK_F_S.eq(new JdbcNamedParameter("taskFS")),
				TASKTABLE.TASK_S_S.eq(new JdbcNamedParameter("taskSS")),
				TASKTABLE.TASK_F_F.eq(new JdbcNamedParameter("taskFF")),
				TASKTABLE.TASK_S_F.eq(new JdbcNamedParameter("taskSF")),
				TASKTABLE.REQUEST_ID.eq(new JdbcNamedParameter("requestId")),
				TASKTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
