/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.document.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.document.constant.AttachmentTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.document.pojo.Attachment;
import org.tinygroup.sdpm.document.inter.AttachmentDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class AttachmentDaoImpl extends TinyDslDaoSupport implements AttachmentDao {

	public Attachment insertObject(Attachment attachment) {
		return getDslTemplate().insertObject(attachment, new InsertGenerateCallback<Attachment>() {
			public Insert generate(Attachment t) {
				Insert insert = insertInto(ATTACHMENTTABLE).values(
					ATTACHMENTTABLE.FILE_ID.value(t.getFileId()),
					ATTACHMENTTABLE.COMPANY_ID.value(t.getCompanyId()),
					ATTACHMENTTABLE.FILE_PATHNAME.value(t.getFilePathname()),
					ATTACHMENTTABLE.FILE_TITLE.value(t.getFileTitle()),
					ATTACHMENTTABLE.FILE_EXTENSION.value(t.getFileExtension()),
					ATTACHMENTTABLE.FILE_SIZE.value(t.getFileSize()),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.value(t.getFileObjectType()),
					ATTACHMENTTABLE.FILE_OBJECT_ID.value(t.getFileObjectId()),
					ATTACHMENTTABLE.FILE_ADDED_BY.value(t.getFileAddedBy()),
					ATTACHMENTTABLE.FILE_ADDED_DATE.value(t.getFileAddedDate()),
					ATTACHMENTTABLE.FILE_DOWNLOADS.value(t.getFileDownloads()),
					ATTACHMENTTABLE.FILE_EXTRA.value(t.getFileExtra()),
					ATTACHMENTTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Attachment insertObject(boolean autoGeneratedKeys ,Attachment attachment) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,attachment, new InsertGenerateCallback<Attachment>() {

			public Insert generate(Attachment t) {
				Insert insert = insertInto(ATTACHMENTTABLE).values(
					ATTACHMENTTABLE.FILE_ID.value(t.getFileId()),
					ATTACHMENTTABLE.COMPANY_ID.value(t.getCompanyId()),
					ATTACHMENTTABLE.FILE_PATHNAME.value(t.getFilePathname()),
					ATTACHMENTTABLE.FILE_TITLE.value(t.getFileTitle()),
					ATTACHMENTTABLE.FILE_EXTENSION.value(t.getFileExtension()),
					ATTACHMENTTABLE.FILE_SIZE.value(t.getFileSize()),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.value(t.getFileObjectType()),
					ATTACHMENTTABLE.FILE_OBJECT_ID.value(t.getFileObjectId()),
					ATTACHMENTTABLE.FILE_ADDED_BY.value(t.getFileAddedBy()),
					ATTACHMENTTABLE.FILE_ADDED_DATE.value(t.getFileAddedDate()),
					ATTACHMENTTABLE.FILE_DOWNLOADS.value(t.getFileDownloads()),
					ATTACHMENTTABLE.FILE_EXTRA.value(t.getFileExtra()),
					ATTACHMENTTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Attachment attachment) {
		return getDslTemplate().updateObject(attachment, new UpdateGenerateCallback<Attachment>() {
			public Update generate(Attachment t) {
				Update update = update(ATTACHMENTTABLE).set(
					ATTACHMENTTABLE.COMPANY_ID.value(t.getCompanyId()),
					ATTACHMENTTABLE.FILE_PATHNAME.value(t.getFilePathname()),
					ATTACHMENTTABLE.FILE_TITLE.value(t.getFileTitle()),
					ATTACHMENTTABLE.FILE_EXTENSION.value(t.getFileExtension()),
					ATTACHMENTTABLE.FILE_SIZE.value(t.getFileSize()),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.value(t.getFileObjectType()),
					ATTACHMENTTABLE.FILE_OBJECT_ID.value(t.getFileObjectId()),
					ATTACHMENTTABLE.FILE_ADDED_BY.value(t.getFileAddedBy()),
					ATTACHMENTTABLE.FILE_ADDED_DATE.value(t.getFileAddedDate()),
					ATTACHMENTTABLE.FILE_DOWNLOADS.value(t.getFileDownloads()),
					ATTACHMENTTABLE.FILE_EXTRA.value(t.getFileExtra()),
					ATTACHMENTTABLE.DELETED.value(t.getDeleted())).where(
					ATTACHMENTTABLE.FILE_ID.eq(t.getFileId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(ATTACHMENTTABLE).where(ATTACHMENTTABLE.FILE_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(ATTACHMENTTABLE).where(ATTACHMENTTABLE.FILE_ID.in(t));
		}
		},pks);
	}

	public Attachment getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Attachment.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(ATTACHMENTTABLE).where(ATTACHMENTTABLE.FILE_ID.eq(t));
			}
		});
	}

	public List<Attachment> queryObjects(Attachment attachment) {
		if(attachment==null){
			attachment=new Attachment();
		}
		return getDslTemplate().queryObjects(attachment, new SelectGenerateCallback<Attachment>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Attachment t) {
				return selectFrom(ATTACHMENTTABLE).where(
				and(
					ATTACHMENTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					ATTACHMENTTABLE.FILE_PATHNAME.eq(t.getFilePathname()),
					ATTACHMENTTABLE.FILE_TITLE.eq(t.getFileTitle()),
					ATTACHMENTTABLE.FILE_EXTENSION.eq(t.getFileExtension()),
					ATTACHMENTTABLE.FILE_SIZE.eq(t.getFileSize()),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.eq(t.getFileObjectType()),
					ATTACHMENTTABLE.FILE_OBJECT_ID.eq(t.getFileObjectId()),
					ATTACHMENTTABLE.FILE_ADDED_BY.eq(t.getFileAddedBy()),
					ATTACHMENTTABLE.FILE_ADDED_DATE.eq(t.getFileAddedDate()),
					ATTACHMENTTABLE.FILE_DOWNLOADS.eq(t.getFileDownloads()),
					ATTACHMENTTABLE.FILE_EXTRA.eq(t.getFileExtra()),
					ATTACHMENTTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Attachment> queryObjectsForPage(int start,int limit ,Attachment attachment) {
		if(attachment==null){
			attachment=new Attachment();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, attachment, false, new SelectGenerateCallback<Attachment>() {

			public Select generate(Attachment t) {
				return MysqlSelect.selectFrom(ATTACHMENTTABLE).where(
				and(
					ATTACHMENTTABLE.COMPANY_ID.eq(t.getCompanyId()),
					ATTACHMENTTABLE.FILE_PATHNAME.eq(t.getFilePathname()),
					ATTACHMENTTABLE.FILE_TITLE.eq(t.getFileTitle()),
					ATTACHMENTTABLE.FILE_EXTENSION.eq(t.getFileExtension()),
					ATTACHMENTTABLE.FILE_SIZE.eq(t.getFileSize()),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.eq(t.getFileObjectType()),
					ATTACHMENTTABLE.FILE_OBJECT_ID.eq(t.getFileObjectId()),
					ATTACHMENTTABLE.FILE_ADDED_BY.eq(t.getFileAddedBy()),
					ATTACHMENTTABLE.FILE_ADDED_DATE.eq(t.getFileAddedDate()),
					ATTACHMENTTABLE.FILE_DOWNLOADS.eq(t.getFileDownloads()),
					ATTACHMENTTABLE.FILE_EXTRA.eq(t.getFileExtra()),
					ATTACHMENTTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Attachment> attachments) {
		if (CollectionUtil.isEmpty(attachments)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, attachments, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(ATTACHMENTTABLE).values(
					ATTACHMENTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					ATTACHMENTTABLE.FILE_PATHNAME.value(new JdbcNamedParameter("filePathname")),
					ATTACHMENTTABLE.FILE_TITLE.value(new JdbcNamedParameter("fileTitle")),
					ATTACHMENTTABLE.FILE_EXTENSION.value(new JdbcNamedParameter("fileExtension")),
					ATTACHMENTTABLE.FILE_SIZE.value(new JdbcNamedParameter("fileSize")),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.value(new JdbcNamedParameter("fileObjectType")),
					ATTACHMENTTABLE.FILE_OBJECT_ID.value(new JdbcNamedParameter("fileObjectId")),
					ATTACHMENTTABLE.FILE_ADDED_BY.value(new JdbcNamedParameter("fileAddedBy")),
					ATTACHMENTTABLE.FILE_ADDED_DATE.value(new JdbcNamedParameter("fileAddedDate")),
					ATTACHMENTTABLE.FILE_DOWNLOADS.value(new JdbcNamedParameter("fileDownloads")),
					ATTACHMENTTABLE.FILE_EXTRA.value(new JdbcNamedParameter("fileExtra")),
					ATTACHMENTTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Attachment> attachments){
			return batchInsert(true ,attachments);
	}

	public int[] batchUpdate(List<Attachment> attachments) {
		if (CollectionUtil.isEmpty(attachments)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(attachments, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(ATTACHMENTTABLE).set(
					ATTACHMENTTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					ATTACHMENTTABLE.FILE_PATHNAME.value(new JdbcNamedParameter("filePathname")),
					ATTACHMENTTABLE.FILE_TITLE.value(new JdbcNamedParameter("fileTitle")),
					ATTACHMENTTABLE.FILE_EXTENSION.value(new JdbcNamedParameter("fileExtension")),
					ATTACHMENTTABLE.FILE_SIZE.value(new JdbcNamedParameter("fileSize")),
					ATTACHMENTTABLE.FILE_OBJECT_TYPE.value(new JdbcNamedParameter("fileObjectType")),
					ATTACHMENTTABLE.FILE_OBJECT_ID.value(new JdbcNamedParameter("fileObjectId")),
					ATTACHMENTTABLE.FILE_ADDED_BY.value(new JdbcNamedParameter("fileAddedBy")),
					ATTACHMENTTABLE.FILE_ADDED_DATE.value(new JdbcNamedParameter("fileAddedDate")),
					ATTACHMENTTABLE.FILE_DOWNLOADS.value(new JdbcNamedParameter("fileDownloads")),
					ATTACHMENTTABLE.FILE_EXTRA.value(new JdbcNamedParameter("fileExtra")),
					ATTACHMENTTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				ATTACHMENTTABLE.FILE_ID.eq(new JdbcNamedParameter("fileId")));
			}
		});
	}

	public int[] batchDelete(List<Attachment> attachments) {
		if (CollectionUtil.isEmpty(attachments)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(attachments, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(ATTACHMENTTABLE).where(and(
				ATTACHMENTTABLE.FILE_ID.eq(new JdbcNamedParameter("fileId")),
				ATTACHMENTTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				ATTACHMENTTABLE.FILE_PATHNAME.eq(new JdbcNamedParameter("filePathname")),
				ATTACHMENTTABLE.FILE_TITLE.eq(new JdbcNamedParameter("fileTitle")),
				ATTACHMENTTABLE.FILE_EXTENSION.eq(new JdbcNamedParameter("fileExtension")),
				ATTACHMENTTABLE.FILE_SIZE.eq(new JdbcNamedParameter("fileSize")),
				ATTACHMENTTABLE.FILE_OBJECT_TYPE.eq(new JdbcNamedParameter("fileObjectType")),
				ATTACHMENTTABLE.FILE_OBJECT_ID.eq(new JdbcNamedParameter("fileObjectId")),
				ATTACHMENTTABLE.FILE_ADDED_BY.eq(new JdbcNamedParameter("fileAddedBy")),
				ATTACHMENTTABLE.FILE_ADDED_DATE.eq(new JdbcNamedParameter("fileAddedDate")),
				ATTACHMENTTABLE.FILE_DOWNLOADS.eq(new JdbcNamedParameter("fileDownloads")),
				ATTACHMENTTABLE.FILE_EXTRA.eq(new JdbcNamedParameter("fileExtra")),
				ATTACHMENTTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
