/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.sdpm.document.impl;

import static org.tinygroup.tinysqldsl.base.StatementSqlBuilder.and;
import static org.tinygroup.sdpm.document.constant.CommentsTable.*;
import static org.tinygroup.tinysqldsl.Select.*;
import static org.tinygroup.tinysqldsl.Insert.*;
import static org.tinygroup.tinysqldsl.Delete.*;
import static org.tinygroup.tinysqldsl.Update.*;

import java.io.Serializable;

import java.util.List;

import org.tinygroup.tinysqldsl.Delete;
import org.tinygroup.tinysqldsl.Insert;
import org.tinygroup.tinysqldsl.Select;
import org.tinygroup.tinysqldsl.Update;
import org.tinygroup.tinysqldsl.Pager;
import org.tinygroup.commons.tools.CollectionUtil;
import org.tinygroup.tinysqldsl.expression.JdbcNamedParameter;
import org.tinygroup.tinysqldsl.extend.MysqlSelect;
import org.tinygroup.sdpm.document.pojo.Comments;
import org.tinygroup.sdpm.document.inter.CommentsDao;
import org.tinygroup.jdbctemplatedslsession.daosupport.TinyDslDaoSupport;

import org.tinygroup.jdbctemplatedslsession.callback.DeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.InsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamDeleteGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamInsertGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.NoParamUpdateGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.SelectGenerateCallback;
import org.tinygroup.jdbctemplatedslsession.callback.UpdateGenerateCallback;

public class CommentsDaoImpl extends TinyDslDaoSupport implements CommentsDao {

	public Comments insertObject(Comments comments) {
		return getDslTemplate().insertObject(comments, new InsertGenerateCallback<Comments>() {
			public Insert generate(Comments t) {
				Insert insert = insertInto(COMMENTSTABLE).values(
					COMMENTSTABLE.COMMENT_ID.value(t.getCommentId()),
					COMMENTSTABLE.COMPANY_ID.value(t.getCompanyId()),
					COMMENTSTABLE.DOC_ID.value(t.getDocId()),
					COMMENTSTABLE.PARENT_ID.value(t.getParentId()),
					COMMENTSTABLE.COMMENT_TEXT.value(t.getCommentText()),
					COMMENTSTABLE.COMMENT_ADDED_BY.value(t.getCommentAddedBy()),
					COMMENTSTABLE.COMMENT_ADDED_DATE.value(t.getCommentAddedDate()),
					COMMENTSTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public Comments insertObject(boolean autoGeneratedKeys ,Comments comments) {
		return getDslTemplate().insertObjectAndReturnKey(autoGeneratedKeys ,comments, new InsertGenerateCallback<Comments>() {

			public Insert generate(Comments t) {
				Insert insert = insertInto(COMMENTSTABLE).values(
					COMMENTSTABLE.COMMENT_ID.value(t.getCommentId()),
					COMMENTSTABLE.COMPANY_ID.value(t.getCompanyId()),
					COMMENTSTABLE.DOC_ID.value(t.getDocId()),
					COMMENTSTABLE.PARENT_ID.value(t.getParentId()),
					COMMENTSTABLE.COMMENT_TEXT.value(t.getCommentText()),
					COMMENTSTABLE.COMMENT_ADDED_BY.value(t.getCommentAddedBy()),
					COMMENTSTABLE.COMMENT_ADDED_DATE.value(t.getCommentAddedDate()),
					COMMENTSTABLE.DELETED.value(t.getDeleted()));
				return insert;
			}
		});
	}

	public int updateObject(Comments comments) {
		return getDslTemplate().updateObject(comments, new UpdateGenerateCallback<Comments>() {
			public Update generate(Comments t) {
				Update update = update(COMMENTSTABLE).set(
					COMMENTSTABLE.COMPANY_ID.value(t.getCompanyId()),
					COMMENTSTABLE.DOC_ID.value(t.getDocId()),
					COMMENTSTABLE.PARENT_ID.value(t.getParentId()),
					COMMENTSTABLE.COMMENT_TEXT.value(t.getCommentText()),
					COMMENTSTABLE.COMMENT_ADDED_BY.value(t.getCommentAddedBy()),
					COMMENTSTABLE.COMMENT_ADDED_DATE.value(t.getCommentAddedDate()),
					COMMENTSTABLE.DELETED.value(t.getDeleted())).where(
					COMMENTSTABLE.COMMENT_ID.eq(t.getCommentId()));
				return update;
			}
		});
	}

	public int deleteObject(Serializable pk){
		return getDslTemplate().deleteObject(pk, new DeleteGenerateCallback<Serializable>() {
			public Delete generate(Serializable pk) {
				return delete(COMMENTSTABLE).where(COMMENTSTABLE.COMMENT_ID.eq(pk));
			}
		});
	}

	public int deleteObjects(Serializable... pks) {
		return getDslTemplate().deleteObjects(new DeleteGenerateCallback<Serializable[]>() {
			public Delete generate(Serializable[] t) {
				return delete(COMMENTSTABLE).where(COMMENTSTABLE.COMMENT_ID.in(t));
		}
		},pks);
	}

	public Comments getObjectById(Serializable pk) {
		return getDslTemplate().getObjectById(pk, Comments.class, new SelectGenerateCallback<Serializable>() {
		@SuppressWarnings("rawtypes")
		public Select generate(Serializable t) {
			return selectFrom(COMMENTSTABLE).where(COMMENTSTABLE.COMMENT_ID.eq(t));
			}
		});
	}

	public List<Comments> queryObjects(Comments comments) {
		if(comments==null){
			comments=new Comments();
		}
		return getDslTemplate().queryObjects(comments, new SelectGenerateCallback<Comments>() {

			@SuppressWarnings("rawtypes")
			public Select generate(Comments t) {
				return selectFrom(COMMENTSTABLE).where(
				and(
					COMMENTSTABLE.COMPANY_ID.eq(t.getCompanyId()),
					COMMENTSTABLE.DOC_ID.eq(t.getDocId()),
					COMMENTSTABLE.PARENT_ID.eq(t.getParentId()),
					COMMENTSTABLE.COMMENT_TEXT.eq(t.getCommentText()),
					COMMENTSTABLE.COMMENT_ADDED_BY.eq(t.getCommentAddedBy()),
					COMMENTSTABLE.COMMENT_ADDED_DATE.eq(t.getCommentAddedDate()),
					COMMENTSTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public Pager<Comments> queryObjectsForPage(int start,int limit ,Comments comments) {
		if(comments==null){
			comments=new Comments();
		}
		return getDslTemplate().queryObjectsForPage(start, limit, comments, false, new SelectGenerateCallback<Comments>() {

			public Select generate(Comments t) {
				return MysqlSelect.selectFrom(COMMENTSTABLE).where(
				and(
					COMMENTSTABLE.COMPANY_ID.eq(t.getCompanyId()),
					COMMENTSTABLE.DOC_ID.eq(t.getDocId()),
					COMMENTSTABLE.PARENT_ID.eq(t.getParentId()),
					COMMENTSTABLE.COMMENT_TEXT.eq(t.getCommentText()),
					COMMENTSTABLE.COMMENT_ADDED_BY.eq(t.getCommentAddedBy()),
					COMMENTSTABLE.COMMENT_ADDED_DATE.eq(t.getCommentAddedDate()),
					COMMENTSTABLE.DELETED.eq(t.getDeleted())));
			}
		});
	}

	public int[] batchInsert(boolean autoGeneratedKeys ,List<Comments> commentss) {
		if (CollectionUtil.isEmpty(commentss)) {
			return new int[0];
		}
		return getDslTemplate().batchInsert(autoGeneratedKeys, commentss, new NoParamInsertGenerateCallback() {

			public Insert generate() {
				return insertInto(COMMENTSTABLE).values(
					COMMENTSTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					COMMENTSTABLE.DOC_ID.value(new JdbcNamedParameter("docId")),
					COMMENTSTABLE.PARENT_ID.value(new JdbcNamedParameter("parentId")),
					COMMENTSTABLE.COMMENT_TEXT.value(new JdbcNamedParameter("commentText")),
					COMMENTSTABLE.COMMENT_ADDED_BY.value(new JdbcNamedParameter("commentAddedBy")),
					COMMENTSTABLE.COMMENT_ADDED_DATE.value(new JdbcNamedParameter("commentAddedDate")),
					COMMENTSTABLE.DELETED.value(new JdbcNamedParameter("deleted")));
			}
		});
	}

	public int[] batchInsert(List<Comments> commentss){
			return batchInsert(true ,commentss);
	}

	public int[] batchUpdate(List<Comments> commentss) {
		if (CollectionUtil.isEmpty(commentss)) {
			return new int[0];
		}
		return getDslTemplate().batchUpdate(commentss, new NoParamUpdateGenerateCallback() {

			public Update generate() {
				return update(COMMENTSTABLE).set(
					COMMENTSTABLE.COMPANY_ID.value(new JdbcNamedParameter("companyId")),
					COMMENTSTABLE.DOC_ID.value(new JdbcNamedParameter("docId")),
					COMMENTSTABLE.PARENT_ID.value(new JdbcNamedParameter("parentId")),
					COMMENTSTABLE.COMMENT_TEXT.value(new JdbcNamedParameter("commentText")),
					COMMENTSTABLE.COMMENT_ADDED_BY.value(new JdbcNamedParameter("commentAddedBy")),
					COMMENTSTABLE.COMMENT_ADDED_DATE.value(new JdbcNamedParameter("commentAddedDate")),
					COMMENTSTABLE.DELETED.value(new JdbcNamedParameter("deleted"))).where(
				COMMENTSTABLE.COMMENT_ID.eq(new JdbcNamedParameter("commentId")));
			}
		});
	}

	public int[] batchDelete(List<Comments> commentss) {
		if (CollectionUtil.isEmpty(commentss)) {
			return new int[0];
		}
		return getDslTemplate().batchDelete(commentss, new NoParamDeleteGenerateCallback() {

			public Delete generate() {
				return delete(COMMENTSTABLE).where(and(
				COMMENTSTABLE.COMMENT_ID.eq(new JdbcNamedParameter("commentId")),
				COMMENTSTABLE.COMPANY_ID.eq(new JdbcNamedParameter("companyId")),
				COMMENTSTABLE.DOC_ID.eq(new JdbcNamedParameter("docId")),
				COMMENTSTABLE.PARENT_ID.eq(new JdbcNamedParameter("parentId")),
				COMMENTSTABLE.COMMENT_TEXT.eq(new JdbcNamedParameter("commentText")),
				COMMENTSTABLE.COMMENT_ADDED_BY.eq(new JdbcNamedParameter("commentAddedBy")),
				COMMENTSTABLE.COMMENT_ADDED_DATE.eq(new JdbcNamedParameter("commentAddedDate")),
				COMMENTSTABLE.DELETED.eq(new JdbcNamedParameter("deleted"))));
			}
		});
	}

}
